import{createMotionClock,advanceMotionClock,resetMotionClock}from'../../src/movement.js';
import{ART_OFFSET_Y,OPTIONS,STATIONS,blockedCell,footBox,createState,resetPosition,tick,boundary,frontGap,choiceText,pulse}from'./model.js';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),s=createState({option:params.get('option'),station:params.get('station'),surface:params.get('surface')});
const motionClock=createMotionClock();
const canvas=$('world'),ctx=canvas.getContext('2d'),tc=$('tile').getContext('2d');const images=new Map();let heroManifest,heroImage,ready=false,held=new Set(),zoom=1,last=0,flashUntil=0,contactText='',nativeGap=null;
const names={A:'Quarter structure',B:'Approved · Half and half',C:'Three-quarter structure',D:'Current ground strip'};
function textStatus(t){if(contactText!==t){contactText=t;$('contact-label').textContent=t;}}
function release(){held.clear();s.contact=false;s.lastContact=null;document.querySelectorAll('[data-dir]').forEach(b=>b.setAttribute('aria-pressed','false'));}
function sync(){document.querySelectorAll('[data-option]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.option===s.option));document.querySelectorAll('[data-station]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.station===s.station));$('surface').value=s.surface;$('option-title').textContent=`${s.option} · ${names[s.option]}`;$('split-description').textContent=`The base ends ${OPTIONS[s.option].cut}px down the tile: ${OPTIONS[s.option].cut}px structure, ${32-OPTIONS[s.option].cut}px ground. ${STATIONS[s.station].rear}`;$('movement-description').textContent='Main game movement: one committed 32px tile per step, with the same turns, walk poses and blocked-wall behavior. Every transition cell stays blocked.';if(ready)draw(performance.now());}
for(const [id,o]of Object.entries(OPTIONS)){const b=document.createElement('button');b.className='option';b.dataset.option=id;b.setAttribute('aria-pressed',s.option===id);const letter=document.createElement('span');letter.className='letter';letter.textContent=id;const label=document.createElement('span'),strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=names[id];small.textContent=o.label;label.append(strong,small);const swatch=document.createElement('span');swatch.className='swatch';const fill=document.createElement('i');fill.style.width=o.cut/32*100+'%';swatch.append(fill);b.append(letter,label,swatch);b.onclick=()=>{release();s.option=id;sync();textStatus(`${id}: same collision and position, different visible base.`);};$('options').append(b);}
document.querySelectorAll('[data-station]').forEach(b=>b.onclick=()=>{release();s.station=b.dataset.station;s.surface=s.station==='wall'?'wood':$('surface').value==='wood'?'grass':s.surface;resetPosition(s);sync();textStatus('Hold toward the edge to compare contact.');});
document.querySelectorAll('[data-side]').forEach(b=>b.onclick=()=>{release();resetPosition(s,b.dataset.side);sync();textStatus(b.dataset.side==='behind'?'Stand behind it; lift the art to inspect your clear ground.':'Hold toward the edge to bump it.');});
$('surface').onchange=()=>{s.surface=$('surface').value;sync();};$('zoom').onclick=()=>{zoom=zoom===1?2:1;$('zoom').textContent=zoom===1?'Close view':'Whole area';draw(performance.now());};
for(const id of['collision','grid','cutaway'])$(id).onchange=()=>draw(performance.now());
const supportsVibration=typeof navigator.vibrate==='function';$('haptic').disabled=!supportsVibration;$('haptic').checked=supportsVibration;$('test-haptic').disabled=!supportsVibration;
function hapticMessage(result){$('haptic-status').textContent=result==='requested'?'Vibration request sent. Only your device can confirm the physical response.':result==='declined'?'This browser declined the vibration request. The contact flash still works.':supportsVibration?'Vibration API available; physical response is not verified.':'This browser has no vibration API. The contact flash still works.';}
hapticMessage();$('test-haptic').onclick=()=>hapticMessage(pulse(navigator,true));$('haptic').onchange=()=>{if(!$('haptic').checked)try{navigator.vibrate?.(0);}catch{};};
function bump(now){flashUntil=now+230;textStatus('Blocked · feet stay on clear ground');if($('haptic').checked)hapticMessage(pulse(navigator,true));$('bumps').textContent=s.bumps;}
function hero(c){const frames={down:0,up:4,left:8,right:12},phase={idle:1,strideA:0,strideB:2}[s.pose]??1;const a=heroManifest.assets.find(a=>a.id===`hero-boy.${frames[s.facing]+phase}`);c.drawImage(heroImage,...a.rect,s.px-16,s.py-64,32,64);}
function draw(now){if(!ready)return;ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,480,352);ctx.fillStyle='#254333';ctx.fillRect(0,0,480,352);ctx.save();const camX=zoom===1?0:Math.max(0,Math.min(480-480/zoom,s.px-240/zoom)),camY=zoom===1?0:Math.max(0,Math.min(352-352/zoom,s.py-205/zoom));ctx.scale(zoom,zoom);ctx.translate(-Math.round(camX),-Math.round(camY));const ground=images.get('ground-'+s.surface);for(let y=0;y<11;y++)for(let x=0;x<15;x++){ctx.drawImage(ground,x*32,y*32);if(x===0||x===14||y===0){ctx.fillStyle='#25433355';ctx.fillRect(x*32,y*32,32,32);}}
const fixture=images.get(`${s.station}-${s.surface}-${s.option}`),baseRow=STATIONS[s.station].height,drawY=192+ART_OFFSET_Y-baseRow;const drawFixture=()=>{ctx.save();if($('cutaway').checked)ctx.globalAlpha=.22;ctx.drawImage(fixture,160,drawY);ctx.restore();};if(s.py<=224){hero(ctx);drawFixture();}else{drawFixture();hero(ctx);}
if($('collision').checked){ctx.fillStyle='#c445573b';ctx.strokeStyle='#a43145aa';ctx.lineWidth=1;for(let y=1;y<=10;y++)for(let x=1;x<14;x++)if(blockedCell(s.station,x,y)){ctx.fillRect(x*32,y*32,32,32);ctx.strokeRect(x*32+.5,y*32+.5,31,31);}const b=footBox(s.px,s.py);ctx.strokeStyle='#172e49';ctx.fillStyle='#91dbe57a';ctx.fillRect(b.x,b.y,b.w,b.h);ctx.strokeRect(b.x+.5,b.y+.5,b.w-1,b.h-1);}
if($('grid').checked){ctx.strokeStyle='#193d3840';ctx.lineWidth=1;ctx.beginPath();for(let x=0;x<=480;x+=32){ctx.moveTo(x+.5,0);ctx.lineTo(x+.5,352);}for(let y=0;y<=352;y+=32){ctx.moveTo(0,y+.5);ctx.lineTo(480,y+.5);}ctx.stroke();ctx.strokeStyle='#efb847';ctx.beginPath();ctx.moveTo(160,boundary(s.option)+.5);ctx.lineTo(320,boundary(s.option)+.5);ctx.stroke();}
if(now<flashUntil){ctx.strokeStyle='#ffe4a0';ctx.lineWidth=2;const b=footBox(s.px,s.py);ctx.strokeRect(b.x-2,b.y-2,b.w+4,b.h+4);}ctx.restore();$('contact-label').classList.toggle('bump',now<flashUntil);tc.imageSmoothingEnabled=false;tc.clearRect(0,0,32,32);tc.drawImage(fixture,32,baseRow,32,32,0,0,32,32);const g=frontGap(s);if(g!==nativeGap){$('gap').textContent=g===null?'—':`${g}px`;nativeGap=g;}}
const keys={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',s:'down',a:'left',d:'right'};
window.addEventListener('keydown',e=>{if(e.target.matches('textarea,select,input')||$('copy-dialog').open)return;if(keys[e.key]){e.preventDefault();held.add(keys[e.key]);}if(['1','2','3','4'].includes(e.key))document.querySelector(`[data-option="${'ABCD'[+e.key-1]}"]`).click();});window.addEventListener('keyup',e=>{if(keys[e.key])held.delete(keys[e.key]);});
document.querySelectorAll('[data-dir]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();held.add(b.dataset.dir);b.setPointerCapture(e.pointerId);b.setAttribute('aria-pressed','true');};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>{held.delete(b.dataset.dir);b.setAttribute('aria-pressed','false');};b.oncontextmenu=e=>e.preventDefault();});
window.addEventListener('blur',()=>{release();resetMotionClock(motionClock);});document.addEventListener('visibilitychange',()=>{release();resetMotionClock(motionClock);last=performance.now();});
$('copy').onclick=async()=>{release();const value=choiceText(s,$('notes').value);$('copy-text').value=value;$('copy-dialog').showModal();$('copy-text').select();try{await navigator.clipboard.writeText(value);$('copy-result').textContent='Copied. Paste this preference into chat.';}catch{$('copy-result').textContent='Select and copy this text into chat.';}};$('close-copy').onclick=()=>$('copy-dialog').close();
async function loadImage(id,path){const img=new Image();img.src=path;await img.decode();images.set(id,img);return img;}
async function load(){const base='../../assets/review/contact-lab/';const response=await fetch(base+'manifest.json');if(!response.ok)throw Error('Contact manifest unavailable');const manifest=await response.json();const hp='../../assets/playable/living/';const hr=await fetch(hp+'atlas.json');if(!hr.ok)throw Error('Hero manifest unavailable');heroManifest=await hr.json();const tasks=manifest.assets.map(a=>loadImage(a.id,base+a.image));tasks.push(...['grass','path','paving','wood'].map(g=>loadImage('ground-'+g,base+'ground-'+g+'.png')));tasks.push(loadImage('hero',hp+heroManifest.image).then(img=>heroImage=img));await Promise.all(tasks);ready=true;sync();textStatus('Hold ↑ to approach. Try each option at the same position.');}
function frame(now){if(!last)last=now;if(ready&&!document.hidden){advanceMotionClock(motionClock,Math.max(0,(now-last)/1000),()=>{const result=tick(s,$('copy-dialog').open?null:held);if(result.bump)bump(now);});draw(now);}last=now;requestAnimationFrame(frame);}
export function inspect(){return{artOffsetY:ART_OFFSET_Y,fixtureY:192+ART_OFFSET_Y-STATIONS[s.station].height,state:JSON.parse(JSON.stringify(s)),foot:footBox(s.px,s.py),gap:frontGap(s),ready,zoom,held:[...held],movement:s.motion?JSON.parse(JSON.stringify(s.motion.action)):null};}
try{await load();requestAnimationFrame(frame);}catch(e){textStatus('Could not load the lab. Reload to retry.');console.error(e);}
