// Separate M1.CT1 proposal. Never imports or mutates adventure/editor saves.
export const CELL=32,STEP_SECONDS=280896/16777216;
export const OPTIONS={A:{cut:8,label:'25% structure / 75% ground'},B:{cut:16,label:'50% structure / 50% ground'},C:{cut:24,label:'75% structure / 25% ground'},D:{cut:28,label:'87.5% structure / 12.5% ground'}};
export const STATIONS={house:{name:'House',height:160,top:3,rear:'Roof projects over two clear rear rows.'},wall:{name:'Indoor wall',height:64,top:5,rear:'A short freestanding wall, viewed from inside.'},cliff:{name:'Cliff',height:96,top:4,rear:'Solid mountain edge; not a jumpable ledge.'}};
export const DELTA={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]};
export const FOOT={halfWidth:11,height:8};
export const boundary=option=>6*CELL+OPTIONS[option].cut;
export function blockedCell(station,x,y){if(x<1||x>13||y<1||y>10)return true;return x>=5&&x<=9&&y>=STATIONS[station].top&&y<=6;}
export function footBox(px,py){return{x:px-FOOT.halfWidth,y:py-FOOT.height,w:FOOT.halfWidth*2,h:FOOT.height};}
export function fits(station,px,py){const b=footBox(px,py);for(let y=Math.floor(b.y/CELL);y<=Math.floor((b.y+b.h-1)/CELL);y++)for(let x=Math.floor(b.x/CELL);x<=Math.floor((b.x+b.w-1)/CELL);x++)if(blockedCell(station,x,y))return false;return true;}
export function createState({option='B',station='house',movement='fine',surface='grass'}={}){return{option:Object.hasOwn(OPTIONS,option)?option:'B',station:Object.hasOwn(STATIONS,station)?station:'house',movement:movement==='grid'?'grid':'fine',surface:['grass','path','paving','wood'].includes(surface)?surface:'grass',px:240,py:288,facing:'up',moving:false,step:null,ticks:0,bumps:0,contact:false,lastContact:null};}
export function resetPosition(s,side='front'){const points={front:[240,288,'up'],left:[128,208,'right'],right:[352,208,'left'],behind:[240,STATIONS[s.station].top*32,'down']};const[x,y,dir]=points[side]||points.front;s.px=s.movement==='grid'?Math.floor(x/32)*32+16:x;s.py=s.movement==='grid'?Math.ceil(y/32)*32:y;s.facing=dir;s.step=null;s.moving=false;s.contact=false;s.lastContact=null;return s;}
export function tick(s,direction){s.ticks++;s.moving=false;let bump=false;if(s.step){s.px+=s.step.dx*2;s.py+=s.step.dy*2;s.step.left--;s.moving=true;if(!s.step.left)s.step=null;return{bump:false};}if(!Object.hasOwn(DELTA,direction)){s.contact=false;s.lastContact=null;return{bump:false};}s.facing=direction;const[dx,dy]=DELTA[direction];if(s.movement==='grid'){const x=Math.floor(s.px/32)+dx,y=Math.ceil(s.py/32)-1+dy;if(!blockedCell(s.station,x,y)){s.step={dx,dy,left:15};s.px+=dx*2;s.py+=dy*2;s.moving=true;s.contact=false;s.lastContact=null;return{bump:false};}}else{let advanced=0;for(let i=0;i<2;i++){if(!fits(s.station,s.px+dx,s.py+dy))break;s.px+=dx;s.py+=dy;advanced++;}if(advanced){s.moving=true;s.contact=false;s.lastContact=null;return{bump:false};}}const key=`${direction}/${s.px}/${s.py}`;if(s.lastContact!==key){s.bumps++;bump=true;}s.contact=true;s.lastContact=key;return{bump};}
export function changeMethod(s,movement){s.movement=movement==='grid'?'grid':'fine';resetPosition(s);}
export function frontGap(s){return s.px>=160&&s.px<320&&s.py>=224?s.py-2-boundary(s.option):null;}
export function choiceText(s,notes=''){return JSON.stringify({format:'critz-contact-review',version:1,task:'M1.CT1',option:s.option,structureRows:OPTIONS[s.option].cut,groundRows:32-OPTIONS[s.option].cut,transitionCollision:'entire 32×32 cell blocked',movement:s.movement,method:'native assembly translated inside padded frame, same material boundary for house / indoor wall / cliff',station:s.station,surface:s.surface,notes:String(notes).slice(0,3000),status:'User preference for review; not an automatic production change'},null,2);}
export function pulse(api,enabled){if(!enabled||typeof api?.vibrate!=='function')return'unsupported';try{return api.vibrate(18)?'requested':'declined';}catch{return'declined';}}
