import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {COAST_MASKS,COAST_CONTEXTS,supportedWaterMask,sliverCells,compileCoastalField,coastalBankPixels,coastalWashPixels} from '../src/coastal-format.js';import {COAST_SCENES,coastalMap} from '../src/coastal-layout.js';
const rows=['00000000000','01111001110','01111001110','01111111110','01111111110','01100001110','01100001110','01100001110','01111111110','01111111110','00000000000'],cells=[];for(let y=0;y<11;y++)for(let x=0;x<11;x++)if(rows[y][x]==='1')cells.push({x,y});
function components(p,w){const visited=new Uint8Array(p.length),sizes=[];for(let i=0;i<p.length;i++){if(!p[i]||visited[i])continue;const stack=[i];visited[i]=1;let n=0;while(stack.length){const a=stack.pop();n++;const x=a%w,y=Math.floor(a/w);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const xx=x+dx,yy=y+dy,j=yy*w+xx;if(xx>=0&&xx<w&&yy>=0&&j<p.length&&p[j]&&!visited[j]){visited[j]=1;stack.push(j);}}}sizes.push(n);}return sizes;}
test('Active template set excludes caps, straight one-cell strips and dangling tongues',()=>{assert.equal(COAST_MASKS.length,15);for(const m of [0,1,2,4,8,3,5,10,15])assert.equal(supportedWaterMask(m),false);for(const m of COAST_MASKS)assert.ok(supportedWaterMask(m));const rejected=[{x:0,y:0},{x:0,y:1},{x:0,y:2}];assert.equal(sliverCells(rejected).length,3);assert.equal(sliverCells(cells).length,0);});
test('All playable shore examples exclude one-cell sliver footprints',()=>{for(const s of COAST_SCENES)assert.equal(sliverCells(coastalMap(s).cells).length,0,s);});
test('Shared field retains B side contacts and south registration at straight shores',()=>{const a=[];for(let y=1;y<5;y++)for(let x=1;x<5;x++)a.push({x,y});const f=compileCoastalField(a,192,224);assert.equal(f.wet[96*192+47],0);assert.equal(f.wet[96*192+48],1);assert.equal(f.wet[47*192+96],0);assert.equal(f.wet[48*192+96],1);assert.equal(f.wet[175*192+96],1);assert.equal(f.wet[176*192+96],0);});
test('Every exposed edge in all rotations has bank artwork; no broken inner returns',()=>{for(let turn=0;turn<4;turn++){const a=cells.map(({x,y})=>{for(let n=0;n<turn;n++)[x,y]=[10-y,x];return{x,y};}),f=compileCoastalField(a,352,384),rgba=coastalBankPixels(f),w=f.width;let edges=0;for(let y=1;y<f.height-1;y++)for(let x=1;x<w-1;x++){const i=y*w+x;if(f.wet[i]&&[i-1,i+1,i-w,i+w].some(j=>!f.wet[j])){assert.equal(rgba[i*4+3],255,`${turn}:${x},${y}`);edges++;}}assert.ok(edges>500);assert.equal(components(Uint8Array.from({length:f.wet.length},(_,i)=>rgba[i*4+3]?1:0),w).length,2,'only outer bank and island bank');}});
test('Beach fronts form two continuous rings without spike fragments throughout the loop',()=>{const f=compileCoastalField(cells,352,384);for(let frame=0;frame<32;frame++){const a=coastalWashPixels(f,frame),foam=Uint8Array.from({length:f.wet.length},(_,i)=>a[i*4]===237&&a[i*4+1]===241&&a[i*4+3]?1:0);assert.equal(components(foam,352).length,2,'frame '+frame);}});
test('Sand and water-to-water never receive a raised bank; shallow rim stays shallow',()=>{const f=compileCoastalField(cells,352,384);assert.ok(coastalBankPixels(f,()=>({ground:'sand'})).every(v=>v===0));const rim=coastalBankPixels(f,()=>({ground:'grass',shallow:true}));assert.ok(rim.some(v=>v===255));assert.ok(rim.filter((v,i)=>i%4===3&&v).length<coastalBankPixels(f).filter((v,i)=>i%4===3&&v).length);});
test('Native format exports deduplicated pieces, excludes thin templates, and preserves 3.2 second waves',()=>{const m=JSON.parse(readFileSync(new URL('../assets/review/coastal-format/atlas.json',import.meta.url))),ids=new Set(m.assets.map(a=>a.id));assert.equal(m.thinCaps,false);assert.deepEqual(m.masks,COAST_MASKS);assert.deepEqual(m.contexts,COAST_CONTEXTS);assert.equal(ids.size,3960);assert.equal(m.nativeTileCount,438);assert.equal(m.uniquePixelFrames,354);for(const mask of COAST_CONTEXTS)for(const side of ['inner','outer']){for(const kind of ['shore','surface'])assert.ok(ids.has(`${kind}.${side}.mask.${mask}`));for(let f=0;f<32;f++)assert.ok(ids.has(`shore.${side}.wash.${mask}.${f}`));}const tiled=JSON.parse(readFileSync(new URL('../assets/review/coastal-format/format.tsj',import.meta.url))),animations=tiled.tiles.filter(t=>t.animation);assert.equal(animations.length,84);for(const t of animations)assert.equal(t.animation.reduce((n,f)=>n+f.duration,0),3200);});

test('Colored native export covers all74 material pairs with raw context and no cap templates',()=>{const m=JSON.parse(readFileSync(new URL('../assets/review/coastal-format/colored.json',import.meta.url)));assert.equal(m.thinCaps,false);assert.equal(m.assets.length,4070);assert.equal(m.nativeTileCount,2042);assert.equal(new Set(m.assets.map(a=>a.inner+':'+a.outer)).size,74);for(const a of m.assets)assert.ok(COAST_CONTEXTS.includes(a.rawNeighborMask));});
