import test from 'node:test';import assert from 'node:assert/strict';import {coastalMap,coastalRocks,rockPlacementValid,coastalWalkable,COAST_SCENES} from '../src/coastal-layout.js';import {validateWaterLayout} from '../src/water-layout.js';import {WATER_MASKS} from '../src/water-surfaces.js';import {readFileSync} from 'node:fs';
test('Deep-only grass and beach examples permit direct land contact',()=>{for(const scene of ['showcase','beach','deep-land']){const map=coastalMap(scene);assert.ok(map.cells.some(a=>!a.surface.shallow&&a.mask!==255));assert.deepEqual(validateWaterLayout(20,15,map.get),[]);}});
test('Mixed-depth examples retain complete shallow enclosures without bank geometry',()=>{for(const scene of ['still','moving']){const map=coastalMap(scene);assert.ok(map.cells.some(a=>a.surface.shallow));assert.ok(map.cells.some(a=>!a.surface.shallow));assert.deepEqual(validateWaterLayout(20,15,map.get),[]);}});
test('Every demo rock occupies interior same-type water, away from shore and depth transitions',()=>{for(const scene of COAST_SCENES){const map=coastalMap(scene),rocks=coastalRocks(map);assert.ok(rocks.length);for(const r of rocks)assert.ok(rockPlacementValid(map,r.x,r.y));for(const a of map.cells)if(a.mask!==255||(!a.surface.shallow&&a.depthMask!==255))assert.equal(rockPlacementValid(map,a.x,a.y),false);}});
test('Depth transitions and shore transitions are forbidden rock placements',()=>{const map=coastalMap('still');assert.equal(rockPlacementValid(map,4,4),false);assert.equal(rockPlacementValid(map,6,6),false);assert.equal(rockPlacementValid(map,5,7),false);assert.equal(rockPlacementValid(map,7,7),true);});
test('Shallows walk, deep water blocks, rocks block; boundary land remains reachable',()=>{const map=coastalMap('puddles'),rocks=coastalRocks(map);assert.ok(coastalWalkable(map,rocks,3,6));assert.equal(coastalWalkable(map,rocks,rocks[0].x,rocks[0].y),false);const deep=coastalMap('deep-land');assert.equal(coastalWalkable(deep,coastalRocks(deep),8,4),false);assert.ok(coastalWalkable(deep,coastalRocks(deep),8,3));});
test('Coastal bank covers all sand and raised land joins, corner shapes and animation frames',()=>{const m=JSON.parse(readFileSync(new URL('../assets/review/coastal-water/atlas.json',import.meta.url))),ids=new Set(m.assets.map(a=>a.id));assert.equal(ids.size,6496);assert.equal(m.loopSeconds,3.2);assert.equal(m.waterToWaterBank,false);for(const mask of WATER_MASKS){for(const s of m.surfaces)for(const g of m.grounds){assert.ok(ids.has(`join.${s}.${g}.${mask}`));assert.ok(ids.has(`bank.${s}.${g}.${mask}`));}for(let f=0;f<32;f++)assert.ok(ids.has(`wash.${mask}.${f}`));for(const g of m.grounds.filter(g=>g!=='sand')){assert.ok(ids.has(`ground.sand.${g}.${mask}`));assert.ok(ids.has(`ground.${g}.sand.${mask}`));}}assert.ok(m.assets.filter(a=>a.kind==='rock').every(a=>a.shadowBaked===false));assert.ok(m.assets.filter(a=>a.kind==='cast-shadow').every(a=>a.separateLayer===true));});
import {coastalWaterPixel,CONTACT_RULE} from '../src/coastal-geometry.js';
test('Coastal shore pixels retain approved B half-cell contact while depth edges remain separate',()=>{assert.equal(CONTACT_RULE.id,'B');assert.equal(CONTACT_RULE.structurePixels,16);assert.equal(coastalWaterPixel(15,30,55),false);assert.equal(coastalWaterPixel(16,30,55),true);assert.equal(coastalWaterPixel(16,15,254),false);assert.equal(coastalWaterPixel(16,16,254),true);assert.equal(coastalWaterPixel(16,47,255),true);assert.equal(coastalWaterPixel(16,48,255),true);});
test('Registered shore bank covers all water/land shapes and32 beach frames on32px collision grid',()=>{const m=JSON.parse(readFileSync(new URL('../assets/review/coastal-water/shore-atlas.json',import.meta.url))),ids=new Set(m.assets.map(a=>a.id));assert.equal(ids.size,6016);assert.equal(m.grid,32);assert.equal(m.artHeight,64);assert.equal(m.contactRule.id,'B');for(const mask of WATER_MASKS){for(const s of ['fresh','ocean'])for(const type of ['still','shallow-still','moving','shallow-moving'])for(const g of ['grass','path','soil','paving','cliff','sand']){assert.ok(ids.has(`join.${s}.${type}.${g}.${mask}`));assert.ok(ids.has(`bank.${s}.${type}.${g}.${mask}`));}for(let f=0;f<32;f++)assert.ok(ids.has(`wash.${mask}.${f}`));}});

test('All four inward returns connect half-cell side contacts through the registered overlap',()=>{for(const [m,cx,cy] of [[127,0,0],[239,31,0],[223,31,63],[191,0,63]]){assert.equal(coastalWaterPixel(cx,cy,m),false);for(const [dx,dy,on] of [[15,0,false],[0,15,false],[15,15,true],[12,12,true],[8,8,false]])assert.equal(coastalWaterPixel(cx===0?dx:31-dx,cy===0?dy:63-dy,m),on);}});

import {coastalBoundaryPlanes} from '../src/coastal-composition.js';
test('Assembled inward shoreline removes internal bank and wave tails',()=>{const map=coastalMap('showcase'),p=coastalBoundaryPlanes(map.cells,640,480);for(const x of [3*32+16,12*32+16]){assert.equal(p.wet[(6*32+28)*640+x],1);assert.equal(p.bank[(6*32+28)*640+x],0);assert.equal(p.wash[(6*32+28)*640+x],0);}assert.equal(p.bank[(5*32+17)*640+5*32],1);});
