import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createMotion,advanceMotion,getMotionView} from '../src/movement.js';
import {OPTIONS,STATIONS,createState,tick,resetPosition,fits,blockedCell,footBox,boundary,frontGap,choiceText,pulse} from '../art-review/contact-lab/model.js';

test('all options preserve whole collision cells for every fixture',()=>{for(const station of Object.keys(STATIONS))for(const option of Object.keys(OPTIONS)){for(let x=5;x<=9;x++){assert.equal(blockedCell(station,x,6),true);assert.equal(fits(station,x*32+16,224),false);assert.equal(fits(station,x*32+16,256),true);}assert.equal(boundary(option),224+OPTIONS[option].cut);}});
test('every option uses tile-based game movement, including old fine URLs',()=>{for(const station of Object.keys(STATIONS))for(const option of Object.keys(OPTIONS)){const s=createState({station,option,movement:'fine'});for(let i=0;i<100;i++)tick(s,'up');assert.equal(s.movement,'grid');assert.equal(s.py,256);assert.deepEqual([s.player.x,s.player.y],[7,7]);assert.equal(frontGap(s),30-OPTIONS[option].cut);assert.equal(s.bumps,1);}});
test('lab motion, poses and collision match the actual adventure controller for 3000 ticks',()=>{for(const station of Object.keys(STATIONS)){const s=createState({station}),player={x:7,y:8,facing:'up'},motion=createMotion(player);let seed=423;for(let i=0;i<1000;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const dir=['up','right','down','left',null][seed%5];const v=advanceMotion(motion,new Set(dir?[dir]:[]),false,(x,y)=>!blockedCell(station,x,y),{runAllowed:false});const result=tick(s,dir);assert.deepEqual(result.view,v);assert.deepEqual(s.player,player);assert.equal(s.px,v.x*2+16);assert.equal(s.py,v.y*2+32);assert.equal(s.pose,v.pose);}}});
test('front, rear and both side approaches stay on clear ground',()=>{for(const station of Object.keys(STATIONS))for(const side of ['front','left','right','behind']){const s=createState({station});resetPosition(s,side);const dir=s.facing;for(let i=0;i<300;i++){tick(s,dir);assert.ok(fits(station,s.px,s.py),`${station}/${side}`);}assert.equal(s.bumps,1);assert.equal(s.px%32,16);assert.equal(s.py%32,0);}});
test('rest turns last eight ticks and committed steps finish after release',()=>{const s=createState();for(let i=0;i<8;i++)tick(s,'left');assert.equal(s.motion.action.kind,'turn');assert.deepEqual([s.px,s.py],[240,288]);tick(s,'left');assert.equal(s.px,238);assert.equal(s.player.x,7);for(let i=0;i<15;i++)tick(s,null);assert.equal(s.px,208);assert.equal(s.player.x,6);tick(s,null);assert.equal(s.pose,'idle');assert.equal(getMotionView(s.motion).action,'idle');});
test('corner and boundary stress traces never leave safe ground',()=>{for(const station of Object.keys(STATIONS)){const s=createState({station});let seed=423;for(let i=0;i<10000;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;tick(s,['up','right','down','left',null][seed%5]);assert.ok(fits(station,s.px,s.py));}}});
test('held blocked actions emit one bump; release idles and permits a fresh bump',()=>{const s=createState();for(let i=0;i<200;i++)tick(s,'up');assert.equal(s.bumps,1);tick(s,null);assert.equal(s.pose,'idle');assert.equal(s.contact,false);tick(s,'up');assert.equal(s.bumps,2);});
test('haptic requests are brief, opt-out safe and do not claim physical success',()=>{const calls=[],api={vibrate:n=>{calls.push(n);return true;}};assert.equal(pulse(api,true),'requested');assert.deepEqual(calls,[18]);assert.equal(pulse(api,false),'unsupported');assert.equal(pulse({},true),'unsupported');assert.equal(pulse({vibrate:()=>false},true),'declined');assert.equal(pulse({vibrate:()=>{throw Error('blocked')}},true),'declined');});
test('choice copy records tile movement and actual game controller',()=>{const c=JSON.parse(choiceText(createState({option:'C',station:'cliff',surface:'path'}),'C feels right.'));assert.equal(c.structureRows,24);assert.equal(c.groundRows,8);assert.equal(c.movement,'tile-based');assert.match(c.controller,/src\/movement.js/);assert.equal(c.task,'M1.CT3');assert.equal(c.notes,'C feels right.');});
test('all 48 original art fixtures retain their shared transition geometry',()=>{const m=JSON.parse(readFileSync('assets/review/contact-lab/manifest.json'));assert.equal(m.assets.length,48);assert.equal(m.cells.length,240);for(const a of m.assets){const option=a.id.at(-1);assert.equal(a.materialRows,OPTIONS[option].cut);assert.equal(a.groundRows,32-OPTIONS[option].cut);assert.equal(a.blockedCell,true);assert.equal(a.size[1],a.baseRow+32);}});

test('simultaneous keys use main-game direction priority and keep the remaining key held',()=>{const s=createState();const held=new Set(['left','up']);tick(s,held);assert.equal(s.facing,'up');held.delete('up');for(let i=0;i<15;i++)tick(s,held);tick(s,held);assert.equal(s.facing,'left');assert.equal(s.motion.action.kind,'walk');});
