import test from 'node:test';import assert from 'node:assert/strict';
import {ensureDayClock,advanceDayClock,endDay,clockLabel,validDayClock,worldHour} from '../src/day-clock.js';
import {createState,startMorning,validateState,tick} from '../src/state.js';
import {fishWindow,createTurtle,updateTurtle,turtleOffset,fishPose} from '../src/water-wildlife.js';
test('28-minute day, exact fourteen-second ticks and 2am boundary',()=>{const s=createState();startMorning(s,false);assert.equal(clockLabel(s.dayClock),'6:00 am');assert.equal(advanceDayClock(s,13.999),false);assert.equal(s.dayClock.minute,360);advanceDayClock(s,.001);assert.equal(s.dayClock.minute,370);assert.equal(advanceDayClock(s,1666),true);assert.equal(clockLabel(s.dayClock),'2:00 am');assert.equal(validDayClock(s.dayClock),true);});
test('old v1 saves acquire world time without changing existing progress',()=>{const s=createState();startMorning(s,true);delete s.dayClock;tick(s,24);const copy=structuredClone(s);assert.equal(validateState(s),true);ensureDayClock(s);assert.equal(validateState(s),true);delete s.dayClock;assert.deepEqual(s,copy);});
test('sleep and pass-out start next day at bedroom bed, no money or energy penalty',()=>{for(const minute of [360,1140,1550,1560]){const s=createState();startMorning(s,true);s.scene='forest';s.dayClock.minute=minute;const money=s.money,debt=s.debt,flags=structuredClone(s.flags);assert.equal(endDay(s),(1800-minute)/60);assert.equal(s.dayClock.day,2);assert.equal(s.scene,'bedroom');assert.deepEqual(s.player,{x:3,y:6,facing:'down'});assert.equal(s.money,money);assert.equal(s.debt,debt);assert.deepEqual(s.flags,flags);assert.equal('energy' in s,false);assert.equal(validateState(s),true);}});
test('opening night never progresses; invalid clocks reject saves; legacy hour fallback remains',()=>{const s=createState();ensureDayClock(s);advanceDayClock(s,5000);assert.equal(s.dayClock.minute,360);assert.equal(worldHour(s),22);s.dayClock.minute=NaN;assert.equal(validateState(s),false);delete s.dayClock;s.stage='morning';s.time=21;assert.equal(worldHour(s),21);});
test('foreground schedules retain fourteen-second cadence and midnight label',()=>{for(const fps of [30,60,120]){const s=createState();startMorning(s,false);for(let n=0;n<fps*28+1;n++)advanceDayClock(s,1/fps);assert.equal(s.dayClock.minute,380);}assert.equal(clockLabel({minute:1440}),'12:00 am');});
test('turtle slides on approach, hides then returns only when player is away',()=>{const t=createTurtle(100,100);updateTurtle(t,{x:0,y:0},1);assert.equal(t.phase,'basking');updateTurtle(t,{x:100,y:150},.1);assert.equal(t.phase,'sliding');updateTurtle(t,{x:100,y:150},.4);assert.deepEqual(turtleOffset(t),{x:11,y:6,visible:true});updateTurtle(t,{x:100,y:150},.5);assert.equal(t.phase,'submerged');updateTurtle(t,{x:100,y:150},10);assert.equal(t.phase,'submerged');updateTurtle(t,{x:0,y:0},.1);assert.equal(t.phase,'returning');updateTurtle(t,{x:0,y:0},1);assert.equal(t.phase,'basking');});
test('fish jump only at dawn/dusk; calm removes jumping',()=>{for(const m of [360,470,1080,1190]){assert.ok(fishWindow(m));assert.ok(fishPose(.7,0,m));}for(const m of [480,720,1200,1550])assert.equal(fishPose(.7,0,m),null);assert.equal(fishPose(.7,0,360,true),null);});

test('minute display counts each minute without changing saved ten-minute cadence',()=>{const s=createState();startMorning(s,false);for(let minute=0;minute<20;minute++){assert.equal(clockLabel(s.dayClock),`6:${String(minute).padStart(2,'0')} am`);advanceDayClock(s,1.4);}assert.equal(s.dayClock.minute,380);assert.ok(validateState(s));s.dayClock={day:4,minute:1430,remainder:12.6};assert.equal(clockLabel(s.dayClock),'11:59 pm');advanceDayClock(s,1.4);assert.equal(clockLabel(s.dayClock),'12:00 am');s.dayClock={day:4,minute:1550,remainder:12.6};assert.equal(clockLabel(s.dayClock),'1:59 am');assert.equal(advanceDayClock(s,1.4),true);assert.equal(clockLabel(s.dayClock),'2:00 am');});
