import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {initialState,pay,chooseTub,collect,fishPosition,TUBS,ROOM,blocked,nearTub} from '../art-review/greenhouse-state.js';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'):'/Users/tanoshi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const url=process.env.CRITZ_GREENHOUSE_URL||'http://127.0.0.1:5186/art-review/greenhouse.html';
const output=process.env.CRITZ_QA_OUTPUT||'docs/reviews/M1-LG2';
const executablePath=process.env.CHROMIUM_EXECUTABLE||'/Users/tanoshi/Library/Caches/ms-playwright/chromium_headless_shell-1217/chrome-headless-shell-mac-arm64/chrome-headless-shell';
const report={url,startedAt:new Date().toISOString(),checks:[],screenshots:[],limitations:['Chromium emulation; physical iOS Safari not tested.','Snapshot is read-only. Movement, dialogue, scooping and menus use actual input. Synthetic fixtures only in isolated contexts.']};
await mkdir(output,{recursive:true});const browser=await chromium.launch({executablePath,headless:true});const contexts=[],pages=[];
const KEY='critz.lukes-greenhouse.review.v1';
async function open(fixture=null,options={}){const c=await browser.newContext({viewport:{width:1024,height:800},...options});contexts.push(c);await c.addInitScript(({key,fixture})=>{if(!/^https?:$/.test(location.protocol))return;if(!sessionStorage.getItem('qa-seeded')){localStorage.setItem('critz-tycoon.save.v1','synthetic-adventure-preserve');localStorage.setItem('critz-tycoon.save.v1.backup','synthetic-backup-preserve');if(fixture)localStorage.setItem(key,JSON.stringify(fixture));sessionStorage.setItem('qa-seeded','yes');}window.__saveOps=[];const old=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){window.__saveOps.push(k);return old.call(this,k,v);};},{key:KEY,fixture});const p=await c.newPage();p.qaErrors=[];p.qaFailedAssets=[];p.on('pageerror',e=>p.qaErrors.push(e.message));p.on('response',r=>{if(r.status()>=400)p.qaFailedAssets.push(`${r.status()} ${r.url()}`)});p.on('requestfailed',r=>p.qaFailedAssets.push(r.url()));pages.push(p);await p.goto(url);await p.waitForFunction(()=>!document.querySelector('#begin').disabled);return p;}
async function snapshot(p){return p.evaluate(async()=> (await import('./greenhouse.js')).getReviewSnapshot());}
async function until(p,predicate){const end=Date.now()+8000;while(Date.now()<end){const s=await snapshot(p);if(predicate(s))return s;await p.waitForTimeout(30);}throw Error('Timed out waiting for state: '+JSON.stringify(await snapshot(p)));}
async function check(name,fn){try{const details=await fn();report.checks.push({name,pass:true,details});console.log('PASS '+name);}catch(e){report.checks.push({name,pass:false,error:e.stack});console.error('FAIL '+name+': '+e.message);}}
async function shot(p,name){const file=path.join(output,name);await p.screenshot({path:file,fullPage:true});report.screenshots.push(file);}
async function begin(p,touch=false){await p.locator('#begin')[touch?'tap':'click']();}
async function press(p,key){await p.keyboard.press(key);await p.waitForTimeout(315);}
async function step(p,dir,n=1){for(let i=0;i<n;i++)await press(p,'Arrow'+dir);}
async function enter(p){await step(p,'Up',3);await p.locator('#speech').waitFor({state:'visible'});}
async function answer(p,text){await p.locator('#choices button').filter({hasText:text}).click();}
async function continueSpeech(p){await p.locator('#choices button').first().click();}
async function buy(p){await answer(p,'Yes');await p.locator('#line').filter({hasText:'go ahead'}).waitFor();await continueSpeech(p);await until(p,s=>!s.busy);}
async function goToTub(p,id=6){
 const current=await snapshot(p),queue=[{x:current.player.x,y:current.player.y,path:[]}],seen=new Set([`${current.player.x},${current.player.y}`]);let route;
 for(const a of queue){const facing=['up','down','left','right'].find(d=>nearTub(a.x,a.y,d)?.id===id);if(facing){route={...a,facing};break;}for(const [dir,dx,dy]of [['Up',0,-1],['Down',0,1],['Left',-1,0],['Right',1,0]]){const x=a.x+dx,y=a.y+dy,k=`${x},${y}`;if(!blocked(x,y)&&y!==ROOM.doorY&&!(x===current.luke.x&&y===current.luke.y)&&!seen.has(k)){seen.add(k);queue.push({x,y,path:[...a.path,dir]});}}}
 assert.ok(route,`No walkable approach to tub ${id+1}`);for(const d of route.path)await step(p,d);await step(p,route.facing[0].toUpperCase()+route.facing.slice(1));const at=await snapshot(p);assert.equal(nearTub(at.player.x,at.player.y,at.player.facing)?.id,id);return route.path.length;
}
async function toTub(p){await goToTub(p);await press(p,'z');await p.locator('#line').filter({hasText:'Are you sure'}).waitFor();}
async function inspect(p){await answer(p,'Yes');await p.locator('#line').filter({hasText:'Wait for'}).waitFor();await continueSpeech(p);await until(p,s=>s.mode==='observing');}
async function canvasPoint(p,x,y){return p.locator('#world').evaluate((c,{x,y})=>{const r=c.getBoundingClientRect(),z=Math.min(c.width/480,c.height/340),px=Math.floor((c.width-480*z)/2),py=Math.floor((c.height-340*z)/2);return {x:r.left+(px+x*z)*r.width/c.width,y:r.top+(py+y*z)*r.height/c.height};},{x,y});}
async function tapPool(p,x,y,touch=false){const point=await canvasPoint(p,x,y);await p[touch?'touchscreen':'mouse'][touch?'tap':'click'](point.x,point.y);}
async function catchFish(p,touch=false){const before=await snapshot(p),f=before.fish[0],at=fishPosition(f,before.time+.40);await tapPool(p,at.x,at.y,touch);return until(p,s=>s.mode==='reveal');}
try{
 const p=await open();await check('cover renders actual colored fish pixels',async()=>{const canvases=await p.locator('#cover-fish canvas').evaluateAll(cs=>cs.map(c=>{const a=c.getContext('2d').getImageData(0,0,32,32).data;let opaque=0,colors=new Set();for(let i=0;i<a.length;i+=4)if(a[i+3]){opaque++;colors.add([...a.slice(i,i+3)].join(','));}return {opaque,colors:colors.size};}));assert.equal(canvases.length,3);canvases.forEach(c=>assert.ok(c.opaque>50&&c.colors>3,JSON.stringify(c)));await shot(p,'browser-cover.png');return canvases;});
 await check('keyboard start, north doorway and Luke approach; decline ejects without charge',async()=>{await p.locator('#begin').focus();await p.keyboard.press('Enter');await until(p,s=>s.mode==='walk');await enter(p);const s=await snapshot(p);assert.equal(s.scene,'inside');assert.equal(s.luke.y,ROOM.doorY-2);assert.equal(s.state.money,300);await answer(p,'No');await p.locator('#line').filter({hasText:'GET OUT!'}).waitFor();await shot(p,'browser-get-out.png');await continueSpeech(p);await until(p,s=>s.scene==='outside'&&!s.busy);assert.equal((await snapshot(p)).state.money,300);return {approachToY:ROOM.doorY-2,money:300};});
 await check('insufficient $99 is ejected with no charge and no admission option',async()=>{const q=await open({...initialState(),money:99});await begin(q);await enter(q);assert.match(await q.locator('#line').textContent(),/You have \$99/);assert.equal(await q.locator('#choices button').count(),1);await continueSpeech(q);await q.locator('#line').filter({hasText:'GET OUT!'}).waitFor();await continueSpeech(q);await until(q,s=>s.scene==='outside'&&!s.busy);assert.equal((await snapshot(q)).state.money,99);return {money:99};});
 await check('exact $100 pays once; tub rejection, free miss, timed catch, saved reveal and collection',async()=>{const q=await open({...initialState(),money:100});report.primaryPage=pages.indexOf(q);await begin(q);await enter(q);await buy(q);assert.equal((await snapshot(q)).state.money,0);await toTub(q);await answer(q,'No');assert.equal((await snapshot(q)).state.visit.tub,null);await press(q,'z');await inspect(q);await shot(q,'browser-silhouettes.png');await tapPool(q,45,40);await until(q,s=>s.mode==='observing');assert.equal((await snapshot(q)).state.collection.length,0);assert.equal((await snapshot(q)).state.money,0);await catchFish(q);await q.waitForTimeout(1200);await shot(q,'browser-catch-reveal.png');let s=await snapshot(q);assert.equal(s.state.collection.length,1);assert.equal(s.state.visit.status,'caught');assert.equal(s.state.money,0);const fish=s.state.collection[0];await press(q,'z');await continueSpeech(q);await until(q,s=>s.mode==='walk');await press(q,'z');await until(q,s=>s.mode==='viewing');await continueSpeech(q);assert.equal((await snapshot(q)).state.collection.length,1);await press(q,'x');await press(q,'p');await q.getByRole('button',{name:'Your goldfish',exact:true}).click();assert.equal(await q.locator('.fish-card').count(),1);await shot(q,'browser-collection.png');await q.reload();await q.waitForFunction(()=>!document.querySelector('#begin').disabled);await begin(q);assert.deepEqual((await snapshot(q)).state.collection,[fish]);assert.equal((await snapshot(q)).state.money,0);await continueSpeech(q);await step(q,'Down');await until(q,s=>s.scene==='outside');assert.equal((await snapshot(q)).state.visit,null);await step(q,'Up');await q.locator('#line').filter({hasText:'You have $0'}).waitFor();return {fish,money:0,duplicateAward:false,secondAdmission:true};});
 await check('paid reload resumes without charging; unfinished exit offers and returns $100',async()=>{const q=await open(chooseTub(pay(initialState(),999),6));await begin(q);assert.match(await q.locator('#line').textContent(),/already paid/);assert.equal((await snapshot(q)).state.money,200);await continueSpeech(q);await step(q,'Down');await q.locator('#line').filter({hasText:'return your $100'}).waitFor();await answer(q,'Stay');await until(q,s=>!s.busy);assert.equal((await snapshot(q)).player.y,ROOM.doorY-1);await step(q,'Down');await answer(q,'Leave');await until(q,s=>s.scene==='outside');assert.equal((await snapshot(q)).state.money,300);assert.equal((await snapshot(q)).state.visit,null);return {refund:100};});
 for(const size of [{width:320,height:568},{width:390,height:844},{width:844,height:390}])await check(`phone ${size.width}x${size.height}: touch entry, dialogue, controls and layouts`,async()=>{const q=await open(null,{viewport:size,isMobile:true,hasTouch:true});await shot(q,`browser-cover-${size.width}.png`);await begin(q,true);if(size.width===390)await shot(q,'browser-outside-390.png');for(let i=0;i<3;i++){await q.locator('[data-dir="up"]').tap();await q.waitForTimeout(330);}await q.locator('#speech').waitFor({state:'visible'});const layout=await q.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,innerWidth,scrollHeight:document.documentElement.scrollHeight,innerHeight,controls:[...document.querySelectorAll('#controls button')].map(e=>{const r=e.getBoundingClientRect();return {label:e.textContent,x:r.x,y:r.y,w:r.width,h:r.height};}),speech:(()=>{const r=document.querySelector('#speech').getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};})()}));assert.ok(layout.scrollWidth<=size.width,JSON.stringify(layout));assert.ok(layout.scrollHeight<=size.height,JSON.stringify(layout));for(const b of layout.controls){assert.ok(b.x>=0&&b.x+b.w<=size.width+.5,JSON.stringify(b));assert.ok(b.y>=0&&b.y+b.h<=size.height+.5,JSON.stringify(b));assert.ok(b.w>=44&&b.h>=44,JSON.stringify(b));}assert.ok(layout.speech.y>=0);await shot(q,`browser-dialogue-${size.width}.png`);await q.locator('#choices button').filter({hasText:'Yes'}).tap();await q.locator('#line').filter({hasText:'go ahead'}).waitFor();await q.locator('#a').tap();await until(q,s=>!s.busy);assert.equal((await snapshot(q)).state.money,200);return layout;});
 await check('touch scoop catches the actual moving silhouette',async()=>{const q=await open(pay(initialState(),12345),{viewport:{width:390,height:844},isMobile:true,hasTouch:true});await begin(q,true);await continueSpeech(q);await toTub(q);await inspect(q);await catchFish(q,true);assert.equal((await snapshot(q)).state.collection.length,1);await q.waitForTimeout(1100);await shot(q,'browser-touch-reveal.png');return {touch:true};});
 await check('caught visit permits all eight tubs without payment; exiting resets paid admission',async()=>{const q=await open(collect(chooseTub(pay(initialState(),31),0),0));await begin(q);await continueSpeech(q);for(const tub of TUBS){await goToTub(q,tub.id);await press(q,'z');await until(q,s=>s.mode==='viewing');await continueSpeech(q);assert.equal((await snapshot(q)).selectedTub,tub.id);assert.equal((await snapshot(q)).state.money,200);assert.equal((await snapshot(q)).state.collection.length,1);await press(q,'x');}await shot(q,'browser-room-free-browse.png');await q.reload();await q.waitForFunction(()=>!document.querySelector('#begin').disabled);await begin(q);await continueSpeech(q);await step(q,'Down');await until(q,s=>s.scene==='outside');await step(q,'Up');await q.locator('#line').filter({hasText:'A goldfish for $100?'}).waitFor();assert.equal((await snapshot(q)).state.money,200);await buy(q);assert.equal((await snapshot(q)).state.money,100);assert.equal((await snapshot(q)).state.collection.length,1);return {tubsViewed:8,freeBrowsing:true,freshVisitDebited:100};});
 await check('corrupt review data is retained with disabled start and readable error',async()=>{const q=await open();await q.evaluate(key=>localStorage.setItem(key,'{corrupt-json'),KEY);await q.reload();await q.locator('#begin').filter({hasText:'Review save needs attention'}).waitFor();assert.equal(await q.locator('#begin').isDisabled(),true);assert.match(await q.locator('#overlay .subtle').textContent(),/retained/);assert.equal(await q.evaluate(key=>localStorage.getItem(key),KEY),'{corrupt-json');return {retained:true};});
 await check('keyboard-only reticle aiming and A catch award a moving fish',async()=>{const q=await open(pay(initialState(),456));await q.locator('#begin').focus();await q.keyboard.press('Enter');await q.locator('#speech').waitFor({state:'visible'});await press(q,'z');await toTub(q);await press(q,'z');await q.locator('#line').filter({hasText:'Wait for'}).waitFor();await press(q,'z');await until(q,s=>s.mode==='observing');const initialAim=(await snapshot(q)).aim;await q.keyboard.down('ArrowRight');await q.waitForTimeout(170);await q.keyboard.up('ArrowRight');const movedAim=(await snapshot(q)).aim;assert.ok(movedAim.x>initialAim.x+12);assert.equal(movedAim.y,initialAim.y);let aligned=false,aimUpdates=0;const end=Date.now()+7000;while(Date.now()<end){const s=await snapshot(q),at=fishPosition(s.fish[0],s.time+.4),dx=at.x-s.aim.x,dy=at.y-s.aim.y;if(Math.hypot(dx,dy)<10){aligned=true;break;}const horizontal=Math.abs(dx)>Math.abs(dy),delta=horizontal?dx:dy,key=horizontal?(delta>0?'ArrowRight':'ArrowLeft'):(delta>0?'ArrowDown':'ArrowUp');await q.keyboard.down(key);await q.waitForTimeout(Math.max(30,Math.min(140,Math.abs(delta)/130*1000)));await q.keyboard.up(key);aimUpdates++;}assert.ok(aligned,'Keyboard aim did not converge on moving silhouette');await q.keyboard.press('z');await until(q,s=>s.mode==='reveal');const s=await snapshot(q);assert.equal(s.state.collection.length,1);assert.equal(s.state.money,200);return {initialAim,movedAim,aimUpdates,awarded:s.state.collection[0],pointerUsed:false};});
 await check('review storage write failure preserves purchase and fish award; retry recovers safely',async()=>{async function failWrites(q){await q.evaluate(key=>{const original=Storage.prototype.setItem;window.__restoreReviewWrites=()=>{Storage.prototype.setItem=original;};Storage.prototype.setItem=function(k,v){if(k===key)throw new DOMException('Synthetic quota failure','QuotaExceededError');return original.call(this,k,v);};},KEY);}const q=await open();await failWrites(q);await begin(q);await enter(q);const beforePurchase=(await snapshot(q)).state;await answer(q,'Yes');await q.locator('#speaker').filter({hasText:'Save paused'}).waitFor();assert.match(await q.locator('#line').textContent(),/No money or fish has changed/);assert.deepEqual((await snapshot(q)).state,beforePurchase);assert.equal(await q.evaluate(key=>localStorage.getItem(key),KEY),null);await continueSpeech(q);const r=await open(pay(initialState(),2468));await begin(r);await continueSpeech(r);await toTub(r);await inspect(r);const beforeAward=(await snapshot(r)).state,raw=await r.evaluate(key=>localStorage.getItem(key),KEY);await failWrites(r);const view=await snapshot(r),at=fishPosition(view.fish[0],view.time+.40);await tapPool(r,at.x,at.y);await r.locator('#speaker').filter({hasText:'Save paused'}).waitFor();assert.deepEqual((await snapshot(r)).state,beforeAward);assert.equal(await r.evaluate(key=>localStorage.getItem(key),KEY),raw);assert.equal((await snapshot(r)).mode,'observing');await continueSpeech(r);await r.evaluate(()=>window.__restoreReviewWrites());await catchFish(r);assert.equal((await snapshot(r)).state.collection.length,1);assert.equal((await snapshot(r)).state.money,200);return {purchaseUnchanged:true,awardUnchanged:true,retryAwardedOnce:true};});
 await check('Shadows setting changes only its render layer and survives reload',async()=>{const q=await open(pay(initialState(),777),{viewport:{width:390,height:844}});await begin(q);await continueSpeech(q);const stateBefore=(await snapshot(q)).state;assert.equal((await snapshot(q)).shadows,true);await press(q,'p');await q.getByRole('button',{name:'Settings',exact:true}).click();async function pixels(){await q.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));return q.locator('#world').evaluate(c=>Array.from(c.getContext('2d').getImageData(0,0,c.width,c.height).data));}const on=await pixels(),time=(await snapshot(q)).time;await q.getByRole('button',{name:'Shadows: On',exact:true}).click();const off=await pixels();assert.equal((await snapshot(q)).shadows,false);assert.equal((await snapshot(q)).time,time);let changed=0;for(let i=0;i<on.length;i+=4)if(on[i]!==off[i]||on[i+1]!==off[i+1]||on[i+2]!==off[i+2])changed++;assert.ok(changed>300,`Only ${changed} pixels changed`);assert.ok(changed<on.length/4*.15,'Shadow toggle changed more than15% of the world');await q.getByRole('button',{name:'Shadows: Off',exact:true}).click();assert.deepEqual(await pixels(),on,'Turning shadows back on must restore exact frozen frame');await q.getByRole('button',{name:'Shadows: On',exact:true}).click();assert.deepEqual((await snapshot(q)).state,stateBefore);await shot(q,'browser-settings-shadows-off.png');await q.reload();await q.waitForFunction(()=>!document.querySelector('#begin').disabled);await begin(q);await continueSpeech(q);assert.equal((await snapshot(q)).shadows,false);assert.deepEqual((await snapshot(q)).state,stateBefore);await shot(q,'browser-room-shadows-off.png');await press(q,'p');await q.getByRole('button',{name:'Settings',exact:true}).click();await q.getByRole('button',{name:'Shadows: Off',exact:true}).click();await press(q,'Escape');await shot(q,'browser-room-shadows-on.png');assert.equal((await snapshot(q)).shadows,true);assert.deepEqual(await q.evaluate(()=>JSON.parse(localStorage.getItem('critz.render-settings.v1'))),{shadows:true});return {changedPixels:changed,exactLayerRestoration:true,persistedAcrossReload:true,gameStateUnchanged:true};});
 await check('all17 shiny designs plus ordinary Dorothy render and persist in collection',async()=>{const collection=Array.from({length:17},(_,kind)=>({serial:kind+1,kind,seed:kind+1,shiny:true,variant:kind%12,...(kind===16?{rarity:'legendary'}:{})}));collection.push({serial:18,kind:16,seed:100,shiny:false,variant:0,rarity:'legendary'});const fixture={...initialState(),money:200,nextId:19,collection,visit:{status:'caught',seed:100,tub:0,fishSerial:18,rarities:true}};const q=await open(fixture);await begin(q);await continueSpeech(q);await press(q,'p');await q.getByRole('button',{name:'Your goldfish',exact:true}).click();assert.equal(await q.locator('.fish-card').count(),18);assert.equal(await q.locator('.fish-card b').filter({hasText:'✦'}).count(),17);const pixels=await q.locator('.fish-card canvas').evaluateAll(cs=>cs.map(c=>{const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data,colors=new Set();let opaque=0;for(let i=0;i<d.length;i+=4)if(d[i+3]){opaque++;colors.add(`${d[i]},${d[i+1]},${d[i+2]}`);}return {opaque,colors:colors.size,encoded:c.toDataURL()};}));for(const c of pixels)assert.ok(c.opaque>50&&c.colors>3,JSON.stringify({opaque:c.opaque,colors:c.colors}));assert.notEqual(pixels[16].encoded,pixels[17].encoded);await shot(q,'browser-shiny-collection-desktop.png');await q.setViewportSize({width:390,height:844});await q.locator('.fish-card').last().scrollIntoViewIfNeeded();await shot(q,'browser-dorothy-collection-phone.png');await q.reload();await q.waitForFunction(()=>!document.querySelector('#begin').disabled);await begin(q);await continueSpeech(q);assert.deepEqual((await snapshot(q)).state.collection,collection);assert.equal((await snapshot(q)).state.money,200);await press(q,'p');await q.getByRole('button',{name:'Your goldfish',exact:true}).click();assert.equal(await q.locator('.fish-card').count(),18);return {shinyKinds:17,variants:12,ordinaryDorothy:true,renderedCards:pixels.map(({opaque,colors})=>({opaque,colors})),persistedAcrossReload:true};});
 await check('all contexts preserve main save and backup; no asset or script errors',async()=>{const result=[];for(const p of pages){assert.deepEqual(p.qaErrors,[]);assert.deepEqual(p.qaFailedAssets,[]);const storage=await p.evaluate(()=>({save:localStorage.getItem('critz-tycoon.save.v1'),backup:localStorage.getItem('critz-tycoon.save.v1.backup'),writes:window.__saveOps}));assert.equal(storage.save,'synthetic-adventure-preserve');assert.equal(storage.backup,'synthetic-backup-preserve');assert.ok(storage.writes.every(k=>['critz.lukes-greenhouse.review.v1','critz.render-settings.v1'].includes(k)));result.push({errors:p.qaErrors,failedAssets:p.qaFailedAssets,reviewWrites:storage.writes.filter(k=>k==='critz.lukes-greenhouse.review.v1').length,settingsWrites:storage.writes.filter(k=>k==='critz.render-settings.v1').length});}return result;});
}catch(e){report.fatal=e.stack;console.error(e);}finally{for(const c of contexts)await c.close();await browser.close();report.finishedAt=new Date().toISOString();report.passed=report.checks.filter(c=>c.pass).length;report.failed=report.checks.filter(c=>!c.pass).length;delete report.primaryPage;await writeFile(path.join(output,'browser-report.json'),JSON.stringify(report,null,2)+'\n');}
if(report.failed||report.fatal)process.exitCode=1;
