// Isolated synthetic saves only. No user's profile or storage is accessed.
import {createRequire}from'node:module';import assert from'node:assert/strict';import{mkdir,writeFile}from'node:fs/promises';
import{createState,startMorning,SAVE_KEY}from'../src/state.js';
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE});const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await context.newPage(),errors=[],report=[],out=process.env.TEST_OUTPUT_DIR||'docs/reviews/M1-I4',base=process.env.TEST_URL||'http://127.0.0.1:5173';await mkdir(out,{recursive:true});page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.url()+': '+r.status());});const pass=s=>{report.push(s);console.log('PASS '+s);};
async function load(scene,x,y,time=12){const s=createState('Ari','boy','River');startMorning(s,true);s.scene=scene;s.player={x,y,facing:'down'};s.time=time;s.flags.rescued=['gecko','snail','isopods','springtails'];s.tank.isopods=6;s.tank.springtails=12;await page.goto(base);await page.waitForSelector('[data-action="new"]');await page.evaluate(({key,s})=>localStorage.setItem(key,JSON.stringify(s)),{key:SAVE_KEY,s});await page.reload();await page.locator('[data-action="continue"]').click();return s;}
async function saveCanvas(selector,file){await writeFile(`${out}/${file}.png`,Buffer.from(await page.locator(selector).evaluate(c=>c.toDataURL().split(',')[1]),'base64'));}
try{
 await page.goto(base);await page.locator('[data-action="new"]').click();assert.deepEqual(await page.locator('#boy-preview').evaluate(c=>[c.width,c.height]),[32,64]);await page.screenshot({path:`${out}/phone-character-choice.png`});pass('Both character choices use native 32×64 art');
 await load('bedroom',8,6);await page.locator('#a-button').click();await page.locator('#tank-preview').waitFor();await saveCanvas('#tank-preview','tank-native-display');await page.screenshot({path:`${out}/phone-tank-menu.png`});assert.deepEqual(await page.locator('#tank-preview').evaluate(c=>[c.width,c.height]),[384,288]);pass('25-gallon tank menu uses C7 layers, live census and Manage/Stats/View');
 await page.locator('[data-action="collection"]').click();assert.equal(await page.locator('[data-specimen]').count(),10);assert.equal(await page.locator('[data-habitat]').count(),3);const before=await page.locator('[data-habitat="aquarium"]').evaluate(c=>c.toDataURL());await page.waitForTimeout(200);assert.notEqual(await page.locator('[data-habitat="aquarium"]').evaluate(c=>c.toDataURL()),before);await page.screenshot({path:`${out}/phone-collection.png`,fullPage:true});pass('All ten animated animals and three living habitat demonstrations are available');
 await page.locator('#b-button').click();await page.locator('[data-action="view"]').click();await page.locator('#frame').fill('5');await page.locator('#zoom').fill('160');await saveCanvas('#view-canvas','tank-framed');await page.locator('[data-action="capture"]').click();await page.locator('[data-action="publish"]').waitFor();pass('New tank renderer supports the existing framing and capture flow');
 await load('glass',8,9,12);await saveCanvas('#world','glass-day');await page.screenshot({path:`${out}/phone-glass-day.png`});await load('glass',8,9,22);await saveCanvas('#world','glass-night');pass('Open exterior entrance has daytime threshold light; night uses the saved clock');
 await load('town',26,34,12);await page.keyboard.down('ArrowUp');await page.waitForFunction(async()=> (await import('/src/main.js')).getDebugSnapshot().scene==='glass');await page.keyboard.up('ArrowUp');pass('Walking north into the open storefront enters Glow n’ Blow');
 await load('house',8,10,12);await saveCanvas('#world','home-mat');await page.keyboard.down('ArrowDown');await page.waitForFunction(async()=> (await import('/src/main.js')).getDebugSnapshot().scene==='yard');await page.keyboard.up('ArrowDown');pass('Walking over the interior doormat exits to the correct yard');
 await load('town',21,14,12);await saveCanvas('#world','rootport-day');await load('town',21,14,22);await saveCanvas('#world','rootport-night');
 for(const [scene,x,y]of [['rivalHome',8,9],['critz',8,8],['vet',8,8],['pharmacy',8,8],['bike',8,8],['kaidHome',8,8],['waterworks',8,9]]){await load(scene,x,y);await saveCanvas('#world',scene);}pass('Parents retain fallback art; all shops and new tank world props render');
 for(const width of [320,390,480,844]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}`);}assert.deepEqual(errors,[]);pass('No page errors or missing assets, with 320–844px layouts');
 const verified=await page.evaluate(async()=>{const {loadLivingArt,drawLiving}=await import('/src/living-art.js');await loadLivingArt();const {renderTank}=await import('/src/tank-render.js');const c=document.createElement('canvas');c.width=384;c.height=288;const t={plants:2,isopods:6,springtails:12,food:40,waste:0,algae:0,moisture:65,stress:0};const original=JSON.stringify(t);renderTank(c,t,0);const a=c.toDataURL();renderTank(c,t,0,{frame:5});const panMoves=c.toDataURL()!==a;const variants={};for(const [key,value]of Object.entries({hide:true,plants:6,food:80,waste:90,algae:90,moisture:90,isopods:0,springtails:0})){renderTank(c,{...t,[key]:value},0);variants[key]=c.toDataURL()!==a;}return {variants,panMoves,unchanged:JSON.stringify(t)===original};});assert.equal(verified.unchanged,true);assert.equal(verified.panMoves,true);for(const [k,v]of Object.entries(verified.variants))assert.ok(v,'No visible care effect '+k);pass('Every care/population visual changes without mutating the simulation');
}finally{await writeFile(`${out}/browser-report.json`,JSON.stringify({checks:report,errors},null,2)+'\n');await browser.close();}
