import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {inflateSync} from 'node:zlib';import {createHash} from 'node:crypto';
import {npcIdentity,characterFrame,CRITTERS} from '../src/living-art.js';import {daylight,doorPresentation,approachesDoor} from '../src/lighting.js';import {scenes,getEntities} from '../src/world.js';import {createState,startMorning} from '../src/state.js';
const m=JSON.parse(readFileSync('assets/playable/living/atlas.json')),ids=new Set(m.assets.map(a=>a.id));
test('all 289 packed frames exactly preserve indexed C7 RGBA and duration',()=>{const png=readFileSync('assets/playable/living/atlas.png'),chunks=[];let p=8;while(p<png.length){const n=png.readUInt32BE(p),type=png.toString('ascii',p+4,p+8);if(type==='IDAT')chunks.push(png.subarray(p+8,p+8+n));p+=n+12;}const raw=inflateSync(Buffer.concat(chunks)),stride=m.size[0]*4+1;assert.equal(m.assets.length,289);for(const a of m.assets){const [x,y,w,h]=a.rect,rgba=Buffer.alloc(w*h*4);for(let j=0;j<h;j++){assert.equal(raw[(y+j)*stride],0);raw.copy(rgba,j*w*4,(y+j)*stride+1+x*4,(y+j)*stride+1+(x+w)*4);}const s=JSON.parse(readFileSync(a.source)),f=s.frames[a.sourceFrame];assert.equal(a.ticks,f.ticks);const source=Buffer.alloc(w*h*4);f.pixels.forEach((v,i)=>{if(v)source.set([...Buffer.from(s.palette[v].slice(1),'hex'),255],i*4);});assert.deepEqual(rgba,source,a.id);assert.equal(createHash('sha256').update(rgba).digest('hex'),a.rgbaSHA256);}});
test('every actual NPC resolves to native art or one of the two declared parent fallbacks',()=>{for(const gender of ['boy','girl']){const s=createState('Ari',gender,'River');startMorning(s,false);for(const scene of Object.keys(scenes)){s.scene=scene;for(const e of getEntities(s).filter(e=>e.type==='npc')){const id=npcIdentity(e,gender);if(['rivalMom','rivalDad'].includes(e.id))assert.ok(id.startsWith('legacy.'));else for(let i=0;i<16;i++)assert.ok(ids.has(`${id}.${i}`),`${e.id}: ${id}`);}}assert.equal(npcIdentity({id:'rival'},gender),`rival-${gender==='boy'?'girl':'boy'}`);}assert.equal(CRITTERS.length,10);});
test('directional idle and stride mapping keeps passing poses and source cycle ordering',()=>{for(const [facing,offset]of [['down',0],['up',4],['left',8],['right',12]])assert.deepEqual(['strideA','idle','strideB','passing'].map(p=>characterFrame(facing,p)),[offset,offset+1,offset+2,offset+1]);});
test('saved game clock controls original dawn, day, dusk and night, including opening override',()=>{const s={stage:'morning',time:12};assert.equal(daylight(s).strength,1);assert.equal(daylight({...s,time:0}).strength,0);assert.equal(daylight({...s,time:7}).strength,.5);assert.equal(daylight({...s,time:19}).strength,1/3);assert.equal(daylight({...s,time:36}).strength,1);assert.equal(daylight({...s,stage:'night'}).strength,0);assert.deepEqual(doorPresentation('house',s),{open:false,mat:true,beam:0});assert.deepEqual(doorPresentation('glass',s),{open:true,mat:false,beam:1});assert.equal(doorPresentation('waterworks',{...s,time:22}).beam,0);});

test('door thresholds trigger only when approached into the opening, never while walking across a storefront',()=>{for(const f of ['down','left','right'])assert.equal(approachesDoor(true,false,{id:'vet',y:10},f),false);assert.equal(approachesDoor(true,false,{id:'vet'},'up'),true);assert.equal(approachesDoor(false,true,{id:'exit'},'down'),true);assert.equal(approachesDoor(false,true,{id:'exit'},'left'),false);assert.equal(approachesDoor(false,false,{id:'stairs',y:3},'up'),true);assert.equal(approachesDoor(true,true,{id:'yard'},'left'),false);});
