import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';
import{newProject,newMap,demoProject,paint,cellRecipe,placeObject,blocked,move,resizeMap,flood,validate,exportProject,exportChat,importProject,MATERIALS,FEATURES,STAMPS,clone}from'../map-editor/model.js';
const world=JSON.parse(readFileSync('assets/playable/overworld/master.json')),extra=JSON.parse(readFileSync('assets/review/map-editor/master.json')),ids=new Set([...world.tiles,...extra.tiles].map(t=>t.id));
test('every neighbor shape and every terrain pairing resolves existing native tiles',()=>{for(const kind of MATERIALS)for(const under of MATERIALS)for(let mask=0;mask<256;mask++){const m=newMap();m.terrain.fill(under);m.terrain[4*m.w+4]=kind;for(const[dx,dy,b]of [[0,-1,1],[1,0,2],[0,1,4],[-1,0,8],[1,-1,16],[1,1,32],[-1,1,64],[-1,-1,128]])if(mask&b)m.terrain[(4+dy)*m.w+4+dx]=kind;for(const id of cellRecipe(m,4,4).quadrants)assert.ok(ids.has(id),id);}});
test('terrain edits update neighboring corners and fence connections, including erasure',()=>{const m=newMap();paint(m,4,4,'water');const first=cellRecipe(m,4,4);paint(m,5,4,'water');assert.notDeepEqual(first,cellRecipe(m,4,4));paint(m,4,8,'fence');paint(m,5,8,'fence');paint(m,5,7,'fence');assert.equal(cellRecipe(m,5,8).feature,'fence.9');paint(m,4,8,'erase');assert.equal(cellRecipe(m,5,8).feature,'fence.1');});
test('water boundaries and cliffs block; explicit bridge, stairs and cave cells allow walking',()=>{const m=newMap();for(const t of ['water','cliff']){paint(m,4,4,t);assert.ok(blocked(m,4,4));for(const f of ['bridge','stairs','cave']){paint(m,4,4,f);assert.equal(blocked(m,4,4),false);}}});
test('all four directed ledges require the correct side and a clear two-cell landing',()=>{for(const[dir,dx,dy]of [['down',0,1],['up',0,-1],['left',-1,0],['right',1,0]]){const p=newProject(),m=p.maps[0];paint(m,5+dx,5+dy,'ledge-'+dir);const result=move(p,m.id,{x:5,y:5},dir);assert.deepEqual([result.x,result.y,result.jump],[5+dx*2,5+dy*2,true]);paint(m,5+dx*2,5+dy*2,'water');assert.equal(move(p,m.id,{x:5,y:5},dir),null);}});
test('ledge cannot be crossed backwards or sideways',()=>{const p=newProject(),m=p.maps[0];paint(m,5,5,'ledge-down');assert.equal(move(p,m.id,{x:5,y:6},'up'),null);assert.equal(move(p,m.id,{x:4,y:5},'right'),null);});
test('building footprint, rear strip, door and placement validation are semantic',()=>{const m=newMap();assert.equal(typeof placeObject(m,'cottage',2,2),'object');assert.equal(blocked(m,3,2),false);assert.equal(blocked(m,3,3),true);assert.equal(blocked(m,4,6),false);assert.equal(blocked(m,4,7),false);assert.equal(typeof placeObject(m,'shop',4,4),'string');assert.equal(typeof placeObject(m,'cottage',19,19),'string');paint(m,14,7,'water');assert.equal(typeof placeObject(m,'cottage',12,2),'string');});
test('boulders push only into clear ground; disposable playtest copy isolates edits',()=>{const p=newProject(),m=p.maps[0];placeObject(m,'boulder',4,4);const copy=clone(p);assert.ok(move(copy,m.id,{x:3,y:4},'right'));assert.equal(copy.maps[0].objects[0].x,5);assert.equal(m.objects[0].x,4);paint(copy.maps[0],6,4,'water');assert.equal(move(copy,m.id,{x:4,y:4},'right'),null);});
test('edge links apply positive/negative alignment offsets and block invalid landings',()=>{const p=newProject(),m=p.maps[0],b=newMap('map-2','Route',30,30);p.maps.push(b);m.connections.push({direction:'up',target:b.id,offset:3});b.connections.push({direction:'down',target:m.id,offset:-3});let dest=move(p,m.id,{x:9,y:0},'up');assert.deepEqual([dest.map,dest.x,dest.y],[b.id,6,29]);assert.equal(move(p,b.id,{x:6,y:29},'down').x,9);paint(b,6,29,'water');assert.equal(move(p,m.id,{x:9,y:0},'up'),null);});
test('entrance warps require approach direction and preserve explicit destination',()=>{const p=newProject(),m=p.maps[0],b=newMap('room','Room',11,9);p.maps.push(b);m.warps.push({x:4,y:4,direction:'up',target:b.id,tx:5,ty:7});assert.equal(move(p,m.id,{x:4,y:5},'up').map,'room');assert.equal(move(p,m.id,{x:3,y:4},'right').map,m.id);paint(b,5,7,'water');assert.equal(move(p,m.id,{x:4,y:5},'up'),null);});
test('flood stays within material boundaries and resizing preserves in-bounds semantics',()=>{const m=newMap();for(let y=0;y<m.h;y++)paint(m,10,y,'water');flood(m,1,1,'path');assert.equal(m.terrain[1],'path');assert.equal(m.terrain[11],'grass');m.raw[5]={id:'rock.0',blocked:true};resizeMap(m,30,25);assert.deepEqual(m.raw[5],{id:'rock.0',blocked:true});assert.equal(m.terrain[11],'grass');assert.equal(m.terrain[30*24+29],'grass');});
test('copy/import roundtrip retains every terrain cell, stamp, note and connection',()=>{const p=demoProject();p.notes='Keep the animals safe.';const m=p.maps[0];m.raw[300]={id:'rock.1',blocked:true};p.maps.push(newMap('other','Second map'));m.connections.push({direction:'up',target:'other',offset:0});const restored=importProject(exportProject(p),ids);assert.deepEqual(restored,p);assert.deepEqual(validate(restored),[]);});
test('import rejects malformed dimensions, unknown assets, overlap, duplicate maps and nonintegers',()=>{const fixtures=[p=>p.maps[0].w=NaN,p=>p.maps[0].terrain[0]='lava',p=>p.maps.push(clone(p.maps[0])),p=>p.maps[0].raw[0]={id:'no-such-tile',blocked:true},p=>p.maps[0].spawn.x=1.5,p=>p.maps[0].objects.push({id:'bad',type:'bad',x:1,y:1})];for(const mutate of fixtures){const p=newProject();mutate(p);assert.throws(()=>importProject(JSON.stringify(p),ids));}});
test('every available stamp refers to existing art; every feature has renderable source',()=>{for(const s of Object.values(STAMPS)){if(s.assembly){assert.ok(world.assemblies[s.assembly]);for(const row of world.assemblies[s.assembly])for(const id of row)assert.ok(ids.has(id));}else assert.ok(ids.has(s.tile));}for(const f of FEATURES.filter(f=>f&&!['fence','tallgrass','flowers','bridge'].includes(f)))assert.ok(ids.has('feature.'+f));});

test('compact chat RLE is lossless and rejects expansion bombs',()=>{const p=demoProject();assert.deepEqual(importProject(exportChat(p),ids),p);assert.ok(exportChat(p).length<exportProject(p).length/3);const q=JSON.parse(exportChat(p));q.maps[0].terrain=[['grass',999999999]];assert.throws(()=>importProject(JSON.stringify(q),ids));});

test('map check catches a connected edge with no aligned clear crossing',()=>{const p=newProject(),m=p.maps[0],b=newMap('b','Other');p.maps.push(b);m.connections.push({direction:'up',target:'b',offset:60});assert.ok(validate(p).some(s=>s.includes('no clear aligned crossing')));});

test('all freshwater and ocean depths/motions plus sand survive export and play collisions',()=>{
 const p=newProject(),m=p.maps[0];let x=1;
 for(const identity of ['fresh','ocean'])for(const type of ['still','moving','shallow-still','shallow-moving']){const id=`water-${identity}-${type}`;paint(m,x,2,id);assert.equal(blocked(m,x,2),!type.startsWith('shallow'));x++;}
 paint(m,1,3,'sand');assert.equal(blocked(m,1,3),false);
 const restored=importProject(exportProject(p));assert.deepEqual(restored,p);
});
