import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'):'playwright');
const url=process.env.CRITZ_OVERWORLD_URL||'http://localhost:5173/art-review/overworld.html';
const output=process.env.CRITZ_QA_OUTPUT||'test-results/overworld';await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE});const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
const page=await context.newPage(),errors=[],requests=[],report=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)requests.push([r.url(),r.status()]);});
await context.addInitScript(()=>{localStorage.setItem('critz-tycoon.save.v1','synthetic-overworld-sentinel');const get=Storage.prototype.getItem;window.readTestSave=()=>get.call(localStorage,'critz-tycoon.save.v1');Storage.prototype.getItem=Storage.prototype.setItem=Storage.prototype.removeItem=function(){throw Error('Review accessed browser storage');};});
async function test(name,fn){await fn();report.push({name,pass:true});console.log('PASS '+name);}
try{
await page.goto(url);await page.waitForFunction(()=>document.documentElement.dataset.overworldReady==='true');
await test('385 atlas tiles load, no missing network assets',async()=>{assert.equal(await page.locator('.tile-grid button').count(),385);assert.deepEqual(requests,[]);});
await test('Five views, exact canvas dimensions, export browser pixels for independent comparison',async()=>{for(const [view,size]of [['town',[1024,768]],['cottage',[480,320]],['water',[480,320]],['construction',[960,576]],['terrain',[1024,768]]]){await page.locator(`[data-view=${view}]`).click();const value=await page.locator('#scene').evaluate(c=>({width:c.width,height:c.height,png:c.toDataURL().split(',')[1]}));assert.deepEqual([value.width,value.height],size);await writeFile(path.join(output,`canvas-${view}.png`),Buffer.from(value.png,'base64'));}});
await test('Grid overlay toggles and native 1× / 2× / 3× are exact',async()=>{await page.locator('[data-view=cottage]').click();const before=await page.locator('#scene').evaluate(c=>c.toDataURL());await page.locator('#grid').check();assert.notEqual(await page.locator('#scene').evaluate(c=>c.toDataURL()),before);await page.locator('#grid').uncheck();assert.equal(await page.locator('#scene').evaluate(c=>c.toDataURL()),before);for(const n of [1,2,3]){await page.locator('#zoom').selectOption(String(n));assert.equal(await page.locator('#scene').evaluate(c=>c.getBoundingClientRect().width/c.width),n);}});
await test('Building can extend from 5 to 11 cells and switch roof material',async()=>{const before=await page.locator('#building').evaluate(c=>c.toDataURL());for(const n of [5,7,9,11]){await page.locator('#width').fill(String(n));assert.equal(await page.locator('#building').evaluate(c=>c.width),n*32);assert.equal(await page.locator('#width-label').textContent(),`${n} cells`);}await page.locator('#width').fill('5');await page.locator('#roof').selectOption('teal');assert.notEqual(await page.locator('#building').evaluate(c=>c.toDataURL()),before);});
await test('Library filtering and per-tile coordinate inspection',async()=>{await page.locator('#search').fill('water.');assert.equal(await page.locator('.tile-grid button').count(),47);await page.getByRole('button',{name:'water.255',exact:true}).click();assert.equal(await page.locator('#tile-id').textContent(),'water.255');assert.match(await page.locator('#tile-info').textContent(),/32 × 32/);await page.locator('#search').fill('no-such-tile');assert.equal(await page.locator('.tile-grid button').count(),0);await page.locator('#search').fill('');await page.locator('#category').selectOption('1');assert.equal(await page.locator('.tile-grid button').count(),47);await page.locator('#category').selectOption('all');});
await test('Desktop and phone layout have no document overflow; screenshot review',async()=>{await page.locator('#zoom').selectOption('fit');await page.locator('[data-view=town]').click();for(const [w,h]of [[1440,1000],[390,844],[320,568],[844,390]]){await page.setViewportSize({width:w,height:h});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow ${w}`);await page.screenshot({path:path.join(output,`review-${w}.png`),fullPage:true});}});
await test('PNG, metadata, Tiled and ZIP downloads return valid bytes',async()=>{for(const name of ['master.png','master.json','master.tsj','critz-overworld-v1.zip']){const r=await context.request.get(new URL('../assets/review/overworld-v1/'+name,url).href);assert.equal(r.status(),200);const b=await r.body();assert.ok(b.length>100);if(name.endsWith('.zip'))assert.equal(b.subarray(0,2).toString(),'PK');}});
await test('No runtime errors or storage calls; isolated synthetic save preserved',async()=>{assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>window.readTestSave()),'synthetic-overworld-sentinel');});
}finally{await writeFile(path.join(output,'browser-report.json'),JSON.stringify(report,null,2)+'\n');await browser.close();}
