import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {PRESETS,TICK_MS,makeProject,validateProject,line,fill,describe,gifBytes} from '../sprite-editor/model.js';
const banks=JSON.parse(readFileSync(new URL('../sprite-editor/palettes.json',import.meta.url))).banks;
const colors=banks[0].colors,allowed=new Set(banks.flatMap(b=>b.colors));
test('preset dimensions and actual project palette sources',()=>{assert.deepEqual(PRESETS.slice(0,7).map(p=>p.slice(2,4)),[[32,64],[128,128],[32,32],[64,64],[64,64],[16,16],[32,32]]);assert.deepEqual(PRESETS.find(p=>p[0]==='screen').slice(2,4),[480,320]);for(const b of banks.filter(b=>b.legacy)){const source=JSON.parse(readFileSync(new URL('../'+b.source,import.meta.url)));const actual=source.palette?Object.values(source.palette):source.palettes?source.palettes[b.id].filter(v=>v!=='transparent'):Object.values(source);assert.deepEqual(b.colors,actual.map(v=>v.toLowerCase()));}assert.equal(colors.length,31);assert.deepEqual(banks[0].slots.map(s=>s.hex),["#00000000","#E84038","#FC7858","#FCD080","#289870","#48D098","#A0F8D0","#F85888","#082048","#184080","#3878B8","#68B0E0","#98E0F8","#F8F8F8","#201008","#482810","#784820","#A87038","#D0A068","#F8D8B0","#083018","#185828","#388840","#68B858","#A0E068","#D8F880","#282830","#484850","#707078","#9898A0","#C0C0C8","#E0E0E8"]);});
test('continuous native-pixel line, bounded fill and transparent holes',()=>{const p=makeProject(colors,'tile'),pixels=p.frames[0].pixels;line(1,1,14,14,(x,y)=>pixels[y*16+x]=1);for(let n=1;n<=14;n++)assert.equal(pixels[n*16+n],1);fill(pixels,16,16,0,0,2);assert.equal(pixels[17],1);assert.equal(pixels[0],2);assert.equal(pixels[255],2);fill(pixels,16,16,1,1,0);assert.equal(pixels[17],0);assert.equal(pixels[34],1);});
test('lossless copy reconstructs every frame, transparency and timing',()=>{const p=makeProject(colors);p.frames[0].pixels[100]=1;p.frames[0].pixels[101]=2;p.frames.push({...p.frames[0],name:'Stride',ticks:5,pixels:[...p.frames[0].pixels]});p.frames[1].pixels[200]=3;const info=JSON.parse(describe(p));for(let n=0;n<p.frames.length;n++){const decoded=info.frames[n].rows.flatMap(row=>{const a=[];for(let i=0;i<row.length;i+=2)a.push(...Array(row[i+1]).fill(row[i]));return a;});assert.deepEqual(decoded,p.frames[n].pixels);assert.equal(info.frames[n].durationMilliseconds,p.frames[n].ticks*TICK_MS);}assert.equal(info.palette[1],colors[0]);assert.equal(info.palette[0],null);});
test('project validation rejects malformed, foreign-color, oversized, and overbudget files',()=>{const p=makeProject(colors);assert.equal(validateProject(p,allowed),p);for(const mutate of [q=>q.width=.5,q=>q.frames[0].pixels.pop(),q=>q.frames[0].pixels[0]=99,q=>q.palette.push('#ff00fe'),q=>q.frames[0].ticks=0,q=>q.frames=Array(65).fill(q.frames[0]),q=>q.notes={}]){const q=structuredClone(p);mutate(q);assert.throws(()=>validateProject(q,allowed));}const q=structuredClone(p);q.palette.push(banks[1].colors.find(c=>!q.palette.includes(c)));for(let i=1;i<=32;i++)q.frames[0].pixels[i]=i;assert.throws(()=>validateProject(q,allowed),/31 opaque/);});
test('GIF export preserves indexed colors and frame timing in an independent decoder fixture',()=>{const p=makeProject(colors,'tile');p.frames[0].pixels[17]=1;p.frames.push({name:'Stride',ticks:5,pixels:Array(256).fill(0)});p.frames[1].pixels[200]=2;mkdirSync('test-results/sprite-editor',{recursive:true});writeFileSync('test-results/sprite-editor/test.gif',gifBytes(p));writeFileSync('test-results/sprite-editor/gif-source.json',JSON.stringify(p));assert.equal(Buffer.from(gifBytes(p)).subarray(0,6).toString(),'GIF89a');});

test('all 31 new colors can coexist; prior project colors round-trip unchanged',()=>{const p=makeProject(colors);for(let i=1;i<=31;i++)p.frames[0].pixels[i]=i;assert.equal(validateProject(p,allowed),p);const old=makeProject(banks[1].colors);old.bank='hero';old.frames[0].pixels[10]=1;const before=JSON.stringify(old);validateProject(old,allowed);assert.equal(JSON.stringify(old),before);assert.equal(old.palette[1],'#292532');});
