import {createRequire}from'node:module';import assert from'node:assert/strict';import{mkdir,writeFile}from'node:fs/promises';
import{createState,startMorning,SAVE_KEY}from'../src/state.js';
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright'),browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE});const ctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await ctx.newPage(),errors=[],checks=[],out=process.env.TEST_OUTPUT_DIR||'docs/reviews/M1-UI1',url=process.env.TEST_URL||'http://localhost:5173';await mkdir(out,{recursive:true});page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.url());});const pass=s=>{checks.push(s);console.log('PASS '+s);};const ui=()=>page.evaluate(async()=> (await import('/src/main.js')).getDebugUI());const actors=()=>page.evaluate(async()=> (await import('/src/main.js')).getDebugActors());
async function fixture(scene='town',x=21,y=26,night=false){await page.goto(url);await page.waitForSelector('[data-action=new]');const s=createState('Ari','boy','River');if(!night)startMorning(s,true);s.scene=scene;s.player={x,y,facing:'up'};await page.evaluate(({s,key})=>localStorage.setItem(key,JSON.stringify(s)),{s,key:SAVE_KEY});await page.reload();await page.locator('[data-action=continue]').click();}
async function finish(){for(let i=0;i<160&&await page.locator('#dialogue').isVisible();i++)await page.locator('#a-button').click();assert.equal(await page.locator('#dialogue').isVisible(),false);}
try{
 await fixture();await page.locator('#start').click();assert.equal(await page.locator('.command').count(),7);await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>document.activeElement.dataset.action),'bag');await page.keyboard.press('z');assert.equal((await ui()).panel,'bag');await page.keyboard.press('Escape');assert.equal((await ui()).panel,'pause');assert.equal(await page.evaluate(()=>document.activeElement.dataset.action),'bag');
 await page.screenshot({path:`${out}/phone-menu.png`});pass('Seven-command menu supports D-pad/keyboard, A confirm, B return and remembered cursor');
 await page.locator('[data-action=options]').click();assert.equal(await page.getByText('FAST',{exact:true}).count(),1);assert.equal(await page.getByText('Slow',{exact:true}).count(),0);await page.waitForFunction(()=>document.getElementById('text-sample')?.textContent.length>20);const saveBefore=await page.evaluate(k=>localStorage.getItem(k),SAVE_KEY);await page.locator('[data-action=frame-style]').focus();await page.keyboard.press('ArrowRight');assert.equal((await ui()).settings.frame,'ocean');await page.locator('[data-action=calm-motion]').click();assert.equal((await ui()).settings.calm,true);assert.equal(await page.evaluate(k=>localStorage.getItem(k),SAVE_KEY),saveBefore);await page.screenshot({path:`${out}/phone-options.png`});await page.reload();await page.waitForSelector('[data-action=continue]');assert.deepEqual((await ui()).settings,{frame:'ocean',calm:true});pass('Fast-only options, left/right setting changes, preview and separate preference persistence');
 await page.locator('[data-action=options]').click();await page.locator('[data-action=calm-motion]').click();await page.locator('[data-action=back]').last().click();assert.equal((await ui()).panel,'title');
 await fixture('bedroom',8,6,true);await page.waitForTimeout(110);const partial=await page.locator('#dialogue-text').textContent();assert.ok(partial.length>0&&partial.length<60,partial);assert.equal((await ui()).typing,true);await page.locator('#a-button').click();assert.equal((await ui()).typing,false);const full=await page.locator('#dialogue-text').textContent();assert.ok(full.startsWith(partial));await page.screenshot({path:`${out}/phone-dialogue.png`});await finish();pass('Fast text visibly types; first A reveals the page, subsequent A advances without skipping');
 await page.locator('#a-button').click();let hopped=false,question=false;for(let i=0;i<140&&await page.locator('#dialogue').isVisible();i++){
  const text=await page.locator('#dialogue-accessible').textContent();if(!question&&text.includes('Mom?')){await page.waitForTimeout(110);assert.equal((await actors()).reactions.find(a=>a.id==='hero')?.mark,'?');question=true;await page.screenshot({path:`${out}/question-reaction.png`});}
  if(!hopped&&text.includes('Then we’ll find everybody. First:')){await page.waitForTimeout(100);assert.ok((await actors()).reactions.find(a=>a.id==='kaid')?.hop>0);await page.screenshot({path:`${out}/birthday-hop.png`});hopped=true;}
  await page.locator('#a-button').click();
 }assert.ok(hopped&&question);await page.locator('[data-action=decline-loan]').waitFor();pass('Opening uses question/exclamation reactions and birthday hop, then reaches the unchanged loan choice');
 await fixture();const before=await actors();await page.waitForTimeout(4300);const after=await actors();for(const id of ['nugget','kaid','rival'])assert.notDeepEqual(after.actors.find(a=>a.id===id),before.actors.find(a=>a.id===id));await page.locator('#start').click();const paused=(await actors()).actors;await page.waitForTimeout(600);assert.deepEqual((await actors()).actors,paused);pass('All three outdoor NPCs walk their loops and freeze in menus');
 await fixture('town',22,25);await page.locator('#a-button').click();await page.waitForSelector('#dialogue:not([hidden])');assert.equal((await actors()).speaker,'nugget');assert.equal((await actors()).actors.find(a=>a.id==='nugget').facing,'down');await page.screenshot({path:`${out}/nugget-greeting.png`});const strip=a=>a.map(({view,...rest})=>rest);const frozen=strip((await actors()).actors);await page.waitForTimeout(600);assert.deepEqual(strip((await actors()).actors),frozen);pass('NPC conversation faces the player and pauses the patrol');await finish();
 for(const [w,h]of [[320,568],[390,844],[844,390],[1280,900]]){await page.setViewportSize({width:w,height:h});await page.locator('#start').click();if((await ui()).panel!=='pause')await page.locator('#start').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('[data-action=options]').click();const rect=await page.locator('#panel').boundingBox();assert.ok(rect.x>=0&&rect.y>=0&&rect.x+rect.width<=w+1&&rect.y+rect.height<=h+1);await page.screenshot({path:`${out}/options-${w}.png`});await page.locator('#b-button').click();await page.locator('#b-button').click();}pass('320px portrait through desktop and landscape retain panels and controls without overflow');assert.deepEqual(errors,[]);pass('No missing assets or uncaught browser exceptions');
}finally{await writeFile(`${out}/browser-report.json`,JSON.stringify({checks,errors},null,2)+'\n');await browser.close();}
