import test from 'node:test';import assert from 'node:assert/strict';
import {createPrinter,advancePrinter,finishPrinter,printerComplete,paginate,FAST_TEXT_SECONDS} from '../src/dialogue.js';
import {initializeActors,updateActors,actorDebug,actorEntity,actorView,facePlayer,releaseActors,cueActor,PATROLS} from '../src/actors.js';
import {readSettings,writeSettings,UI_SETTINGS_KEY} from '../src/ui-settings.js';
import {createState,startMorning} from '../src/state.js';import {scenes,getEntities,isBlocked} from '../src/world.js';
test('fast typing is one grapheme per source tick at 30/60/120Hz and A reveal does not destroy content',()=>{for(const hz of [30,60,120]){const p=createPrinter('Hello, tiny world! 👨‍👩‍👧');for(let i=0;i<hz/5;i++)advancePrinter(p,1/hz);assert.equal(p.count,Math.floor(.2/FAST_TEXT_SECONDS));assert.equal(printerComplete(p),false);assert.equal(finishPrinter(p),'Hello, tiny world! 👨‍👩‍👧');assert.ok(printerComplete(p));}});
test('two-line pagination preserves words, punctuation, long names and Unicode',()=>{for(const text of ['Hello, tiny world! A new beginning awaits.','Supercalifragilisticexpialidocious is a name.','Ari 🌿 meets Kaid.']){const pages=paginate(text,s=>Array.from(s).length,12);assert.ok(pages.every(p=>p.split('\n').length<=2));assert.equal(pages.join('\n').replace(/\s/g,''),text.replace(/\s/g,''));}});
function fixture(scene='town'){const s=createState();startMorning(s,true);s.scene=scene;s.player={x:21,y:26,facing:'up'};initializeActors(s,scenes[scene].entities);return s;}
const step=(s,n=1,extra={})=>{for(let i=0;i<n;i++)updateActors(s,FAST_TEXT_SECONDS,{canEnter:(x,y)=>!isBlocked(s.scene,x,y)&&!getEntities(s).some(e=>e.type==='door'&&e.x===x&&e.y===y),...extra});};
test('all authored NPC paths are cardinal, walkable and clear of every doorway',()=>{for(const [id,path]of Object.entries(PATROLS)){const [scene,npc]=id.split(':'),e=scenes[scene].entities.find(e=>e.id===npc);for(let i=0;i<path.length;i++){const p=path[i],q=path[(i+1)%path.length];assert.equal(Math.abs(p[0]-q[0])+Math.abs(p[1]-q[1]),1);assert.equal(isBlocked(scene,e.x+p[0],e.y+p[1]),false,id);assert.ok(!scenes[scene].entities.some(d=>d.type==='door'&&d.x===e.x+p[0]&&d.y===e.y+p[1]));}}});
test('patrols animate, reserve both step cells, pause and keep every saved field unchanged',()=>{const s=fixture(),before=structuredClone(s);let moving;for(let i=0;i<600&&!moving;i++){step(s);moving=actorDebug(s).actors.find(a=>a.step);}assert.ok(moving);const e=actorEntity(s,scenes.town.entities.find(e=>e.id===moving.id));assert.equal(isBlocked('town',e.x,e.y,s),true);assert.equal(isBlocked('town',...e.reserved,s),true);const frozen=actorDebug(s).actors;step(s,100,{paused:true});assert.deepEqual(actorDebug(s).actors,frozen);step(s,16);assert.notDeepEqual(actorDebug(s).actors,frozen);assert.deepEqual(s,before);});
test('NPCs wait near the player and cannot enter a player destination',()=>{const s=fixture();s.player={x:22,y:25,facing:'up'};step(s,600);const a=actorDebug(s).actors.find(a=>a.id==='nugget');assert.deepEqual([a.x,a.y],[22,24]);s.player={x:10,y:20,facing:'up'};step(s,600,{playerDestination:{x:23,y:24}});assert.equal(actorDebug(s).actors.find(a=>a.id==='nugget').x,22);});
test('talking faces player, short reactions expire, calm eliminates the hop, no save mutation',()=>{const s=fixture();facePlayer(s,'nugget');cueActor(s,'nugget',{mark:'!',hop:true});step(s,8,{paused:true});assert.ok(actorView(s,'nugget').hop>0);assert.equal(actorView(s,'nugget').mark,'!');step(s,1,{paused:true,calm:true});assert.equal(actorView(s,'nugget').hop,0);step(s,100,{paused:true});assert.equal(actorView(s,'nugget').mark,null);releaseActors(s);assert.equal(actorDebug(s).speaker,null);});
test('options use a separate validated key and tolerate unavailable storage',()=>{const data=new Map([['critz-tycoon.save.v1','sentinel']]),store={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};assert.deepEqual(readSettings(store),{frame:'leaf',calm:false});assert.ok(writeSettings(store,{frame:'ocean',calm:true}));assert.equal(data.get('critz-tycoon.save.v1'),'sentinel');assert.equal(readSettings(store).frame,'ocean');data.set(UI_SETTINGS_KEY,'{"frame":"bad","calm":1}');assert.deepEqual(readSettings(store,true),{frame:'leaf',calm:true});assert.equal(writeSettings({setItem(){throw Error();}},{frame:'leaf',calm:false}),false);});
test('all outdoor patrol footprints leave a route from every doorstep to the town spawn',()=>{const blocked=new Set(Object.entries(PATROLS).filter(([key])=>key.startsWith('town:')).flatMap(([key,path])=>{const e=scenes.town.entities.find(e=>e.id===key.split(':')[1]);return path.map(([x,y])=>`${e.x+x},${e.y+y}`);}));const queue=[scenes.town.safeSpawn],seen=new Set([queue[0].join(',')]);for(let i=0;i<queue.length;i++){const [x,y]=queue[i];for(const [dx,dy]of [[0,1],[0,-1],[1,0],[-1,0]]){const a=x+dx,b=y+dy,k=`${a},${b}`;if(!seen.has(k)&&!blocked.has(k)&&!isBlocked('town',a,b)){seen.add(k);queue.push([a,b]);}}}for(const e of scenes.town.entities.filter(e=>e.type==='door'))assert.ok(seen.has(`${e.x},${e.y}`),e.id);});
