// Fresh isolated browser only: synthetic saves, real held input, no user profile.
import assert from 'node:assert/strict';import {createRequire}from'node:module';import{mkdir,writeFile}from'node:fs/promises';
import {createState,startMorning,SAVE_KEY}from'../src/state.js';import {scenes,isBlocked}from'../src/world.js';
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE});
const base=process.env.TEST_URL||'http://127.0.0.1:5190',out=process.env.TEST_OUTPUT_DIR||'docs/reviews/M1-W1';await mkdir(out,{recursive:true});
const results=[],errors=[],pass=s=>{results.push(s);console.log('PASS',s);};
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
const snap=()=>page.evaluate(async()=> (await import('/src/main.js')).getDebugSnapshot());
const motion=()=>page.evaluate(async()=> (await import('/src/main.js')).getDebugMovement());
async function until(read,predicate,timeout=12000){const end=Date.now()+timeout;while(Date.now()<end){const value=await read();if(predicate(value))return value;await page.waitForTimeout(10);}throw Error('Timed out awaiting '+predicate);}
const idle=()=>until(motion,m=>m.settled&&m.action==='idle');
async function go(x,y){await idle();const state=await snap(),q=[[state.player.x,state.player.y]],parents=new Map([[q[0].join(','),null]]);let end;
 for(let n=0;n<q.length;n++){const p=q[n];if(p[0]===x&&p[1]===y){end=p;break;}for(const [dx,dy]of [[0,-1],[1,0],[0,1],[-1,0]]){const a=p[0]+dx,b=p[1]+dy,k=`${a},${b}`;if(!parents.has(k)&&!isBlocked(state.scene,a,b,state)){parents.set(k,p);q.push([a,b]);}}}assert.ok(end,`No path ${state.scene} ${x},${y}`);
 const path=[];for(let p=end;p;p=parents.get(p.join(',')))path.unshift(p);
 for(let i=1;i<path.length;){const axis=path[i][0]!==path[i-1][0]?0:1,sign=Math.sign(path[i][axis]-path[i-1][axis]);let j=i;while(j+1<path.length&&path[j+1][1-axis]===path[j][1-axis]&&Math.sign(path[j+1][axis]-path[j][axis])===sign)j++;
  const target=path[j][axis],key=axis===0?(sign>0?'ArrowRight':'ArrowLeft'):(sign>0?'ArrowDown':'ArrowUp');await page.keyboard.down(key);try{await until(motion,m=>{const v=m.destination?.[axis===0?'x':'y']??m[axis===0?'tileX':'tileY'];return sign>0?v>=target:v<=target;});}finally{await page.keyboard.up(key);}await idle();assert.equal((await snap()).player[axis===0?'x':'y'],target);i=j+1;
 }
}
async function cross(key,scene){await page.keyboard.down(key);try{await until(snap,s=>s.scene===scene);}finally{await page.keyboard.up(key);}await idle();}
try{
 await page.goto(base);await page.waitForSelector('[data-action="new"]');
 const s=createState('World Review','boy','River');startMorning(s,true);s.scene='town';s.player={x:21,y:3,facing:'up'};await page.evaluate(({key,s})=>localStorage.setItem(key,JSON.stringify(s)),{key:SAVE_KEY,s});await page.reload();await page.locator('[data-action="continue"]').click();
 await cross('ArrowUp','forest');assert.equal((await snap()).debt,s.debt);pass('Walking north from Rootport enters Mossway without a menu');
 await go(9,22);await page.screenshot({path:`${out}/phone-meadow.png`});const grass=await page.evaluate(async()=> (await import('/src/render.js')).getRenderDebug());assert.equal(grass.activeGrass,true);pass('Real keyboard traversal reaches the required tall-grass meadow');
 await go(13,3);await cross('ArrowUp','liarsville');pass('Full wooded route reaches Liarsville through the meadow');
 await go(8,11);await page.locator('#a-button').click();await until(snap,s=>s.scene==='waterworks');await idle();await go(7,8);await page.locator('#a-button').click();await page.locator('#dialogue:not([hidden])').waitFor();assert.match(await page.locator('#dialogue-text').textContent(),/Spring, channel, mill, garden/);await page.locator('#a-button').click();await go(8,10);await page.locator('#a-button').click();await until(snap,s=>s.scene==='liarsville');await idle();pass('Waterworks entrance, history interaction and return doorway work');
 await go(14,28);await cross('ArrowDown','forest');await go(13,31);await cross('ArrowDown','town');pass('Complete return journey reaches Rootport and retains debt/story progress');
 const before=await snap();await page.locator('#start').click();await page.locator('[data-action="save"]').click();await page.reload();await page.locator('[data-action="continue"]').waitFor();const after=await snap();assert.deepEqual(after.player,before.player);assert.equal(after.worldVersion,2);assert.equal(after.debt,s.debt);pass('World-v2 save reload restores the completed cell and existing loan');
 for(const [scene,map]of Object.entries(scenes)){
 const [x,y]=map.safeSpawn;const data=await page.evaluate(async({scene,x,y})=>{const {createState,startMorning}=await import('/src/state.js'),{renderWorld,getRenderDebug}=await import('/src/render.js');const s=createState();startMorning(s);s.scene=scene;s.player={x,y,facing:'down'};const cv=document.createElement('canvas');cv.width=480;cv.height=320;renderWorld(cv,s,0,{x:x*16,y:y*16,facing:'down',pose:'idle',action:'idle'});return{png:cv.toDataURL().split(',')[1],debug:getRenderDebug()};},{scene,x,y});assert.deepEqual([data.debug.width,data.debug.height],[480,320]);await writeFile(`${out}/scene-${scene}.png`,Buffer.from(data.png,'base64'));
 }pass('All 14 scenes render in the native 480×320 framebuffer with no missing art');
 const anim=await page.evaluate(async()=>{const {createState,startMorning}=await import('/src/state.js'),{renderWorld}=await import('/src/render.js');const s=createState();startMorning(s);const cv=document.createElement('canvas');cv.width=480;cv.height=320;const c=cv.getContext('2d');
 const render=(scene,x,y,time,moving=false,actionTick=0)=>{s.scene=scene;s.player={x,y,facing:'down'};renderWorld(cv,s,time,{x:x*16,y:y*16,facing:'down',pose:'idle',action:'walk',moving,actionTick});return c.getImageData(0,0,480,320).data;};
 const changes=(a,b)=>{let n=0;for(let i=0;i<a.length;i+=4)if(a[i]!==b[i]||a[i+1]!==b[i+1]||a[i+2]!==b[i+2])n++;return n;};return{grass:changes(render('forest',9,22,0),render('forest',9,22,0,true,1)),water:changes(render('forest',19,12,0),render('forest',19,12,.3)),flowers:changes(render('yard',8,9,0),render('yard',8,9,.3)),wheel:changes(render('liarsville',27,13,0),render('liarsville',27,13,.2))};});assert.ok(Object.values(anim).every(n=>n>0),JSON.stringify(anim));pass('Actual rendered pixels change for contacted grass, water/falls, flowers and the waterwheel');
 const occlusion=await page.evaluate(async()=>{const {renderEnvironment}=await import('/src/environment-render.js'),{createState,startMorning}=await import('/src/state.js');const s=createState();startMorning(s);s.scene='forest';const cv=document.createElement('canvas');cv.width=480;cv.height=320;const c=cv.getContext('2d');const paint=c=>{c.fillStyle='#ff00ff';c.fillRect(-8,-32,16,32);};
 const count=y=>{renderEnvironment(c,s,0,{x:64,y:y*16,facing:'down',pose:'idle',action:'idle'},paint,e=>e.look);const bytes=c.getImageData(0,0,480,320).data;let red=0;for(let i=0;i<bytes.length;i+=4)if(bytes[i]===255&&bytes[i+1]===0&&bytes[i+2]===255)red++;return red;};return{behind:count(3),front:count(5)};});assert.ok(occlusion.behind<occlusion.front);assert.equal(occlusion.front,32*64);pass('Tree canopy covers an actor behind it; the actor covers the tree when in front');
 await page.locator('[data-action="continue"]').click();
 for(const [w,h]of [[320,568],[390,844],[844,390],[1280,900]]){await page.setViewportSize({width:w,height:h});await page.waitForTimeout(80);const g=await page.evaluate(()=>{const cv=document.getElementById('world'),r=cv.getBoundingClientRect();return{native:[cv.width,cv.height],ratio:r.width/r.height,screen:innerWidth,doc:document.documentElement.scrollWidth,controls:[...document.querySelectorAll('[data-dir],#a-button,#b-button')].map(b=>{const r=b.getBoundingClientRect();return[r.width,r.height];})};});assert.deepEqual(g.native,[480,320]);assert.ok(Math.abs(g.ratio-1.5)<.001);assert.ok(g.doc<=w);assert.ok(g.controls.every(([w,h])=>w>=44&&h>=44));await page.screenshot({path:`${out}/phone-${w}x${h}.png`});}pass('320/390 portrait, 844 landscape and desktop: full aspect, no overflow, 44px controls');
 const bad=await browser.newContext();await bad.route('**/assets/playable/overworld/master.png',r=>r.abort());const badPage=await bad.newPage();await badPage.goto(base);await badPage.waitForSelector('[data-action="reload"]');assert.equal(await badPage.evaluate(()=>localStorage.length),0);await bad.close();pass('Missing new atlas shows recovery UI without touching storage');
 assert.deepEqual(errors,[]);pass('Zero uncaught browser errors');await writeFile(`${out}/world-browser.json`,JSON.stringify({passed:results.length,results,animationPixelChanges:anim,occlusion,errors,limitations:['Chromium phone emulation; no physical iPhone/Safari test.','New map composition and animations await user feedback.']},null,2)+'\n');
}finally{await browser.close();}
