import{SAVE_KEY,MATERIALS,FEATURES,PRESETS,STAMPS,DIRS,clone,at,inside,newMap,newProject,demoProject,paint,flood,resizeMap,blocked,placeObject,objectAt,move,validate,importProject,exportProject,exportChat}from'./model.js';
import{MapRenderer}from'./render.js';
const $=id=>document.getElementById(id),renderer=new MapRenderer(),canvas=$('map'),ctx=canvas.getContext('2d'),viewport=$('viewport');
let project=demoProject(),undo=[],redo=[],mode='paint',brush='grass',stamp=null,raw=null,zoom=1,ox=40,oy=40,point={x:0,y:0},drag=null,settingsAdd=false,connectionPoint=null,testState=null,held=null,space=false,loaded=false,saveTimer,tileLimit=100,recovery=false;
const labels={grass:'Grass',path:'Dirt path',paving:'Concrete',soil:'Garden soil',water:'Water',cliff:'Mountain',fence:'Fence',tallgrass:'Tall grass',flowers:'Flowers',bridge:'Bridge',stairs:'Cliff stairs',cave:'Cliff opening','ledge-down':'Ledge ↓','ledge-up':'Ledge ↑','ledge-left':'Ledge ←','ledge-right':'Ledge →'};
const map=()=>project.maps.find(m=>m.id===project.active);
function status(s){$('status').textContent=s;}
function snapshot(){return JSON.stringify(project);}
function remember(){undo.push(snapshot());if(undo.length>80)undo.shift();redo=[];}
function save(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{if(recovery){$('saved').textContent='Unreadable draft retained. Download or import to recover.';return;}try{localStorage.setItem(SAVE_KEY,exportProject(project));$('saved').textContent='● Draft saved on this device';}catch{$('saved').textContent='Draft could not save. Download a project backup.';status('Storage is unavailable or full. Use Save project.');}},150);}
function refresh(){const m=map();canvas.width=m.w*32;canvas.height=m.h*32;renderer.draw(ctx,m,{grid:$('grid').checked,collision:$('collision').checked});canvas.style.transform=`translate(${ox}px,${oy}px) scale(${zoom})`;$('zoom-label').textContent=Math.round(zoom*100)+'%';$('map-dimensions').textContent=`${m.w} × ${m.h} cells · 32px`;$('undo').disabled=!undo.length;$('redo').disabled=!redo.length;$('world-name').textContent=project.name;updateCursor();}
function changed(message){refresh();save();if(message)status(message);}
function sync(){const select=$('maps');select.replaceChildren();for(const m of project.maps)select.add(new Option(m.name,m.id));select.value=project.active;$('notes').value=project.notes;refresh();}
function fit(){const m=map();zoom=Math.min(2,Math.max(.125,Math.min((viewport.clientWidth-48)/(m.w*32),(viewport.clientHeight-50)/(m.h*32))));ox=Math.round((viewport.clientWidth-m.w*32*zoom)/2);oy=Math.round((viewport.clientHeight-m.h*32*zoom)/2);refresh();}
function setZoom(z,x=viewport.clientWidth/2,y=viewport.clientHeight/2){z=Math.max(.125,Math.min(4,z));ox=x-(x-ox)*z/zoom;oy=y-(y-oy)*z/zoom;zoom=z;refresh();}
function setMode(value){if(['rectangle','fill'].includes(value))stamp=null;mode=value;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mode===mode));$('move-stamp').setAttribute('aria-pressed',mode==='move');$('selection-label').textContent=mode==='paint'||mode==='rectangle'||mode==='fill'?(stamp?STAMPS[stamp].name:raw?raw:labels[brush]):({spawn:'Set Hero start',warp:'Place passage',pan:'Pan canvas',erase:'Erase feature / stamp',move:'Pick up a stamp'}[mode]||mode);updateCursor();}
function selectBrush(value){brush=value;stamp=null;raw=null;if(!['paint','rectangle','fill'].includes(mode))setMode('paint');setMode(mode);document.querySelectorAll('[data-brush]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.brush===brush));document.querySelectorAll('[data-stamp],[data-tile]').forEach(b=>b.setAttribute('aria-pressed','false'));}
function selectStamp(type){stamp=type;raw=null;setMode('paint');document.querySelectorAll('[data-stamp]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.stamp===type));document.querySelectorAll('[data-brush],[data-tile]').forEach(b=>b.setAttribute('aria-pressed','false'));}
function locationOf(e){const r=viewport.getBoundingClientRect();return{x:Math.floor((e.clientX-r.left-ox)/zoom/32),y:Math.floor((e.clientY-r.top-oy)/zoom/32)};}
function updateCursor(){const valid=inside(map(),point.x,point.y),s=stamp?STAMPS[stamp]:{w:1,h:1};$('cursor').hidden=!valid||mode==='pan';Object.assign($('cursor').style,{left:ox+point.x*32*zoom+'px',top:oy+point.y*32*zoom+'px',width:s.w*32*zoom+'px',height:s.h*32*zoom+'px'});if(!valid)return;const m=map(),i=at(m,point.x,point.y),o=objectAt(m,point.x,point.y);$('coordinates').textContent=`Cell ${point.x}, ${point.y}`;$('cell-details').textContent=`${point.x}, ${point.y} · ${labels[m.terrain[i]]}${m.features[i]?' · '+labels[m.features[i]]:''}${o?' · '+o.name:''} · ${blocked(m,point.x,point.y)?'Blocked':'Walkable'}${m.raw[i]?' · exact tile '+m.raw[i].id:''}`;}
function apply(x,y){const m=map();if(!inside(m,x,y))return;if(mode==='erase'){paint(m,x,y,'erase');return;}if(raw){m.raw[at(m,x,y)]={id:raw,blocked:$('raw-block').checked};return;}paint(m,x,y,brush);}
function line(a,b){let x=a.x,y=a.y;const dx=Math.abs(b.x-x),sx=x<b.x?1:-1,dy=-Math.abs(b.y-y),sy=y<b.y?1:-1;let err=dx+dy;for(let guard=0;guard<512;guard++){apply(x,y);if(x===b.x&&y===b.y)break;const e=2*err;if(e>=dy){err+=dy;x+=sx;}if(e<=dx){err+=dx;y+=sy;}}}
function undoAction(forward=false){const from=forward?redo:undo,to=forward?undo:redo;if(!from.length)return;to.push(snapshot());project=JSON.parse(from.pop());sync();save();status(forward?'Redone.':'Undone.');}
function finishStroke(){if(!drag)return;if(drag.kind==='rectangle'){for(let y=Math.max(0,Math.min(drag.start.y,point.y));y<=Math.min(map().h-1,Math.max(drag.start.y,point.y));y++)for(let x=Math.max(0,Math.min(drag.start.x,point.x));x<=Math.min(map().w-1,Math.max(drag.start.x,point.x));x++)apply(x,y);}const edited=['paint','rectangle'].includes(drag.kind);drag=null;if(edited)changed('Map updated. Edges and collision recalculated.');}
viewport.addEventListener('pointerdown',e=>{if(!loaded||e.button>1)return;point=locationOf(e);viewport.focus();if(e.button===1||space||mode==='pan'){drag={kind:'pan',x:e.clientX,y:e.clientY,ox,oy};viewport.setPointerCapture(e.pointerId);return;}if(!inside(map(),point.x,point.y))return;const m=map();if(mode==='warp'){openConnections(point);return;}if(mode==='spawn'){if(blocked(m,point.x,point.y)){status('Hero needs a clear walking cell.');return;}remember();m.spawn={...point};changed('Hero start moved.');return;}if(mode==='move'){const o=objectAt(m,point.x,point.y);if(!o){status('Select a building or object to move.');return;}drag={kind:'object',object:o,start:{...point}};viewport.setPointerCapture(e.pointerId);return;}if(stamp&&mode==='paint'){remember();const result=placeObject(m,stamp,point.x,point.y);if(typeof result==='string'){undo.pop();status(result);refresh();}else changed(`${STAMPS[stamp].name} placed. Use Passage to link a door.`);return;}if(mode==='fill'&&!MATERIALS.includes(brush)||mode==='fill'&&(raw||stamp)){status('Fill works with the six ground materials.');return;}remember();if(mode==='fill'){flood(m,point.x,point.y,brush);changed('Connected ground filled.');return;}drag={kind:mode==='rectangle'?'rectangle':'paint',start:{...point},last:{...point}};viewport.setPointerCapture(e.pointerId);if(drag.kind==='paint'){apply(point.x,point.y);refresh();}});
viewport.addEventListener('pointermove',e=>{point=locationOf(e);if(drag?.kind==='pan'){ox=drag.ox+e.clientX-drag.x;oy=drag.oy+e.clientY-drag.y;refresh();}else if(drag?.kind==='paint'){line(drag.last,point);drag.last={...point};refresh();}else updateCursor();});
viewport.addEventListener('pointerup',e=>{if(drag?.kind==='object'){point=locationOf(e);const m=map(),o=drag.object,old={x:o.x,y:o.y};const x=o.x+point.x-drag.start.x,y=o.y+point.y-drag.start.y;remember();m.objects=m.objects.filter(a=>a!==o);const result=placeObject(m,o.type,x,y);if(typeof result==='string'){m.objects.push(o);undo.pop();status(result);}else{Object.assign(result,{id:o.id,name:o.name});const s=STAMPS[o.type];if(s.door)for(const w of m.warps)if(w.x===old.x+s.door[0]&&w.y===old.y+s.door[1]){w.x=x+s.door[0];w.y=y+s.door[1];}status('Stamp moved with its doorway.');}drag=null;changed();}else finishStroke();});
viewport.addEventListener('pointercancel',()=>{finishStroke();});viewport.addEventListener('lostpointercapture',()=>finishStroke());viewport.addEventListener('contextmenu',e=>e.preventDefault());viewport.addEventListener('wheel',e=>{e.preventDefault();if(e.ctrlKey||e.metaKey){const r=viewport.getBoundingClientRect();setZoom(zoom*Math.exp(-e.deltaY*.008),e.clientX-r.left,e.clientY-r.top);}else{ox-=e.deltaX;oy-=e.deltaY;refresh();}},{passive:false});
viewport.addEventListener('dragover',e=>{e.preventDefault();point=locationOf(e);updateCursor();});viewport.addEventListener('drop',e=>{e.preventDefault();const type=e.dataTransfer.getData('application/x-critz-stamp');if(!STAMPS[type])return;point=locationOf(e);remember();const result=placeObject(map(),type,point.x,point.y);if(typeof result==='string'){undo.pop();status(result);refresh();}else changed(STAMPS[type].name+' placed.');});
function buildPalette(){for(const kind of [...MATERIALS,...FEATURES.filter(f=>f)]){const b=document.createElement('button');b.className='brush';b.dataset.brush=kind;b.setAttribute('aria-pressed',kind==='grass');const c=document.createElement('canvas');c.width=c.height=32;const m=newMap();m.terrain.fill(kind==='cliff'?'cliff':'grass');if(MATERIALS.includes(kind))m.terrain[0]=kind;else m.features[0]=kind;c.getContext('2d').drawImage(renderer.cell(m,0,0),0,0);b.append(c,document.createTextNode(labels[kind]));b.onclick=()=>selectBrush(kind);$(MATERIALS.includes(kind)?'materials':'features').append(b);}for(const[type,s]of Object.entries(STAMPS)){const b=document.createElement('button'),c=document.createElement('canvas');renderer.thumbnail(type,c);b.dataset.stamp=type;b.draggable=true;b.title=`${s.name} · ${s.w} × ${s.h} cells`;b.append(c,document.createTextNode(s.name));b.onclick=()=>selectStamp(type);b.ondragstart=e=>{selectStamp(type);e.dataTransfer.setData('application/x-critz-stamp',type);};$('stamps').append(b);}renderTiles();}
function renderTiles(){const q=$('tile-search').value.toLowerCase(),sheet=$('sheet').value,allowed=sheet==='all'?null:new Set(renderer[sheet==='world'?'world':sheet==='contact'?'contact':'extra'].m.tiles.map(t=>t.id));const entries=[...renderer.tiles.values()].filter(t=>(!allowed||allowed.has(t.id))&&t.id.includes(q));$('tiles').replaceChildren();for(const t of entries.slice(0,tileLimit)){const b=document.createElement('button'),c=document.createElement('canvas');c.width=c.height=32;renderer.drawTile(c.getContext('2d'),t.id,0,0);b.append(c);b.dataset.tile=t.id;b.title=t.id;b.setAttribute('aria-label',t.id);b.setAttribute('aria-pressed',raw===t.id);b.onclick=()=>{raw=t.id;stamp=null;setMode('paint');$('raw-block').checked=t.blocked??t.layer!=='ground';renderTiles();document.querySelectorAll('[data-brush],[data-stamp]').forEach(b=>b.setAttribute('aria-pressed','false'));status(t.id+' selected. Set collision before painting.');};$('tiles').append(b);}$('tile-count').textContent=`${Math.min(tileLimit,entries.length)} of ${entries.length} tiles`;$('more-tiles').hidden=entries.length<=tileLimit;}
$('project-panel').onclick=()=>{document.body.classList.toggle('show-project');};$('close-project').onclick=()=>document.body.classList.remove('show-project');
$('tile-search').oninput=$('sheet').onchange=()=>{tileLimit=100;renderTiles();};$('more-tiles').onclick=()=>{tileLimit+=100;renderTiles();};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(a=>a.setAttribute('aria-selected',a===b));for(const tab of['terrain','stamps','tiles'])$(tab+'-panel').hidden=tab!==b.dataset.tab;});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('move-stamp').onclick=()=>{stamp=null;raw=null;setMode('move');};$('undo').onclick=()=>undoAction();$('redo').onclick=()=>undoAction(true);$('grid').onchange=$('collision').onchange=refresh;$('zoom-in').onclick=()=>setZoom(zoom*1.25);$('zoom-out').onclick=()=>setZoom(zoom/1.25);$('fit').onclick=fit;$('maps').onchange=()=>{project.active=$('maps').value;fit();save();};
function mapSettings(add=false){if(add&&project.maps.length>=16){status('Project limit: 16 maps.');return;}settingsAdd=add;$('settings-title').textContent=add?'Add another map':'Map settings';$('map-name').value=add?'New area':map().name;$('width').value=add?20:map().w;$('height').value=add?20:map().h;$('preset').value='custom';$('settings-error').textContent='';$('settings-dialog').showModal();}
$('preset').add(new Option('Custom size','custom'));PRESETS.forEach(([name,w,h],i)=>$('preset').add(new Option(`${name} · ${w} × ${h}`,String(i))));$('preset').onchange=()=>{if($('preset').value==='custom')return;const[,w,h]=PRESETS[+$('preset').value];$('width').value=w;$('height').value=h;};$('map-settings').onclick=()=>mapSettings();$('add-map').onclick=()=>mapSettings(true);$('apply-settings').onclick=()=>{try{const w=Number($('width').value),h=Number($('height').value),name=$('map-name').value.trim()||'Untitled map';const candidate=newMap('map-'+Date.now(),name,w,h);if(project.maps.reduce((n,m)=>n+m.w*m.h,0)+(settingsAdd?0:-map().w*map().h)+w*h>65536)throw Error('Project limit: 65,536 cells.');remember();if(settingsAdd){project.maps.push(candidate);project.active=candidate.id;}else{resizeMap(map(),w,h);map().name=name;}sync();fit();save();$('settings-dialog').close();status('Map ready.');}catch(e){$('settings-error').textContent=e.message;}};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('download').onclick=()=>download(new Blob([exportProject(project)],{type:'application/json'}),'critz-world.json');
$('copy').onclick=async()=>{const text=exportChat(project);$('data-title').textContent='Copy your world';$('data-description').textContent='Paste this complete text into chat. It includes terrain, buildings, collision rules, notes and map links.';$('data-text').value=text;$('data-text').readOnly=true;$('apply-import').hidden=$('open-file').hidden=true;$('data-error').textContent='';$('data-dialog').showModal();$('data-text').select();try{await navigator.clipboard.writeText(text);$('data-error').textContent='Copied. Paste it into chat when you’re ready.';}catch{$('data-error').textContent='Copy the selected text, or download Save project.';}};
$('import').onclick=()=>{$('data-title').textContent='Open a map project';$('data-description').textContent='Paste exported map JSON or choose a project file. Import replaces this workspace; Undo restores it.';$('data-text').value='';$('data-text').readOnly=false;$('apply-import').hidden=$('open-file').hidden=false;$('data-error').textContent='';$('data-dialog').showModal();};$('open-file').onclick=()=>$('file-input').click();$('file-input').onchange=async()=>{const f=$('file-input').files[0];if(!f)return;if(f.size>6000000){$('data-error').textContent='File exceeds 6 MB.';return;}$('data-text').value=await f.text();$('file-input').value='';};$('apply-import').onclick=()=>{try{const imported=importProject($('data-text').value,new Set(renderer.tiles.keys()));remember();project=imported;recovery=false;sync();fit();save();$('data-dialog').close();status('Project imported. Undo restores the previous world.');}catch(e){$('data-error').textContent=e.message;}};
$('export-png').onclick=()=>{const m=map(),c=document.createElement('canvas');c.width=m.w*32;c.height=m.h*32;renderer.draw(c.getContext('2d'),m,{markers:false});c.toBlob(b=>download(b,'critz-map.png'));};$('new-project').onclick=()=>{remember();project=newProject();recovery=false;sync();fit();save();status('Blank world started. Undo restores your previous project.');};$('notes').onchange=()=>{remember();project.notes=$('notes').value.slice(0,10000);save();};
function openConnections(p=null){connectionPoint=p?{...p}:null;const m=map();$('target-map').replaceChildren();for(const t of project.maps)$('target-map').add(new Option(t.name,t.id));$('target-map').value=project.maps.find(t=>t.id!==m.id)?.id||m.id;const dest=project.maps.find(t=>t.id===$('target-map').value);$('target-x').value=dest.spawn.x;$('target-y').value=dest.spawn.y;$('edge-fields').hidden=!!p;$('warp-fields').hidden=!p;$('connection-help').textContent=p?`Passage at cell ${p.x}, ${p.y}. Walking onto this cell in the chosen direction goes to the arrival cell. Add a separate return passage if needed.`:'Connect the current map’s outer edge to another map. An offset of 0 aligns their top or left boundaries.';$('connection-error').textContent='';$('existing-connections').replaceChildren();const list=p?m.warps:m.connections;list.forEach((c,i)=>{const row=document.createElement('div');row.className='connection-row';row.append(document.createTextNode(`${c.direction} → ${project.maps.find(m=>m.id===c.target)?.name||c.target}${p?' at '+c.x+','+c.y:' (offset '+c.offset+')'}`));const b=document.createElement('button');b.textContent='Remove';b.onclick=()=>{remember();list.splice(i,1);if(!p){const target=project.maps.find(t=>t.id===c.target),opposite={up:'down',down:'up',left:'right',right:'left'}[c.direction];if(target)target.connections=target.connections.filter(a=>!(a.direction===opposite&&a.target===m.id));}changed('Connection removed.');$('connection-dialog').close();};row.append(b);$('existing-connections').append(row);});$('connection-dialog').showModal();}
$('connections').onclick=()=>openConnections();$('target-map').onchange=()=>{const t=project.maps.find(m=>m.id===$('target-map').value);$('target-x').value=t.spawn.x;$('target-y').value=t.spawn.y;};$('save-connection').onclick=()=>{const m=map(),target=project.maps.find(m=>m.id===$('target-map').value),direction=$('direction').value;if(connectionPoint){const tx=+$('target-x').value,ty=+$('target-y').value;if(blocked(m,connectionPoint.x,connectionPoint.y)||blocked(target,tx,ty)){$('connection-error').textContent='Both the passage and arrival need clear walking cells.';return;}remember();m.warps=m.warps.filter(w=>w.x!==connectionPoint.x||w.y!==connectionPoint.y);m.warps.push({...connectionPoint,target:target.id,tx,ty,direction});}else{const offset=+$('offset').value;if(target===m){$('connection-error').textContent='Choose a different map for an edge connection.';return;}if(!Number.isInteger(offset)||Math.abs(offset)>128){$('connection-error').textContent='Use an integer offset between −128 and 128.';return;}const opposite={up:'down',down:'up',left:'right',right:'left'}[direction];if(m.connections.some(c=>c.direction===direction)||target.connections.some(c=>c.direction===opposite)){$('connection-error').textContent='An edge is already connected. Remove its existing link first.';return;}remember();m.connections.push({direction,target:target.id,offset});target.connections.push({direction:opposite,target:m.id,offset:-offset});}changed('Maps connected. Try walking through in Test.');$('connection-dialog').close();};
$('validate').onclick=()=>{const issues=validate(project);$('check-results').replaceChildren();for(const s of issues.length?issues:['No blocked starts, blocked door approaches or broken passage destinations found. Test with Hero to check the paths you intend.']){const p=document.createElement('p');p.textContent=s;$('check-results').append(p);}$('check-dialog').showModal();};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
const play=$('play'),pc=play.getContext('2d');let lastTick=0;
function startTest(){const m=map();if(blocked(m,m.spawn.x,m.spawn.y)){status('Move Hero start to a clear walking cell before testing.');$('validate').click();return;}testState={project:clone(project),map:m.id,player:{...m.spawn,facing:'down'},animation:null};held=null;lastTick=performance.now();$('test-dialog').showModal();play.focus();drawTest(performance.now());}
function drawTest(now){if(!testState)return;const t=testState,m=t.project.maps.find(m=>m.id===t.map),p={...t.player};if(t.animation){const a=t.animation,u=Math.min(1,(now-a.start)/a.duration);p.px=a.x*32+(p.x-a.x)*32*u;p.py=a.y*32+(p.y-a.y)*32*u;p.moving=true;p.jump=a.jump;p.progress=u;if(u===1)t.animation=null;}pc.imageSmoothingEnabled=false;pc.fillStyle='#253d34';pc.fillRect(0,0,480,320);const camX=Math.round((p.px??p.x*32)+16-240),camY=Math.round((p.py??p.y*32)+32-176);pc.save();pc.translate(-camX,-camY);renderer.draw(pc,m,{player:p,time:now,markers:false,bounds:{x:camX,y:camY,w:480,h:320}});pc.restore();$('test-map-name').textContent=m.name;}
function stepTest(dir,now){if(!testState||testState.animation)return;const t=testState,old={...t.player},dest=move(t.project,t.map,t.player,dir);t.player.facing=dir;if(dest){t.player=dest;t.map=dest.map;if(!dest.transition)t.animation={x:old.x,y:old.y,start:now,duration:dest.jump?360:268,jump:dest.jump};$('test-status').textContent=dest.transition?'Entered '+t.project.maps.find(m=>m.id===t.map).name:dest.jump?'One-way ledge · landed on clear ground.':'Arrow keys / WASD to walk. Push boulders. Follow passages.';}else $('test-status').textContent='Blocked here. Water banks, walls and fences are solid.';}
function frame(now){if(testState){if(held&&!testState.animation&&now-lastTick>70){stepTest(held,now);lastTick=now;}drawTest(now);}requestAnimationFrame(frame);}
$('test').onclick=startTest;$('exit-test').onclick=()=>$('test-dialog').close();$('test-dialog').addEventListener('close',()=>{testState=null;held=null;status('Back to your draft. Test movements and pushed boulders were discarded.');});document.querySelectorAll('[data-dir]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();held=b.dataset.dir;b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>held=null;});
const keys={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',s:'down',a:'left',d:'right'};
window.addEventListener('keydown',e=>{if(testState){if(keys[e.key]){e.preventDefault();held=keys[e.key];}return;}if(e.target.matches('input,textarea,select')||document.querySelector('dialog[open]'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undoAction(e.shiftKey);return;}if(e.code==='Space'){space=true;e.preventDefault();}if(e.key==='Escape'){finishStroke();setMode('paint');}if(document.activeElement===viewport){if(keys[e.key]){e.preventDefault();const[dx,dy]=DIRS[keys[e.key]];point.x=Math.max(0,Math.min(map().w-1,point.x+dx));point.y=Math.max(0,Math.min(map().h-1,point.y+dy));updateCursor();}if(e.key==='Enter'){e.preventDefault();if(mode==='warp'){openConnections(point);return;}remember();if(mode==='spawn'){if(!blocked(map(),point.x,point.y))map().spawn={...point};}else if(stamp){const result=placeObject(map(),stamp,point.x,point.y);if(typeof result==='string')status(result);}else if(mode==='fill')flood(map(),point.x,point.y,brush);else apply(point.x,point.y);changed();}}});window.addEventListener('keyup',e=>{if(e.code==='Space')space=false;if(keys[e.key]===held)held=null;});window.addEventListener('blur',()=>{space=false;held=null;finishStroke();});document.addEventListener('visibilitychange',()=>{held=null;});new ResizeObserver(()=>{if(loaded)refresh();}).observe(viewport);
// Read-only inspection hook for isolated browser QA; game state is never imported.
export function inspect(){return{project:clone(project),mode,brush,stamp,raw,zoom,ox,oy,test:testState?clone({map:testState.map,player:testState.player}):null};}
try{await renderer.load();try{const saved=localStorage.getItem(SAVE_KEY);if(saved){project=importProject(saved,new Set(renderer.tiles.keys()));$('saved').textContent='● Saved draft restored';}else $('saved').textContent='Example clearing · make it yours';}catch(e){recovery=true;$('saved').textContent='Unreadable draft retained. Import a backup to recover.';status(e.message);}buildPalette();sync();loaded=true;fit();status(recovery?'Your stored draft was not overwritten. Import a backup or start a new blank world.':'Ready. Paint terrain, drop a building, then take Hero for a walk.');requestAnimationFrame(frame);}catch(e){status('Editor could not load: '+e.message);$('saved').textContent='Reload to retry loading the tiles.';console.error(e);}
