import {drawContactSprite} from '../src/contact-rules.js';
import {loadContactArt,drawContactArt,contactSheet} from '../src/contact-art.js';
import{cellRecipe,STAMPS,blocked,at,maskAt}from'./model.js';
export class MapRenderer{
 constructor(){this.tiles=new Map();this.cache=new Map();}
 async load(){await loadContactArt();const load=async path=>{const m=await(await fetch(path)).json(),img=new Image();img.src=new URL(m.image,new URL(path,location.href)).href;await img.decode();return{m,img};};const [world,extra,hero]=await Promise.all([load('../assets/playable/overworld/master.json'),load('../assets/review/map-editor/master.json'),load('../assets/playable/living/atlas.json')]);this.world=world;this.extra=extra;this.hero=hero;this.contact=contactSheet();for(const atlas of[world,extra,contactSheet()])for(const t of atlas.m.tiles)this.tiles.set(t.id,{...t,img:atlas.img});this.heroFrames=new Map(hero.m.assets.map(t=>[t.id,t]));}
 drawTile(c,id,x,y,w=32,h=32){const t=this.tiles.get(id);if(!t)throw Error('Missing editor tile '+id);c.drawImage(t.img,t.x,t.y,32,32,x,y,w,h);}
 cell(m,x,y){const r=cellRecipe(m,x,y),key=JSON.stringify(r);if(this.cache.has(key))return this.cache.get(key);if(this.cache.size>8192)this.cache.clear();const c=document.createElement('canvas');c.width=c.height=32;const ctx=c.getContext('2d');r.quadrants.forEach((id,q)=>{const t=this.tiles.get(id);if(!t)throw Error('Missing terrain '+id);const a=q%2*16,b=Math.floor(q/2)*16;ctx.drawImage(t.img,t.x+a,t.y+b,16,16,a,b,16,16);});if(r.feature&&!r.feature.startsWith('fence.')&&!r.feature.startsWith('ledge-')){const id=r.feature.startsWith('fence.')?r.feature:{tallgrass:'grass.living.0',flowers:'flowers.2',bridge:'bridge.horizontal.center'}[r.feature]||'feature.'+r.feature;this.drawTile(ctx,id,0,0);}if(r.raw)this.drawTile(ctx,r.raw.id,0,0);this.cache.set(key,c);return c;}
 stampRows(o){const s=STAMPS[o.type];return s.assembly?this.world.m.assemblies[s.assembly]:[[s.tile]];}
 drawObject(c,o,m=null){drawContactArt(c,`stamp:${o.type}`,o.x*32,o.y*32);}
 drawHero(c,p,time=0){const facing={down:0,up:4,left:8,right:12}[p.facing]||0,phase=p.moving?[0,1,2,1][Math.floor(time/134)%4]:1,t=this.heroFrames.get(`hero-boy.${facing+phase}`);const[x,y,w,h]=t.rect;const hop=p.jump?Math.round(Math.sin((p.progress||0)*Math.PI)*12):0;c.drawImage(this.hero.img,x,y,w,h,Math.round(p.px??p.x*32),Math.round((p.py??p.y*32)-32-hop),w,h);}
 draw(c,m,{grid=false,collision=false,player=null,time=0,markers=true,bounds=null}={}){c.imageSmoothingEnabled=false;c.fillStyle='#253d34';c.fillRect(0,0,m.w*32,m.h*32);const x0=bounds?Math.max(0,Math.floor(bounds.x/32)):0,y0=bounds?Math.max(0,Math.floor(bounds.y/32)):0,x1=bounds?Math.min(m.w,Math.ceil((bounds.x+bounds.w)/32)):m.w,y1=bounds?Math.min(m.h,Math.ceil((bounds.y+bounds.h)/32)):m.h;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){const kind=m.terrain[y*m.w+x];if(m.raw[y*m.w+x]?.blocked||!m.raw[y*m.w+x]&&['water','cliff'].includes(kind))this.drawTile(c,'meadow.grass.0',x*32,y*32);else c.drawImage(this.cell(m,x,y),x*32,y*32);}
 for(let y=Math.max(0,y0-1);y<y1;y++)for(let x=x0;x<x1;x++){const kind=m.terrain[y*m.w+x],f=m.features[y*m.w+x],raw=m.raw[y*m.w+x];if(raw?.blocked){const t=this.tiles.get(raw.id);drawContactSprite(c,t.img,[t.x,t.y,32,32],[x*32,y*32,32,32],[x,y,1,1],{groundBand:t.contact?.groundRows||0});continue;}if(raw)continue;if(['water','cliff'].includes(kind)&&!['bridge','stairs','cave'].includes(f))drawContactArt(c,`terrain:${kind}:${maskAt(m,x,y,(a,b)=>m.terrain[at(m,a,b)]===kind)}`,x*32,y*32);if(f.startsWith('ledge-'))drawContactArt(c,`feature:${f}`,x*32,y*32);else if(f==='fence')drawContactArt(c,`catalog:fence.${maskAt(m,x,y,(a,b)=>m.features[at(m,a,b)]==='fence')&15}`,x*32,y*32);else if(['bridge','stairs','cave'].includes(f))c.drawImage(this.cell(m,x,y),x*32,y*32);}const objects=m.objects.map(o=>({o,depth:o.y+STAMPS[o.type].h}));if(player)objects.push({player,depth:(player.py??player.y*32)/32+1});objects.sort((a,b)=>a.depth-b.depth);for(const d of objects)if(d.player)this.drawHero(c,d.player,time);else this.drawObject(c,d.o,m);if(collision){c.fillStyle='#d84b6268';for(let y=0;y<m.h;y++)for(let x=0;x<m.w;x++)if(blocked(m,x,y))c.fillRect(x*32+1,y*32+1,30,30);}if(grid){c.strokeStyle='#17372b38';c.lineWidth=1;c.beginPath();for(let x=0;x<=m.w;x++){c.moveTo(x*32+.5,0);c.lineTo(x*32+.5,m.h*32);}for(let y=0;y<=m.h;y++){c.moveTo(0,y*32+.5);c.lineTo(m.w*32,y*32+.5);}c.stroke();}if(markers){this.marker(c,m.spawn.x,m.spawn.y,'H','#fcdf92');for(const w of m.warps)this.marker(c,w.x,w.y,'↗','#aadefa');}}
 marker(c,x,y,text,color){c.fillStyle=color;c.fillRect(x*32+7,y*32+7,18,18);c.fillStyle='#233c35';c.font='bold 14px sans-serif';c.textAlign='center';c.fillText(text,x*32+16,y*32+21);}
 thumbnail(type,canvas){const s=STAMPS[type];canvas.width=s.w*32;canvas.height=(s.h+1)*32;this.drawObject(canvas.getContext('2d'),{type,x:0,y:0});}
}
