import {drawFormatTile} from './coast-review-art.js';
import {compileCoastalField,sliverCells} from '../src/coastal-format.js';
import {createCoastalDrawing,coastalFieldPath,drawCoastalBoundary} from '../src/coastal-drawing.js';
import {CONTACT_RULE} from '../src/contact-rules.js';
import {drawContactSprite} from '../src/contact-rules.js';
import {coastalMap,coastalRocks,coastalWalkable} from '../src/coastal-layout.js';
import {footstepRipples,ripplePose,RIPPLE_SECONDS} from '../src/water-surfaces.js';
import {createMotion,getMotionView,advanceMotion,createMotionClock,advanceMotionClock,resetMotionClock} from '../src/movement.js';
import {initWorldArt,character} from '../src/render.js';import {drawEnvironmentTile} from '../src/environment-render.js';
import {createState} from '../src/state.js';import {ensureDayClock,advanceDayClock,endDay,paintClock,displayedMinute} from '../src/day-clock.js';import {applyLighting} from '../src/lighting.js';
import {loadCloudArt,cloudsVisible,cloudSun} from '../src/water-clouds.js';import {loadWaterArt,createTurtle,updateTurtle,turtleOffset,fishPose} from '../src/water-wildlife.js';import {readRenderSettings,saveRenderSettings} from '../src/render-settings.js';
const $=id=>document.getElementById(id),canvas=$('coast'),c=canvas.getContext('2d'),state=(new URLSearchParams(location.search).get('game')==='1'&&window.parent.critzCoast?.state)||createState('Hero','boy','River');state.stage='morning';ensureDayClock(state);
let boundary,groundTile;
let scene='showcase',ground='grass',identity='fresh',map,rocks,turtles,player,motion,hero;const clock=createMotionClock(),down=new Set(),settings=readRenderSettings(localStorage);
let detail=matchMedia('(max-width:600px)').matches;function setView(){canvas.width=detail?384:640;canvas.height=detail?320:480;$('view').textContent=`View · ${detail?'Detail':'Overview'}`;}setView();$('view').onclick=()=>{detail=!detail;setView();};
let time=0,last=performance.now(),ready=false,paused=false,calm=matchMedia('(prefers-reduced-motion: reduce)').matches,speed=1,weather='sunny',steps=0,ripples=[],reflections=0,art,waterArt,wildlife,cloudArt;
const description={showcase:'Deep-only freshwater touches raised grass on the left. Deep ocean touches sand on the right. Shallow freshwater puddle above.',beach:'A deep-only moving ocean meets new sand tiles. Rounded wash fronts advance onto the beach and recede; sand has no cliff.', 'deep-land':'A deep-only still-water pool meets raised land directly. The exposed shore has a cap, rock face, cracks and dark toe.',still:'Shallow Still Water wraps deep Still Water. Curved water-color edges show the change in depth, with no stone bank. Walk the shallow ring.',moving:'Shallow Moving Water wraps deep Moving Water. Curved depth edges; no stone bank and no footstep rings.',puddles:'Left: Shallow Still Water, with footstep rings. Right: Shallow Moving Water, without rings. Both reflect Hero when freshwater.'};
function place(x,y){player={x,y,facing:'down'};motion=createMotion(player);resetMotionClock(clock);down.clear();sync();}
function rebuild(){groundTile=document.createElement('canvas');groundTile.width=groundTile.height=32;drawFormatTile(groundTile.getContext('2d'),{kind:'surface',mask:55,a:'sand',b:ground,f:0,family:'ground'});map=coastalMap(scene,ground,identity);if(sliverCells(map.cells).length)throw Error('Unsupported one-cell water strip');boundary=createCoastalDrawing(compileCoastalField(map.cells,640,480),(x,y)=>{const s=nearestSurface(x,y);return{ground:map.land(Math.floor(x/32),Math.floor((y-16)/32)),shallow:s?.shallow,moving:s?.moving};});rocks=coastalRocks(map);turtles=rocks.slice(0,2).map(r=>createTurtle(r.x*32+16,r.y*32+16));ripples=[];place(2,3);$('description').textContent=description[scene];$('visit').disabled=scene==='beach';$('message').textContent=description[scene];}
function sync(){const v=getMotionView(motion);hero={x:v.x*2+16,y:v.y*2+32,facing:v.facing,pose:calm?'idle':v.pose};}
function nearestSurface(x,y){const xx=Math.floor(x/32),yy=Math.floor((y-16)/32);let s=map.get(xx,yy);if(s)return s;let best=Infinity;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const n=map.get(xx+dx,yy+dy),d=(x-((xx+dx)*32+16))**2+(y-((yy+dy)*32+32))**2;if(n&&d<best){s=n;best=d;}}return s;}
const paths=new Map();function mask(cells,depth=false){const key=depth+':'+cells.map(a=>`${a.x},${a.y}`).join(';');if(!paths.has(key))paths.set(key,coastalFieldPath(compileCoastalField(cells,640,480,depth?{sideInset:5,verticalInset:5}:{})));return paths.get(key);}
async function load(path){const url=new URL(path,import.meta.url),m=await(await fetch(url)).json(),im=new Image();im.src=new URL(m.image,url);await im.decode();const entries=new Map(m.assets.map(a=>[a.id,a]));return {manifest:m,draw(ctx,id,x,y){const a=entries.get(id);if(!a)throw Error('Missing coastal tile '+id);ctx.drawImage(im,a.x,a.y,a.w,a.h,Math.round(x),Math.round(y),a.w,a.h);}};}
let rockSprites=[];const bedSprite=document.createElement('canvas');bedSprite.width=32;bedSprite.height=64;const bc=bedSprite.getContext('2d');bc.fillStyle='#51433a';bc.fillRect(8,0,16,60);bc.fillStyle='#c89969';bc.fillRect(10,2,12,56);bc.fillStyle='#eee1b5';bc.fillRect(11,4,10,12);bc.fillStyle='#609c9f';bc.fillRect(10,19,12,35);bc.fillStyle='#8ac5b8';bc.fillRect(11,20,10,7);
const actor=document.createElement('canvas');actor.width=32;actor.height=64;const ac=actor.getContext('2d');const shadows=document.createElement('canvas');shadows.width=640;shadows.height=480;const sc=shadows.getContext('2d');
function render(){c.imageSmoothingEnabled=false;c.clearRect(0,0,canvas.width,canvas.height);c.save();if(detail)c.translate(-Math.max(0,Math.min(256,Math.round(hero.x)-192)),-Math.max(0,Math.min(160,Math.round(hero.y)-160)));const f=calm?0:Math.floor(time/.1)%32,all=map.cells,wet=boundary.path,minute=displayedMinute(state.dayClock);
 for(let y=0;y<15;y++)for(let x=0;x<20;x++){const g=map.land(x,y);if(g==='sand'){art.draw(c,`sand.${(x+y)%4}`,x*32,y*32);if(scene==='showcase'&&x===10&&!map.get(x,y))c.drawImage(groundTile,x*32,y*32);}else drawEnvironmentTile(c,({grass:'meadow.grass.0',path:'meadow.path.255.0',soil:'soil.255',paving:'paving.255',cliff:'ground.soil'})[g],x*32,y*32);}
 c.save();c.clip(boundary.path);for(let y=0;y<15;y++)for(let x=0;x<20;x++){const s=nearestSurface(x*32+16,y*32+32);if(s){const type=(scene==='still'||scene==='moving')&&!s.shallow?'shallow-'+s.type:s.type;waterArt.draw(c,`${s.identity}.${type}.${f}`,x*32,y*32+16);}}if(scene==='still'||scene==='moving'){c.save();c.clip(mask(all.filter(a=>!a.surface.shallow),true));for(const a of all.filter(a=>!a.surface.shallow))waterArt.draw(c,`${a.surface.identity}.${a.surface.type}.${f}`,a.x*32,a.y*32+16);c.restore();}c.restore();
 c.save();c.clip(wet);if(minute>=1260){for(let i=0;i<44;i++){c.fillStyle=i%3?'#acd5da':'#e5eacb';c.globalAlpha=calm?.4:.35+Math.sin(time*1.7+i)*.13;const x=(i*83+31)%640,y=(i*57+126)%480;c.fillRect(x,y,2,2);if(i%6===0){c.fillRect(x-2,y+1,6,1);c.fillRect(x+1,y-2,1,6);}}}else if(cloudsVisible(minute,weather)){c.globalAlpha=.52;for(let i=0;i<4;i++){const x=Math.round(((480+i*181-(calm?0:time*9))%840+840)%840)-96;cloudArt.draw(c,i%3,minute,x,140+i*66);}}c.restore();
 ac.clearRect(0,0,32,64);character(ac,16,64,{gender:state.gender,facing:hero.facing,pose:hero.pose});const pixels=ac.getImageData(0,0,32,64);for(let i=0;i<pixels.data.length;i+=4){pixels.data[i]=Math.round(pixels.data[i]*.68+147*.32);pixels.data[i+1]=Math.round(pixels.data[i+1]*.68+200*.32);pixels.data[i+2]=Math.round(pixels.data[i+2]*.68+213*.32);}ac.putImageData(pixels,0,0);reflections=0;
 for(const moving of [false,true]){const cells=all.filter(a=>a.surface.reflective&&a.surface.moving===moving);c.save();c.clip(mask(cells));c.globalAlpha=.52;for(let y=0;y<64;y++){const drift=moving&&!calm?Math.round(Math.sin(time*2+y/7)):0;c.drawImage(actor,0,63-y,32,1,Math.round(hero.x)-16+drift,Math.round(hero.y)-4+y,32,1);}c.restore();if(cells.some(a=>hero.x>=a.x*32&&hero.x<(a.x+1)*32&&hero.y<(a.y+1)*32&&hero.y+64>a.y*32))reflections++;}
 // Derive the complete bank/wash once from the continuous shared footprint.
 drawCoastalBoundary(c,boundary,f);
 c.save();c.clip(mask(all.filter(a=>footstepRipples(a.surface))));for(const r of ripples){const p=ripplePose(time-r.time);if(!p)continue;c.fillStyle='#d0e7d9';c.globalAlpha=p.alpha;for(let y=-p.ry;y<=p.ry;y++){const w=Math.round(p.rx*Math.sqrt(Math.max(0,1-y*y/p.ry**2)));c.fillRect(r.x-w,r.y+y,1,1);c.fillRect(r.x+w,r.y+y,1,1);}}c.restore();
 // Shadow mask is independent of rock material shading and water animation.
 sc.clearRect(0,0,640,480);if(settings.shadows){for(const r of rocks)art.draw(sc,`rock-shadow.${r.variant}`,r.x*32,r.y*32+16);sc.fillStyle='#183947';sc.fillRect(Math.round(hero.x)-8,Math.round(hero.y)-2,16,3);c.save();c.globalAlpha=.65;c.drawImage(shadows,0,0);c.restore();}
 for(const r of rocks){const rockImage=rockSprites[r.variant];drawContactSprite(c,rockImage,[0,0,32,32],[r.x*32,r.y*32,32,32],[r.x,r.y,1,1]);}
 for(const t of turtles){const v=calm?{x:0,y:0,visible:t.phase!=='submerged'}:turtleOffset(t);if(v.visible)wildlife(c,`turtle.${calm?0:Math.floor(t.age*8)%4}`,t.x-16+v.x,t.y-19+v.y+18);if(t.phase==='submerged'&&t.age<.8&&!calm)wildlife(c,`splash.${Math.min(3,Math.floor(t.age*5))}`,t.x+4,t.y+22);}
 const fishCells=all.filter(a=>a.mask===255&&a.depthMask===255&&!a.surface.shallow);for(let i=0;i<Math.min(3,fishCells.length);i++){const a=fishCells[Math.floor(fishCells.length*(i+.5)/3)],p=fishPose(time,i,minute,calm);if(p){const x=a.x*32+p.x,y=a.y*32+16+p.y;wildlife(c,`fish.${p.frame}`,x,y);if(p.splash)wildlife(c,'splash.2',x,a.y*32+16);}}
 drawContactSprite(c,bedSprite,[0,0,32,64],[32,32,32,64],[1,1,1,2]);
 character(c,Math.round(hero.x),Math.round(hero.y),{gender:state.gender,facing:hero.facing,pose:hero.pose});c.restore();applyLighting(c,state);paintClock($('day-clock'),state,paused);if(document.activeElement!==$('time'))$('time').value=minute;
}
function sleep(forced=false){if(!forced&&Math.hypot(hero.x-48,hero.y-80)>60){$('message').textContent='Visit the bed, then press A to sleep.';return;}endDay(state);speed=1;$('speed').textContent='Speed · 1×';place(1,3);$('message').textContent=forced?'You passed out at 2:00am and woke at 6:00am, with no fee.':'Good morning! You woke at 6:00am.';}
$('scene').onchange=e=>{scene=e.target.value;rebuild();};$('ground').onchange=e=>{ground=e.target.value;rebuild();};$('identity').onclick=()=>{identity=identity==='fresh'?'ocean':'fresh';$('identity').textContent=`Freshwater reflections · ${identity==='fresh'?'On':'Off'}`;rebuild();};$('weather').onchange=e=>weather=e.target.value;
$('visit').onclick=()=>{const pos={showcase:[14,1],still:[5,7],moving:[5,7],puddles:[4,6],'deep-land':[8,3]};if(pos[scene])place(...pos[scene]);};$('bed').onclick=()=>place(1,3);$('sleep').onclick=()=>sleep();$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Resume':'Pause';};$('speed').onclick=()=>{speed=speed===1?60:1;$('speed').textContent=`Speed · ${speed}×`;};
function setTime(m){m=Number(m);state.dayClock.minute=Math.floor(m/10)*10;state.dayClock.remainder=(m%10)*1.4;}
for(const b of document.querySelectorAll('[data-minute]'))b.onclick=()=>setTime(b.dataset.minute);$('time').oninput=e=>setTime(e.target.value);$('calm').onclick=()=>{calm=!calm;$('calm').textContent=`Calm · ${calm?'On':'Off'}`;};function showShadows(){$('shadows').textContent=`Shadows · ${settings.shadows?'On':'Off'}`;}showShadows();$('shadows').onclick=()=>{settings.shadows=!settings.shadows;saveRenderSettings(localStorage,settings);showShadows();};
const keys={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'};addEventListener('keydown',e=>{if(keys[e.key]&&!['INPUT','SELECT'].includes(e.target.tagName)){e.preventDefault();down.add(keys[e.key]);}if(e.key.toLowerCase()==='a')sleep();});addEventListener('keyup',e=>down.delete(keys[e.key]));for(const b of document.querySelectorAll('[data-dir]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);down.add(b.dataset.dir);};b.onpointerup=b.onpointercancel=()=>down.delete(b.dataset.dir);}
function clear(){down.clear();last=performance.now();resetMotionClock(clock);}addEventListener('blur',clear);document.addEventListener('visibilitychange',clear);
function frame(now){const elapsed=Math.max(0,(now-last)/1000),dt=Math.min(.1,elapsed);last=now;if(ready&&!document.hidden){if(!paused&&document.hasFocus()){time+=dt;advanceMotionClock(clock,elapsed,()=>{const before=`${player.x},${player.y}`;advanceMotion(motion,down,false,(x,y)=>coastalWalkable(map,rocks,x,y),{runAllowed:true});if(before!==`${player.x},${player.y}`){steps++;if(footstepRipples(map.get(player.x,player.y))&&!calm)ripples.push({x:player.x*32+16,y:player.y*32+29,time});}});sync();ripples=ripples.filter(r=>time-r.time<RIPPLE_SECONDS);for(const t of turtles)updateTurtle(t,hero,dt,{calm});if(advanceDayClock(state,dt*speed))sleep(true);}else resetMotionClock(clock);render();}requestAnimationFrame(frame);}
rebuild();try{await initWorldArt();[art,waterArt,wildlife,cloudArt]=await Promise.all([load('../assets/review/coastal-format/props.json'),load('../assets/review/coastal-format/water.json'),loadWaterArt(),loadCloudArt()]);rockSprites=Array.from({length:3},(_,i)=>{const cv=document.createElement('canvas');cv.width=cv.height=32;art.draw(cv.getContext('2d'),`rock.${i}`,0,0);return cv;});ready=true;requestAnimationFrame(frame);}catch(e){$('message').textContent='Artwork could not load: '+e.message;throw e;}
export function getCoastReview(){return structuredClone({ready,contactRule:CONTACT_RULE,detail,scene,ground,identity,player,hero,movement:getMotionView(motion),time,frame:calm?0:Math.floor(time/.1)%32,paused,calm,speed,weather,shadows:settings.shadows,steps,ripples,reflections,rocks,turtles,cells:map.cells,depthBankCount:0,landBankCount:map.cells.filter(a=>a.mask!==255&&a.ground!=='sand').length,beachWaveCount:map.cells.filter(a=>a.mask!==255&&a.ground==='sand'&&a.surface.moving).length,cloudsVisible:cloudsVisible(displayedMinute(state.dayClock),weather),cloudSun:cloudSun(displayedMinute(state.dayClock)),state});}

if(new URLSearchParams(location.search).get('game')==='1'){
 document.title='The coast · Critz';document.querySelector('h1').textContent='The coast';
 document.querySelectorAll('main > p, main > .controls').forEach(el=>{if(el.id!=='message')el.hidden=true;});
 document.querySelectorAll('main > .controls')[0].hidden=false;
}
