import { character, furniture, building, tree, flower, plant, renderTank, renderWorld } from '../src/art.js';
import { scenes, buildings } from '../src/world.js';
import { createState } from '../src/state.js';
const $=id=>document.getElementById(id);
const canvas=(w,h)=>Object.assign(document.createElement('canvas'),{width:w,height:h});
const entries=[],actors=[],effects=[];
const labels={v2:'Latest draft · unapproved',prototype:'Current prototype',v1:'Rejected first draft'};
const appearances=[['Hero · boy','hero','boy'],['Hero · girl','hero','girl'],['Rival · boy','rival','boy'],['Rival · girl','rival','girl'],['Kaid','kaid','boy'],['Mom','mom','girl'],['Professor Nugget','professor','boy'],['Dr. Fern','doctor','boy'],['Aunt Ember','glassblower','boy'],['Other shopkeepers / adults','adult','boy']];
const directions=['down','left','up','right'];
const sample=createState('Gallery sample','boy','Rival sample');sample.stage='morning';sample.tankOwned=true;sample.tank.isopods=6;sample.tank.springtails=12;sample.tank.hide=true;
let paused=matchMedia('(prefers-reduced-motion: reduce)').matches,time=0,last=null;
function clean(c){const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.imageSmoothingEnabled=false;return ctx;}
function add(id,group,w,h,draw){entries.push({id,group,w,h,draw});}
for(const [name,look,gender]of appearances){
 const node=document.createElement('article');node.className='actor';const title=document.createElement('b');title.textContent=name;node.append(title);const c=canvas(128,40);c.setAttribute('aria-label',name+' facing down, left, up and right');node.append(c);const hint=document.createElement('small');hint.textContent='DOWN · LEFT · UP · RIGHT';node.append(hint);$('actors').append(node);
 const draw=(target,t,walking=true)=>{const ctx=clean(target);for(let d=0;d<4;d++)character(ctx,16+d*32,32,{look,gender,facing:directions[d],walk:walking?t*12:0});};
 actors.push({c,draw,name,look,gender});add('actor.'+look+'.'+gender,'prototype',128,40,(ctx,x,y)=>{for(let d=0;d<4;d++)character(ctx,x+16+d*32,y+32,{look,gender,facing:directions[d],walk:0});});
}
const propMap=new Map();for(const scene of Object.values(scenes))for(const o of scene.objects){const key=`${o.kind}.${o.w}x${o.h}`;propMap.set(key,{...o,x:0,y:0});}
for(const [key,o]of propMap){const w=Math.ceil(o.w*24)+16,h=Math.ceil(o.h*24)+48;add('prop.'+key,'prototype',w,h,(ctx,x,y)=>{ctx.save();ctx.translate(x+8,y+30);furniture(ctx,o,sample,0);ctx.restore();});}
const tankObject={kind:'tank',x:0,y:0,w:3,h:1.5};
for(const storyBeat of ['feeding','broken']){const s={...sample,stage:'night',storyBeat};add('tank.story.'+storyBeat,'prototype',96,88,(ctx,x,y)=>{ctx.save();ctx.translate(x+8,y+30);furniture(ctx,tankObject,s,0);ctx.restore();});}
for(const b of buildings)add('building.'+b.scene,'prototype',168,144,(ctx,x,y)=>{ctx.save();ctx.translate(x+8,y+8);building(ctx,{...b,x:0,y:0});ctx.restore();});
for(let v=0;v<2;v++)add('tree.prototype.'+v,'prototype',56,64,(ctx,x,y)=>tree(ctx,x+28,y+52,v));
for(const [i,color]of ['#f2d999','#ebc0a2','#dfafa0'].entries())add('flower.prototype.'+i,'prototype',16,16,(ctx,x,y)=>flower(ctx,x+7,y+6,color));
add('plant.prototype','prototype',32,40,(ctx,x,y)=>plant(ctx,x+16,y+30));
const tankPoster=canvas(256,128);renderTank(tankPoster,sample.tank,0);add('tank.ecosystem.composition','prototype',256,128,(ctx,x,y)=>ctx.drawImage(tankPoster,x,y));
function effect(title,w,h,draw){const n=document.createElement('article');n.className='effect';const b=document.createElement('b');b.textContent=title;n.append(b);const c=canvas(w,h);c.style.width=w+'px';c.style.height=h+'px';c.setAttribute('aria-label',title);n.append(c);$('effects').append(n);effects.push({c,draw});}
 effect('Little Root · plants, isopods & springtails',256,128,(c,t)=>renderTank(c,sample.tank,t));
 effect('Opening tank · gecko motion',128,64,(c,t)=>{const ctx=clean(c);ctx.save();ctx.translate(26,24);furniture(ctx,tankObject,{...sample,stage:'night',storyBeat:'feeding'},t);ctx.restore();});
 const yard=canvas(384,288),yardState={...sample,scene:'yard',player:{x:8,y:9,facing:'down'}};
 effect('Rescue indicator · original bobbing motion',128,64,(c,t)=>{renderWorld(yard,yardState,t);const ctx=clean(c);ctx.drawImage(yard,64,108,128,64,0,0,128,64);});
function renderMotion(){for(const a of actors)a.draw(a.c,time,$('pose').value==='walk');for(const e of effects)e.draw(e.c,time);}
function tick(now){if(last!==null&&!paused&&!document.hidden)time+=Math.min((now-last)/1000,.1);last=now;renderMotion();requestAnimationFrame(tick);}
function syncPause(){$('pause').textContent=paused?'Play':'Pause';$('pause').setAttribute('aria-pressed',String(paused));}
$('pause').onclick=()=>{paused=!paused;syncPause();};$('step').onclick=()=>{paused=true;time+=1/12;syncPause();renderMotion();};$('pose').onchange=renderMotion;document.addEventListener('visibilitychange',()=>{last=null;});syncPause();requestAnimationFrame(tick);
function image(url){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('Missing image '+url));i.src=url;});}
async function loadAtlas(version){const base=`../assets/review/environment-${version}/`;const [response,atlas]=await Promise.all([fetch(base+'atlas.json'),image(base+'atlas.png')]);if(!response.ok)throw Error('Missing atlas '+version);const data=await response.json();for(const a of data.assets){const [sx,sy,w,h]=a.rect;if(sx<0||sy<0||sx+w>atlas.width||sy+h>atlas.height)throw Error('Invalid atlas rectangle '+a.id);add(a.id,version,w,h,(ctx,x,y)=>ctx.drawImage(atlas,sx,sy,w,h,x,y,w,h));}return data.assets.length;}
function display(){const filter=$('filter').value,search=$('search').value.trim().toLowerCase();const visible=entries.filter(e=>(filter==='all'||e.group===filter)&&e.id.toLowerCase().includes(search));$('assets').replaceChildren();$('count').textContent=`${visible.length} of ${entries.length} entries`;
 for(const e of visible){const card=document.createElement('article');card.className='asset';const well=document.createElement('div');well.className='art-well';const c=canvas(e.w,e.h);const scale=Math.max(1,Math.min(4,Math.floor(120/e.w),Math.floor(100/e.h)));c.style.width=e.w*scale+'px';c.style.height=e.h*scale+'px';c.setAttribute('aria-label',e.id);e.draw(clean(c),0,0);well.append(c);const body=document.createElement('div');body.className='asset-body';const id=document.createElement('b');id.className='asset-name';id.textContent=e.id;const tag=document.createElement('span');tag.className='status '+e.group;tag.textContent=labels[e.group];const dims=document.createElement('div');dims.className='dimensions';dims.textContent=e.w+' × '+e.h+' native px';body.append(id,tag,dims);card.append(well,body);$('assets').append(card);}}
$('filter').onchange=display;$('search').oninput=display;
function sheet(){const cols=6,cw=256,ch=192,header=100;const groups=['v2','prototype','v1'];const height=header+groups.reduce((n,g)=>n+64+Math.ceil(entries.filter(e=>e.group===g).length/cols)*ch,0);const c=canvas(cols*cw,height),ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.fillStyle='#f4f2e8';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#293e35';ctx.font='bold 32px sans-serif';ctx.fillText('CRITZ — COMPLETE ASSET CONTACT SHEET',24,43);ctx.font='16px sans-serif';ctx.fillText('Existing pixels and prototype renderers · static snapshot · animations available in the gallery',24,74);let y=header;
 for(const g of groups){const items=entries.filter(e=>e.group===g);ctx.fillStyle=g==='v1'?'#895a4c':'#315e45';ctx.font='bold 23px sans-serif';ctx.fillText(labels[g]+' · '+items.length+' entries',24,y+38);y+=64;for(let i=0;i<items.length;i++){const e=items[i],x=(i%cols)*cw,yy=y+Math.floor(i/cols)*ch;ctx.fillStyle='#e0e7d6';ctx.fillRect(x+8,yy+4,cw-16,142);const scale=Math.max(1,Math.min(4,Math.floor((cw-24)/e.w),Math.floor(132/e.h)));ctx.save();ctx.translate(x+Math.floor((cw-e.w*scale)/2),yy+8+Math.floor((132-e.h*scale)/2));ctx.scale(scale,scale);e.draw(ctx,0,0);ctx.restore();ctx.fillStyle='#293e35';ctx.font='12px monospace';const text=e.id;ctx.fillText(text.slice(0,31),x+12,yy+163);if(text.length>31)ctx.fillText(text.slice(31),x+12,yy+177);ctx.font='10px sans-serif';ctx.fillStyle='#64725f';ctx.fillText(e.w+'×'+e.h,x+12,yy+189);}y+=Math.ceil(items.length/cols)*ch;}return c;}
// Export samples at uniform 2x; each frame is 64x80, with no aspect distortion.
function characterFrames(){const c=canvas(1184,120+actors.length*100),ctx=c.getContext('2d');ctx.fillStyle='#edf0e1';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#29443a';ctx.font='bold 26px sans-serif';ctx.fillText('CRITZ — PROTOTYPE CHARACTER FRAME SAMPLES',16,35);ctx.font='14px sans-serif';ctx.fillText('Four sampled phases per facing · exact 2× display · code-driven prototype, not approved sprites',16,64);for(let d=0;d<4;d++)ctx.fillText(directions[d].toUpperCase(),150+d*256,100);for(let i=0;i<actors.length;i++){const a=actors[i],y=120+i*100;ctx.fillStyle='#29443a';ctx.font='12px sans-serif';ctx.fillText(a.name.slice(0,21),12,y+38);for(let d=0;d<4;d++)for(let p=0;p<4;p++){ctx.save();ctx.translate(144+d*256+p*64,y+4);ctx.scale(2,2);character(ctx,16,32,{look:a.look,gender:a.gender,facing:directions[d],walk:p*Math.PI/2});ctx.restore();}}return c;}
function download(c,name){c.toBlob(blob=>{if(!blob){$('load-status').textContent='Could not export PNG.';return;}const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'image/png');}
$('download').onclick=()=>download(sheet(),'critz-all-assets.png');$('frames').onclick=()=>download(characterFrames(),'critz-prototype-character-frames.png');
try{await loadAtlas('v2');await loadAtlas('v1');entries.sort((a,b)=>['v2','prototype','v1'].indexOf(a.group)-['v2','prototype','v1'].indexOf(b.group));display();$('load-status').textContent=`${entries.length} entries loaded. Live motion previews are below; PNG downloads contain static views and sampled frames.`;$('download').disabled=false;$('frames').disabled=false;
 // Read-only test/export hook for reproducible artifact capture; no save access.
 window.catalog={ready:true,count:entries.length,groups:Object.fromEntries(['v2','prototype','v1'].map(g=>[g,entries.filter(e=>e.group===g).length])),sheet,characterFrames,get time(){return time;}};
}catch(error){$('load-status').textContent='Some artwork could not load. Please reload the page.';console.error(error);}
