import {SAVE_KEY,PRICE,TUBS,ROOM,hopperAt,initialState,normalize,pay,chooseTub,collect,leave,fishInTub,fishPosition,catchAt,blocked,nearTub} from './greenhouse-state.js';

import {readRenderSettings,saveRenderSettings} from '../src/render-settings.js';
import {paintShadowMask,sparkle,shinySheet} from './greenhouse-effects.js';
let renderSettings=readRenderSettings({getItem:key=>localStorage.getItem(key)});
const shadowCanvas=document.createElement('canvas');shadowCanvas.width=416;shadowCanvas.height=544;const shadowContext=shadowCanvas.getContext('2d');
const shinyCache=new Map();
const $=id=>document.getElementById(id),cv=$('world'),ctx=cv.getContext('2d');
const ASSET='../assets/review/luke-greenhouse/';
const names=['Marmalade','Lemon Drop','Dumpling','Milk Tea','Sesame','Confetti','Peaches','Inkblot','Ember','Mooncap','Caramel','Speckles','Sunset','Snowball','Pepper','Tangerine','Dorothy'];
const traits=['a determined little waddler','a bubble-chasing daydreamer','a shy leaf inspector','a curious little vacuum','a very dignified potato','a champion at looking surprised','a gentle slowpoke','a tiny plant enthusiast'];
let s=initialState(),loadError='',scene='outside',mode='cover',busy=false,calm=matchMedia('(prefers-reduced-motion: reduce)').matches;
let player={x:6,y:10,facing:'up'},luke={x:6,y:10,facing:'down'},motion=null,lukeMotion=null,time=0,last=0,held=null,stepCooldown=0;
let menuOpen=false,speechResolve=null,options=[],choiceIndex=0,selectedTub=0,fish=[],net=null,revealFish=null,revealStart=0,aim={x:240,y:158},notice='',noticeUntil=0;
let camera={x:0,y:0},scale=1,viewW=480,viewH=320;const images={},heroFrames=new Map();
try{const raw=localStorage.getItem(SAVE_KEY);if(raw)s=normalize(JSON.parse(raw));}catch(e){loadError=e.message;}
const randomSeed=()=>crypto.getRandomValues(new Uint32Array(1))[0];
const fishName=f=>names[f.kind],breed=f=>f.kind===16?'Goldfish':f.kind<8?'Ranchu':'Oranda';
function announce(text){$('live').textContent=text;}
function image(path){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error(`Could not load ${path}`));i.src=path;});}
function rect(x,y,w,h,color){ctx.fillStyle=color;ctx.fillRect(Math.round(x),Math.round(y),w,h);}
function text(value,x,y,size=10,color='#fbefce',align='left'){ctx.fillStyle=color;ctx.font=`bold ${size}px monospace`;ctx.textAlign=align;ctx.fillText(value,Math.round(x),Math.round(y));ctx.textAlign='left';}
function persist(next){if(next===s)return true;try{localStorage.setItem(SAVE_KEY,JSON.stringify(next));s=next;return true;}catch{say('Save paused','Your browser could not save this visit. No money or fish has changed. Free some storage and try again.',[{label:'OK',value:false}]);return false;}}
function say(who,line,choices=[{label:'Continue',value:true}]){held=null;$('speaker').textContent=who;$('line').textContent=line;$('speech').hidden=false;options=choices;choiceIndex=0;renderChoices();announce(`${who}: ${line}`);return new Promise(resolve=>{speechResolve=resolve;});}
function renderChoices(){$('choices').replaceChildren(...options.map((o,i)=>{const b=document.createElement('button');b.textContent=(i===choiceIndex?'▸ ':'')+o.label;b.dataset.choice=String(i);b.onclick=()=>resolveSpeech(o.value);return b;}));}
function resolveSpeech(value){if(!speechResolve)return;const resolve=speechResolve;speechResolve=null;$('speech').hidden=true;options=[];resolve(value);}
function resize(){const r=$('viewport').getBoundingClientRect();scale=r.width>=480?Math.max(1,Math.floor(r.width/480)):r.width/480;viewW=Math.max(240,Math.round(r.width/scale));viewH=Math.max(160,Math.round(r.height/scale));cv.width=viewW;cv.height=viewH;ctx.imageSmoothingEnabled=false;}
new ResizeObserver(resize).observe($('viewport'));

function drawActor(actor,move,isLuke){const x=Math.round((actor.x+.5)*32-camera.x),y=Math.round((actor.y+1)*32-camera.y);const row={down:0,up:1,left:2,right:3}[actor.facing];const frame=move?Math.floor(time/.134)%4:1;if(isLuke)ctx.drawImage(images.luke,frame*32,row*64,32,64,x-16,y-64,32,64);else{const id=row*4+frame,r=heroFrames.get(`hero-boy.${id}`);ctx.drawImage(images.hero,...r,x-16,y-64,32,64);}}
function drawTile(id,x,y){ctx.drawImage(images.tiles,id*32,0,32,32,x,y,32,32);}
function drawFish(f,x,y,top=false,shadow=false,size=32,dir=0){const col=(top&&!shadow?2:0)+Math.floor(time*3)%2;ctx.save();ctx.translate(Math.round(x),Math.round(y));if(top&&dir)ctx.rotate(dir*Math.PI/2);ctx.drawImage(shadow?sheet('silhouettes',{...f,shiny:false}):sheet('fish',f),col*32,fishRow(f),32,32,-size/2,-size/2,size,size);ctx.restore();if(f.shiny&&!shadow)sparkle(ctx,x,y,time,calm,size/32);}
function drawWorldFish(kind,x,y,top=true){const col=(top?0:2)+Math.floor(time/.24)%2;ctx.drawImage(images.fishWorld,col*16,kind*16,16,16,Math.round(x)-8,Math.round(y)-8,16,16);}
function cameraFor(actor,w,h){return {x:Math.round(416<=w?(416-w)/2:Math.max(0,Math.min(416-w,actor.x*32+16-w/2))),y:Math.round(h<=viewH?(h-viewH)/2:Math.max(0,Math.min(h-viewH,actor.y*32+32-viewH*.58)))};}
function shadowLayer(inside){paintShadowMask(shadowContext,{enabled:renderSettings.shadows,time,calm,inside,actors:inside?[player,luke]:[player]});ctx.save();ctx.globalAlpha=.15;ctx.drawImage(shadowCanvas,0,0);ctx.restore();}
function sheet(key,f){const base=images[f.kind===16?'dorothy'+({fish:'',front:'Front',fishWorld:'World',silhouettes:'Silhouettes'}[key]||''):key];if(!f.shiny)return base;const id=key+':'+f.kind+':'+f.variant;if(!shinyCache.has(id))shinyCache.set(id,shinySheet(base,f.variant||0));return shinyCache.get(id);}
function fishRow(f,size=32){return f.kind===16?0:f.kind*size;}
function drawHopper(){const h=hopperAt(time,s.visit?.seed||0),a=TUBS[h.tub],b=TUBS[h.next],p=calm?0:h.jump;const x=(a.x+1.5)*32+(b.x-a.x)*32*p,y=(a.y+.7)*32+(b.y-a.y)*32*p-Math.round(Math.sin(p*Math.PI)*44);ctx.drawImage(images.hopper,(calm?0:Math.floor(time*4)%2)*16,0,16,16,Math.round(x)-8,Math.round(y)-8,16,16);sparkle(ctx,x,y,time,calm);}
function drawRoom(){camera=cameraFor(player,viewW,544);rect(0,0,viewW,viewH,'#254b42');ctx.save();ctx.translate(-camera.x,-camera.y);
  for(let y=0;y<17;y++)for(let x=0;x<13;x++){drawTile(y<3?2:(x===0||x===12?3:(Math.min(x,12-x)+y)%4===0?1:0),x*32,y*32);if(y>=3&&(x===0||x===12)&&y%3===0)drawTile(4,x*32,y*32);}
  ctx.drawImage(images.header,0,0);
  for(let y=3;y<17;y++){rect(160,y*32,2,32,'#c2ad82');rect(254,y*32,2,32,'#c2ad82');}
  shadowLayer(true);
  for(const x of [1,5,9])ctx.drawImage(images.tankWall,x*32,32);
  for(let k=0;k<3;k++)drawWorldFish(k*5,80+k*128+Math.round(Math.sin(time*.5+k)*10),57,false);
  for(const t of TUBS){const right=t.id%2;ctx.save();ctx.translate((t.x+(right?3:0))*32,t.y*32);if(right)ctx.scale(-1,1);ctx.drawImage(images.tubVariants,Math.floor(t.id/2)*96,0,96,64,0,0,96,64);ctx.restore();ctx.drawImage(right?images.equipmentRight:images.equipmentLeft,(right?11:1)*32,t.y*32);ctx.drawImage(right?images.inletRight:images.inletLeft,t.x*32+(right?80:0),t.y*32);for(let bubble=0;bubble<2;bubble++){const by=t.y*32+26-(calm?bubble*4:Math.floor((time*5+bubble*4)%9)),bx=t.x*32+(right?83:12);rect(bx,by,2,1,'#a5cabc');rect(bx-1,by+1,1,2,'#638f8c');}for(let k=0;k<3;k++){const x=t.x*32+27+k*20+Math.round(Math.sin(time*.6+t.id+k)*5),y=t.y*32+26+Math.round(Math.cos(time*.8+k)*5);drawWorldFish((t.id*2+k)%16,x,y);}text(String(t.id+1),t.x*32+48,t.y*32+61,9,'#e4d5a6','center');}
  for(const y of [6,9,12]){ctx.drawImage(images.riserLeft,32,y*32);ctx.drawImage(images.riserRight,352,y*32);}
  drawTile(5,6*32,16*32);for(let x=1;x<12;x++)if(x!==6)rect(x*32,16*32+24,32,8,'#55664f');drawHopper();ctx.restore();
  [{a:player,m:motion,l:false},{a:luke,m:lukeMotion,l:true}].sort((a,b)=>a.a.y-b.a.y).forEach(a=>drawActor(a.a,a.m,a.l));
}
function drawOutside(){camera=cameraFor(player,viewW,416);rect(0,0,viewW,viewH,'#426c43');ctx.save();ctx.translate(-camera.x,-camera.y);
  for(let y=0;y<13;y++)for(let x=0;x<13;x++){rect(x*32,y*32,32,32,(Math.min(x,12-x)+y)%4===0?'#638348':'#5d7d45');if((Math.min(x,12-x)*7+y*3)%5===0){rect(x*32+9,y*32+18,3,2,'#799850');rect(x*32+13,y*32+16,2,3,'#799850');}}
  for(let y=7;y<13;y++){rect(160,y*32,96,32,'#c2a276');rect(161,y*32+30,94,2,'#b49670');}shadowLayer(false);ctx.drawImage(images.greenhouse,48,64);
  rect(107,140,202,29,'#294f40');rect(108,141,200,1,'#bdbb85');text("LUKE'S GREENHOUSE",208,159,12,'#fff0c6','center');
  for(const x of [122,281]){rect(x,265,13,10,'#946744');rect(x-4,252,21,14,'#315d36');rect(x,249,13,7,'#a0b660');}ctx.restore();drawActor(player,motion,false);
}
function poolTransform(){const z=Math.min(viewW/480,viewH/340);return {z,x:Math.floor((viewW-480*z)/2),y:Math.floor((viewH-340*z)/2)};}
function drawPool(){rect(0,0,viewW,viewH,'#173c38');const p=poolTransform();ctx.save();ctx.translate(p.x,p.y);ctx.scale(p.z,p.z);ctx.imageSmoothingEnabled=false;
  if(images.closeup)ctx.drawImage(images.closeup,0,0,240,160,0,0,480,320);else{rect(16,16,448,290,'#111f24');rect(30,30,420,260,'#27565a');}
  fish.forEach(f=>{const at=fishPosition(f,time);drawFish(f,at.x,at.y,true,mode!=='viewing',32,Math.round(at.angle/(Math.PI/2)));});
  // Water rings are deliberate hard native pixels; no blurred overlays.
  for(let i=0;i<6;i++){const x=65+i*64,y=85+Math.round(Math.sin(time*.6+i)*5)+(i%2)*120;rect(x,y,12,1,'#639b91');rect(x+14,y-2,4,1,'#639b91');}
  if(mode==='observing'){const x=Math.round(aim.x),y=Math.round(aim.y);ctx.strokeStyle='#efe1ac';ctx.lineWidth=2;ctx.strokeRect(x-13,y-13,26,26);rect(x-1,y-18,2,8,'#efe1ac');rect(x-1,y+10,2,8,'#efe1ac');}
  if(net){const progress=Math.min(1,(time-net.start)/.38);const nx=net.x,ny=net.y-30*(1-progress);ctx.strokeStyle='#ede0b1';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(Math.round(nx),Math.round(ny),26,19,0,0,Math.PI*2);ctx.stroke();for(let i=-15;i<=15;i+=6)rect(nx+i,ny-12,1,24,'#a0bfa1');rect(nx+20,ny+12,4,45,'#bf9567');}
  text(`TUB ${selectedTub+1} · ONE PAID SCOOP`,240,330,11,'#f6e8bf','center');if(notice&&time<noticeUntil)text(notice,240,303,11,'#fff2c7','center');ctx.restore();
}
function drawReveal(){rect(0,0,viewW,viewH,'#1c4846');const x=Math.round(viewW/2),y=Math.round(viewH*.4),t=time-revealStart;const progress=calm?1:Math.min(1,t/1.1);for(let i=0;i<12;i++){const a=i*Math.PI/6;const r=50+progress*50;rect(x+Math.round(Math.cos(a)*r),y+Math.round(Math.sin(a)*r),i%2?2:4,i%2?2:4,['#edcf88','#a8cfb1','#e39365'][i%3]);}if(t<.6&&!calm)drawFish(revealFish,x,y,true,true,96);else ctx.drawImage(sheet('front',revealFish),Math.floor(time*3)%2*32,fishRow(revealFish),32,32,x-48,y-48,96,96);if(revealFish.shiny&&(t>.6||calm))sparkle(ctx,x,y,time,calm,4);if(t>.6||calm){text(revealFish.shiny?'A SHINY LITTLE ONE!':'HELLO, LITTLE ONE!',x,y-78,12,'#e3cc95','center');text(fishName(revealFish),x,y+80,21,'#fff1cf','center');text(breed(revealFish)+' · #'+String(revealFish.serial).padStart(3,'0'),x,y+101,11,'#bed5bf','center');}}
function moveTo(actor,x,y,duration=.268){return new Promise(resolve=>{actor.facing=x>actor.x?'right':x<actor.x?'left':y>actor.y?'down':'up';const m={from:{x:actor.x,y:actor.y},to:{x,y},elapsed:0,duration,resolve};if(actor===player)motion=m;else lukeMotion=m;});}
function advanceMotion(actor,m,dt){if(!m)return null;m.elapsed+=dt;const p=Math.min(1,m.elapsed/m.duration);actor.x=m.from.x+(m.to.x-m.from.x)*p;actor.y=m.from.y+(m.to.y-m.from.y)*p;if(p>=1){actor.x=m.to.x;actor.y=m.to.y;m.resolve();return null;}return m;}
async function enter(){if(busy)return;busy=true;scene='inside';player={x:6,y:15,facing:'up'};luke={x:6,y:10,facing:'down'};mode='walk';for(let y=11;y<=14;y++)await moveTo(luke,6,y,.134);
  if(s.money<PRICE){await say('Luke',`One goldfish is $100. You have $${s.money}.`);await eject();return;}
  const yes=await say('Luke','A goldfish for $100? One scoop, one surprise. Are you in?',[{label:'Yes · $100',value:true},{label:'No',value:false}]);if(!yes){await eject();return;}
  if(!persist(pay(s,randomSeed()))){busy=false;return;}
  await say('Luke','Ok, go ahead and pick a tub');await moveTo(luke,7,14);await moveTo(luke,7,13);luke.facing='left';busy=false;announce('Paid $100. Walk to any of the eight tubs and press A.');
}
async function eject(){await say('Luke','GET OUT!');luke.facing='down';await Promise.all([moveTo(player,6,16,.21),moveTo(luke,6,15,.21)]);scene='outside';player={x:6,y:8,facing:'down'};mode='walk';busy=false;announce('Luke has ushered you back outside. No charge.');}
async function exitRoom(){if(busy)return;busy=true;if(s.visit?.status==='paid'){const yes=await say('Luke','Leaving before your scoop? I’ll return your $100.',[{label:'Leave · refund $100',value:true},{label:'Stay',value:false}]);if(!yes){player.y=15;busy=false;return;}}
  if(!persist(leave(s))){player.y=15;busy=false;return;}scene='outside';player={x:6,y:8,facing:'down'};busy=false;mode='walk';announce('Outside Luke’s Greenhouse. Admission starts again next time.');}
async function inspectTub(t){if(busy)return;busy=true;selectedTub=t.id;if(s.visit?.status==='paid'){
    const yes=await say('Luke','Are you sure you want that one?',[{label:`Yes · tub ${t.id+1}`,value:true},{label:'No',value:false}]);if(!yes){busy=false;return;}if(!persist(chooseTub(s,t.id,hopperAt(time,s.visit.seed).tub))){busy=false;return;}
    await say('Luke','Wait for a shape you like. Tap where it’s going, then the net lands. Missed? Try again.');fish=fishInTub(s.visit.seed,t.id,s.visit.rarities);mode='observing';aim={x:240,y:158};busy=false;
  }else{fish=fishInTub(s.visit?.seed||12345,t.id,s.visit?.rarities);mode='viewing';busy=false;await say('Luke','Take your time looking. Your little goldie is safe in the collection.');}
}
async function finishCatch(found){net=null;if(!found){mode='observing';notice='Missed! Wait, then try again.';noticeUntil=time+2;announce(notice);return;}
  if(!persist(collect(s,found.slot))){mode='observing';return;}revealFish=s.collection.at(-1);revealStart=time;mode='reveal';announce(`You caught ${fishName(revealFish)}, a ${breed(revealFish)}!`);
}
async function scoop(x=aim.x,y=aim.y){if(mode!=='observing'||net||speechResolve||menuOpen)return;aim={x:Math.max(45,Math.min(435,x)),y:Math.max(40,Math.min(280,y))};net={...aim,start:time};mode='scooping';}
async function action(){if(menuOpen||mode==='cover')return;if(speechResolve){resolveSpeech(options[choiceIndex].value);return;}if(busy)return;if(mode==='observing'){scoop();return;}if(mode==='reveal'){if(time-revealStart<1&&!calm)return;mode='walk';await say('Luke',`${fishName(revealFish)}! What a face. Have a look around before you go.`);return;}if(mode==='viewing'){mode='walk';return;}if(mode!=='walk'||motion)return;if(scene==='outside'){if(player.x===6&&player.y<=9){enter();}return;}const t=nearTub(player.x,player.y,player.facing);if(t){inspectTub(t);return;}if(Math.abs(player.x-luke.x)+Math.abs(player.y-luke.y)<=1){say('Luke',s.visit?.status==='paid'?'Ok, go ahead and pick a tub':'Every little face is different. Take a look around.');}}
function back(){if(mode==='cover')return;if(menuOpen){closeMenu();return;}if(speechResolve){if(options.some(o=>o.value===false))resolveSpeech(false);else resolveSpeech(options[0].value);return;}if(busy||net)return;if(mode==='observing'||mode==='viewing'){mode='walk';return;}if(mode==='reveal'){action();return;}openMenu();}
function walk(dir){if(busy||menuOpen||speechResolve||motion||mode!=='walk')return;player.facing=dir;const [dx,dy]={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[dir];const x=player.x+dx,y=player.y+dy;if(scene==='outside'){if(x===6&&y===7&&dir==='up'){enter();return;}if(x<1||x>11||y<8||y>12)return;}else{if(blocked(x,y)||x===luke.x&&y===luke.y)return;}moveTo(player,x,y).then(()=>{if(scene==='inside'&&x===6&&y===16)exitRoom();});}
function dirInput(dir){if(speechResolve){if(options.length>1){choiceIndex=(choiceIndex+(dir==='left'||dir==='up'?-1:1)+options.length)%options.length;renderChoices();}return;}held=dir;if(mode==='walk')walk(dir);}
function closeMenu(){menuOpen=false;$('menu').hidden=true;held=null;}
function menuButton(label,fn){const b=document.createElement('button');b.textContent=label;b.onclick=fn;$('menu').append(b);return b;}
function showCollection(){const cards=document.createElement('div');cards.className='collection';for(const f of s.collection){const card=document.createElement('div');card.className='fish-card';const img=document.createElement('canvas');img.width=img.height=32;img.getContext('2d').drawImage(sheet('front',f),0,fishRow(f),32,32,0,0,32,32);const b=document.createElement('b');b.textContent=fishName(f)+(f.shiny?' ✦':'');const small=document.createElement('small');small.textContent=`${breed(f)} #${String(f.serial).padStart(3,'0')} · ${traits[f.seed%traits.length]}`;card.append(img,b,small);cards.append(card);}return cards;}
function showSettings(){const el=$('menu');el.innerHTML='<h2>Settings</h2>';menuButton(renderSettings.shadows?'Shadows: On':'Shadows: Off',()=>{const next={shadows:!renderSettings.shadows};try{saveRenderSettings(localStorage,next);renderSettings=next;showSettings();}catch{announce('Could not save settings. Free some browser storage and try again.');const p=document.createElement('p');p.textContent='Could not save settings. Your setting has not changed.';el.append(p);}});menuButton(calm?'Calm motion: On':'Calm motion: Off',()=>{calm=!calm;showSettings();});menuButton('Back',openMenu);}
function openMenu(){if(busy||speechResolve||mode==='cover'||net)return;held=null;menuOpen=true;const el=$('menu');el.hidden=false;el.innerHTML='<p class="eyebrow">M1.LG2 · PLAYABLE REVIEW</p><h2>Luke’s Greenhouse</h2>';const wallet=document.createElement('p');wallet.textContent=`Review wallet: $${s.money} · ${s.collection.length} goldfish`;el.append(wallet);menuButton('Resume',closeMenu);menuButton('Your goldfish',()=>{el.replaceChildren();const h=document.createElement('h2');h.textContent='Little faces, big personalities';el.append(h);if(s.collection.length)el.append(showCollection());else{const p=document.createElement('p');p.textContent='Your first little goldie is still waiting in a tub.';el.append(p);}menuButton('Back',openMenu);});menuButton('Settings',showSettings);menuButton('How to play',()=>{el.innerHTML='<h2>One scoop. One surprise.</h2><p>Walk through the greenhouse door. Pay Luke $100, approach a tub and press A.</p><p>Watch the shapes. Tap where a fish is going to be: the net takes a moment to land. A miss costs nothing. You always receive the fish inside the net.</p><p>Keyboard: arrows / WASD to walk or aim; Z / Enter / Space for A; X / Escape for B; P opens this menu.</p><p>After your catch, browse freely. Leave and admission starts again. Leaving before catching refunds the unused scoop.</p>';menuButton('Back',openMenu);});menuButton('Review notes & restart',()=>{el.innerHTML='<h2>Art &amp; play review</h2><p>Luke is the sole goldfish seller. Ranchu have a smooth back; oranda have a dorsal fin. Colors stay secret during the scoop.</p><p>This is a fictional cameo, with original Critz fish names. The dialogue and shop rules are game inventions, not claims about the real Luke.</p><p class="subtle">Separate review wallet and collection. Fish do not transfer to your adventure save yet; no aquarium care or goldfish stocking system is implied.</p><p class="subtle">Restart clears only this review wallet and collection.</p>';menuButton('Restart review · $300',async()=>{const yes=confirm('Reset only the greenhouse review wallet and collection? Your Critz adventure save is untouched.');if(!yes)return;if(!persist(initialState()))return;closeMenu();scene='outside';player={x:6,y:10,facing:'up'};motion=lukeMotion=null;mode='walk';});menuButton('Back',openMenu);const a=document.createElement('a');a.href='../docs/reviews/M1-LG2/README.md';a.textContent='Sources and review record';el.append(a);});const a=document.createElement('a');a.href='../';a.textContent='Return to Critz';el.append(a);}

$('begin').onclick=()=>{if(loadError){$('line').textContent=loadError;return;}$('overlay').hidden=true;mode='walk';if(s.visit){scene='inside';player={x:6,y:15,facing:'up'};luke={x:7,y:13,facing:'left'};say('Luke',s.visit.status==='paid'?'Your scoop is already paid for. Go ahead and pick a tub.':'Welcome back. Your goldfish is safely saved. Take a look around.');}announce('Walk north to enter Luke’s Greenhouse.');};
$('a').onclick=action;$('b').onclick=back;$('start').onclick=()=>menuOpen?closeMenu():openMenu();
for(const b of document.querySelectorAll('[data-dir]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);dirInput(b.dataset.dir);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>{held=null;};}
const keys={ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'};
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea'))return;if(keys[e.key]){e.preventDefault();if(!e.repeat)dirInput(keys[e.key]);}else if(['z','Enter',' '].includes(e.key)){if(mode==='cover'||menuOpen)return;e.preventDefault();if(!e.repeat)action();}else if(['x','Escape'].includes(e.key)){e.preventDefault();if(!e.repeat)back();}else if(e.key==='p'){e.preventDefault();if(!e.repeat)menuOpen?closeMenu():openMenu();}});
document.addEventListener('keyup',e=>{if(keys[e.key]===held)held=null;});window.addEventListener('blur',()=>{held=null;});document.addEventListener('visibilitychange',()=>{held=null;last=0;});
cv.addEventListener('pointerdown',e=>{if(mode!=='observing')return;const r=cv.getBoundingClientRect(),p=poolTransform();scoop(((e.clientX-r.left)*viewW/r.width-p.x)/p.z,((e.clientY-r.top)*viewH/r.height-p.y)/p.z);});
function frame(now){const dt=last?Math.min(.05,(now-last)/1000):0;last=now;if(!document.hidden){if(!menuOpen&&mode!=='cover'){time+=dt;motion=advanceMotion(player,motion,dt);lukeMotion=advanceMotion(luke,lukeMotion,dt);if(held&&!speechResolve){if(mode==='observing'){const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[held];aim.x=Math.max(45,Math.min(435,aim.x+d[0]*dt*130));aim.y=Math.max(40,Math.min(280,aim.y+d[1]*dt*130));}else if(time>stepCooldown){walk(held);stepCooldown=time+.07;}}if(net&&time-net.start>=.38)finishCatch(catchAt(fish,net.x,net.y,time));}ctx.imageSmoothingEnabled=false;if(['observing','scooping','viewing'].includes(mode)){drawPool();}else if(mode==='reveal'){drawReveal();}else if(scene==='inside')drawRoom();else drawOutside();}requestAnimationFrame(frame);}
export function getReviewSnapshot(){return {state:JSON.parse(JSON.stringify(s)),scene,mode,busy,player:{...player},luke:{...luke},camera:{...camera},selectedTub,fish:fish.map(f=>({...f,...fishPosition(f,time)})),time,net,aim:{...aim},saveKey:SAVE_KEY,calm,shadows:renderSettings.shadows,hopper:hopperAt(time,s.visit?.seed||0),room:ROOM};}

try{const atlas=await fetch('../assets/playable/living/atlas.json').then(r=>{if(!r.ok)throw Error('Hero atlas failed');return r.json();});atlas.assets.forEach(a=>heroFrames.set(a.id,a.rect));const files={luke:'luke.png',fish:'fish.png',fishWorld:'fish-world.png',silhouettes:'silhouettes.png',tub:'tub.png',tubVariants:'tub-variants.png',tankWall:'tank-wall.png',tiles:'tiles.png',greenhouse:'greenhouse.png',closeup:'tub-closeup.png',front:'fish-front.png'};await Promise.all(Object.entries(files).map(async([key,path])=>{images[key]=await image(ASSET+path);}));const revised={header:'header.png',equipmentLeft:'equipment-left.png',equipmentRight:'equipment-right.png',inletLeft:'inlet-left.png',inletRight:'inlet-right.png',riserLeft:'wall-riser-left.png',riserRight:'wall-riser-right.png',greenhouse:'greenhouse.png',dorothy:'dorothy.png',dorothyFront:'dorothy-front.png',dorothyWorld:'dorothy-world.png',dorothySilhouettes:'dorothy-silhouettes.png',hopper:'gold-hopper.png'};await Promise.all(Object.entries(revised).map(async([key,path])=>{images[key]=await image('../assets/review/luke-greenhouse-r2/'+path);}));images.hero=await image('../assets/playable/living/atlas.png');for(const kind of [0,2,9]){const c=document.createElement('canvas');c.width=c.height=32;c.getContext('2d').drawImage(images.front,0,kind*32,32,32,0,0,32,32);$('cover-fish').append(c);}if(loadError){$('begin').textContent='Review save needs attention';$('overlay').querySelector('.subtle').textContent=loadError+' Your original data has been retained.';}else{$('begin').disabled=false;$('begin').textContent=s.visit?'Resume your visit':'Visit the greenhouse';}resize();requestAnimationFrame(frame);}catch(e){$('begin').textContent='Could not load the greenhouse';$('overlay').querySelector('.subtle').textContent=e.message;announce(e.message);}
