const $=s=>document.querySelector(s),base='../assets/review/overworld-v1/';
const loadImage=src=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('Could not load '+src));im.src=src;});
const fetchJSON=async path=>{const r=await fetch(path);if(!r.ok)throw Error('Could not load '+path);return r.json();};
try{
const [data,atlas,maps,hero]=await Promise.all([fetchJSON(base+'master.json'),loadImage(base+'master.png'),Promise.all([0,1,2].map(n=>fetchJSON(base+`map-${n}.json`))),loadImage('../assets/characters/hero-boy-v1/idle-south.png')]);
const by=new Map(data.tiles.map(t=>[t.id,t]));
function tile(ctx,id,x,y){const t=by.get(id);if(!t)throw Error('Missing tile '+id);ctx.drawImage(atlas,t.x,t.y,32,32,x,y,32,32);}
function renderMap(map,actor=false){const c=document.createElement('canvas');c.width=map.width*32;c.height=map.height*32;const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;for(const layer of ['ground','decal','object','foreground'])map.layers[layer].forEach((id,i)=>{if(id)tile(ctx,id,i%map.width*32,Math.floor(i/map.width)*32);});if(actor)ctx.drawImage(hero,224,272);return c;}
const town=renderMap(maps[0],true),lab=renderMap(maps[1]),terrain=renderMap(maps[2]);
let view='town';
const views={town:{source:town,rect:[0,0,1024,768],description:'Garden town · a construction sample, not a proposed change to Rootport’s map.'},cottage:{source:town,rect:[96,64,480,320],description:'480 × 320 native view · 5 × 5 cottage · exact approved Hero Boy V1 for scale.'},water:{source:town,rect:[384,352,480,320],description:'480 × 320 native view · tiled fountain, planting, bridge, shore, cliffs and waterfall.'},construction:{source:lab,rect:[0,0,960,576],description:'Shared parts build 5- and 7-cell houses, 3- and 5-cell fountains, cliffs, stairs and connected fences.'},terrain:{source:terrain,rect:[0,0,1024,768],description:'Four complete terrain families · inner and outer corners, islands, narrow joins and transitions.'}};
function resize(){const c=$('#scene'),z=$('#zoom').value,pad=innerWidth<=700?24:48,available=$('#viewer').clientWidth-pad;const scale=z==='fit'?Math.min(1,available/c.width):Number(z);c.style.width=c.width*scale+'px';c.style.height=c.height*scale+'px';}
function draw(){const v=views[view],c=$('#scene'),[x,y,w,h]=v.rect;c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.drawImage(v.source,x,y,w,h,0,0,w,h);if($('#grid').checked){ctx.strokeStyle='#183e4e88';ctx.lineWidth=1;ctx.beginPath();for(let a=0;a<=w;a+=32){ctx.moveTo(a+.5,0);ctx.lineTo(a+.5,h);}for(let b=0;b<=h;b+=32){ctx.moveTo(0,b+.5);ctx.lineTo(w,b+.5);}ctx.stroke();}$('#scene-description').textContent=v.description;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));resize();}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;draw();}));$('#grid').addEventListener('change',draw);$('#zoom').addEventListener('change',resize);addEventListener('resize',resize);
function building(){const n=Number($('#width').value),color=$('#roof').value,c=$('#building');c.width=n*32;c.height=192;const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;for(let y=0;y<6;y++)for(let x=0;x<n;x++)tile(ctx,'ground.grass.0',x*32,y*32);for(let y=0;y<3;y++)for(let x=0;x<n;x++)tile(ctx,`roof.${color}.${y}.${x===0?'left':x===n-1?'right':'center'}`,x*32,y*32);for(let y=0;y<2;y++)for(let x=0;x<n;x++){const id=x===Math.floor(n/2)?`door.wood.closed.0.${y}`:x===0||x===n-1?`wall.plaster.${y}.${x===0?'left':'right'}`:`windowbox.plaster.0.${y}`;tile(ctx,id,x*32,(y+3)*32);}ctx.drawImage(hero,Math.floor(n/2)*32,128);$('#width-label').textContent=`${n} cells`;c.style.width=n*32*2+'px';c.style.height='384px';}
$('#width').addEventListener('input',building);$('#roof').addEventListener('change',building);
const category=$('#category');category.add(new Option('All collections','all'));for(const [i,s]of data.sections.entries())category.add(new Option(s.name,String(i)));
function select(t){const c=$('#selected'),ctx=c.getContext('2d');ctx.clearRect(0,0,192,192);ctx.imageSmoothingEnabled=false;ctx.drawImage(atlas,t.x,t.y,32,32,0,0,192,192);$('#tile-id').textContent=t.id;$('#tile-info').textContent=`Cell ${t.index} · ${t.layer}\nPNG x ${t.x}, y ${t.y}\n32 × 32 · four 16 × 16 subtiles`;document.querySelectorAll('.tile-grid button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===t.id)));}
function library(){const cat=category.value,query=$('#search').value.trim().toLowerCase(),section=cat==='all'?null:data.sections[Number(cat)],end=cat==='all'?Infinity:(data.sections[Number(cat)+1]?.start??Infinity);const selected=data.tiles.filter(t=>(!section||t.index>=section.start&&t.index<end)&&t.id.includes(query));const fragment=document.createDocumentFragment();for(const t of selected){const b=document.createElement('button');b.type='button';b.title=t.id;b.setAttribute('aria-label',t.id);b.dataset.id=t.id;b.setAttribute('aria-pressed','false');const c=document.createElement('canvas');c.width=32;c.height=32;tile(c.getContext('2d'),t.id,0,0);const label=document.createElement('span');label.textContent=String(t.index).padStart(3,'0');b.append(c,label);b.addEventListener('click',()=>select(t));fragment.append(b);}$('#tiles').replaceChildren(fragment);$('#count').textContent=`${selected.length} tiles`;}
category.addEventListener('change',library);$('#search').addEventListener('input',library);draw();building();library();select(by.get('roof.clay.1.center'));document.documentElement.dataset.overworldReady='true';
}catch(error){$('#scene-description').textContent=error.message;document.documentElement.dataset.overworldReady='error';console.error(error);}
