import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {Raster} from '../raster.mjs';
import {compileContactPixels,CONTACT_RULE,compileWaterContact} from '../../../src/contact-rules.js';
import {overworldMaps} from '../../../src/overworld.js';
import {WATER_MASKS} from '../../../src/water-surfaces.js';
import {STAMPS} from '../../../map-editor/model.js';
const out='assets/playable/contact';await mkdir(out,{recursive:true});
const m=JSON.parse(await readFile('assets/playable/overworld/master.json','utf8'));
const decoded=spawnSync(process.env.PYTHON_BIN||'python3',['-c',"from PIL import Image;import sys;sys.stdout.buffer.write(Image.open(sys.argv[1]).convert('RGBA').tobytes())",'assets/playable/overworld/master.png'],{maxBuffer:100*1024*1024});if(decoded.status!==0)throw Error(decoded.stderr.toString());
const source=new Raster(m.imageWidth,m.imageHeight);source.p.set(decoded.stdout);const by=new Map(m.tiles.map(t=>[t.id,t])),entries=[],sprites=[];
function add(id,rows,footprint,kind,neighbors=null){if(kind==='building')rows=rows.map(row=>row.map(id=>id.startsWith('contact.')?id.slice(8).replace(/\.(grass|path|paving)$/ ,''):id));const image=new Raster(rows[0].length*32,rows.length*32);rows.forEach((row,y)=>row.forEach((id,x)=>{const t=by.get(id);if(!t)throw Error(id);image.blit(source.crop(t.x,t.y,32,32),x*32,y*32);}));const overheadRows=kind==='building'?3:kind==='tree'?Math.max(0,rows.length-1):0,groundBand=0,frame=compileContactPixels(image.p,image.w,image.h,{footprint,overheadRows,groundBand,neighbors});const raster=new Raster(frame.w,frame.h);raster.p.set(frame.pixels);sprites.push(raster);entries.push({id,footprint,kind,offsetY:frame.offsetY,dy:frame.dy,contact:frame.contact,w:frame.w,h:frame.h});}
for(const [scene,map]of Object.entries(overworldMaps))map.objects.forEach((o,i)=>{if(!o.collision)return;const rows=o.tiles||m.assemblies[o.id]||[[o.id]],f=[o.collision[0]-o.x,o.collision[1]-o.y,o.collision[2],o.collision[3]];const neighbors=/^(fence|hedge|cliff)\./.test(o.id)?map.objects.reduce((mask,n)=>mask|(n.y===o.y&&n.x===o.x-1&&/^(fence|hedge|cliff)\./.test(n.id)?8:0)|(n.y===o.y&&n.x===o.x+1&&/^(fence|hedge|cliff)\./.test(n.id)?2:0),0):null;add(`${scene}:${i}`,rows,f,o.kind,neighbors);if(o.id==='mill.wheel.0')for(let phase=1;phase<4;phase++)add(`${scene}:${i}:phase${phase}`,m.assemblies[`mill.wheel.${phase}`],f,'prop');if(o.fruitId)add(`${scene}:${i}:ripe`,m.assemblies['tree.apple.ripe'],f,'tree');});
const frontiers={};for(const [scene,map]of Object.entries(overworldMaps)){frontiers[scene]=[];for(const key of map.solid){const [x,y]=key.split(',').map(Number);if(x<0||y<0||x>=map.w||y>=map.h||map.terrain[y*map.w+x]==='water'||map.objects.some(o=>o.collision&&x>=o.collision[0]&&y>=o.collision[1]&&x<o.collision[0]+o.collision[2]&&y<o.collision[1]+o.collision[3]))continue;if(![[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>x+dx>=0&&y+dy>=0&&x+dx<map.w&&y+dy<map.h&&!map.solid.has(`${x+dx},${y+dy}`)))continue;const mask=(map.solid.has(`${x-1},${y}`)?8:0)|(map.solid.has(`${x+1},${y}`)?2:0),id=`frontier:${scene}:${x}:${y}`;add(id,[['hedge.10']],[0,0,1,1],'prop',mask);frontiers[scene].push({id,x,y});}}
for(const [type,s]of Object.entries(STAMPS)){let rows=s.assembly?m.assemblies[s.assembly]:[[s.tile]];if(s.kind==='building')rows=rows.map((row,y)=>row.map((id,x)=>y===s.h-1?`contact.${id}.${x===s.door[0]?'path':'grass'}`:id));add(`stamp:${type}`,rows,s.footprint,s.kind==='scenery'&&type.includes('tree')||type==='cypress'?'tree':s.kind);}
// Every unplaced collidable source remains available as a named native assembly.
for(const [id,rows]of Object.entries(m.assemblies))if(!id.startsWith('house.'))add(`catalog:${id}`,rows,[0,Math.max(0,rows.length-1),rows[0].length,1],id.startsWith('tree.')?'tree':'prop');
for(const t of m.tiles)if(/^(rock\.|bush\.|hedge\.|fence\.|planter\.|cliff\.)/.test(t.id))add(`catalog:${t.id}`,[[t.id]],[0,0,1,1],'prop',t.id.startsWith('fence.')||t.id.startsWith('hedge.')?Number(t.id.split('.')[1]):null);
// Terrain is a plane registered to the same bottom-center ground anchors.
// Transparent native halves compose with the actual neighboring ground.
const full=by.get('water.255'),stone=by.get('cliff.0.center');
for(const kind of ['water','cliff'])for(const mask of WATER_MASKS)for(let phase=0;phase<(kind==='water'?4:1);phase++){const t=kind==='water'?(phase?by.get(`anim.water.255.${phase}`):full):stone,r=source.crop(t.x,t.y,32,32),frame=new Raster(32,64),left=mask&8?0:mask&2?16:8,right=mask&2?32:mask&8?16:24;for(let yy=0;yy<32;yy++)for(let xx=left;xx<right;xx++)frame.p.set(r.p.subarray((yy*32+xx)*4,(yy*32+xx)*4+4),((yy+16)*32+xx)*4);sprites.push(frame);entries.push({id:`terrain:${kind}:${mask}${phase?':'+phase:''}`,footprint:[0,0,1,1],kind:'terrain',offsetY:0,dy:16,contact:{x:left,y:16,w:right-left,h:32},w:32,h:64});}
// Approved water compositions retain every identity/motion/depth family.
const water=JSON.parse(await readFile('assets/review/water-terrain/atlas.json','utf8')),wr=spawnSync(process.env.PYTHON_BIN||'python3',['-c',"from PIL import Image;import sys;sys.stdout.buffer.write(Image.open(sys.argv[1]).convert('RGBA').tobytes())",'assets/review/water-terrain/atlas.png'],{maxBuffer:100*1024*1024});if(wr.status!==0)throw Error(wr.stderr.toString());const ww=1024,wt=new Map(water.assets.map(a=>[a.id,a]));
for(const surface of water.surfaces)for(const mask of WATER_MASKS)for(const bank of [false,true]){const a=wt.get(surface+'.0'),p=new Uint8ClampedArray(4096);for(let yy=0;yy<32;yy++)p.set(wr.stdout.subarray(((a.y+yy)*ww+a.x)*4,((a.y+yy)*ww+a.x+32)*4),yy*128);const r=new Raster(32,64);r.p.set(compileWaterContact(p,mask,{bank,shallow:surface.includes('shallow')}));sprites.push(r);entries.push({id:`${bank?'bank':'water'}:${surface}:${mask}`,kind:'terrain',offsetY:0,dy:16,w:32,h:64,contact:CONTACT_RULE});}
for(const identity of ['fresh','ocean'])for(const motion of ['still','moving'])for(const mask of WATER_MASKS){const r=new Raster(32,64);r.p.set(compileWaterContact(null,mask,{bank:true,deep:true}));sprites.push(r);entries.push({id:`depth:${identity}.${motion}:${mask}`,kind:'terrain',offsetY:0,dy:16,w:32,h:64,contact:CONTACT_RULE});}
const editor=JSON.parse(await readFile('assets/review/map-editor/master.json','utf8')),er=spawnSync(process.env.PYTHON_BIN||'python3',['-c',"from PIL import Image;import sys;sys.stdout.buffer.write(Image.open(sys.argv[1]).convert('RGBA').tobytes())",'assets/review/map-editor/master.png'],{maxBuffer:100*1024*1024});if(er.status!==0)throw Error(er.stderr.toString());for(const dir of ['down','up','left','right']){const a=editor.tiles.find(t=>t.id===`feature.ledge-${dir}`),p=new Uint8ClampedArray(4096);for(let yy=0;yy<32;yy++)p.set(er.stdout.subarray(((a.y+yy)*1024+a.x)*4,((a.y+yy)*1024+a.x+32)*4),yy*128);const frame=compileContactPixels(p,32,32,{footprint:[0,0,1,1],neighbors:['down','up'].includes(dir)?10:0}),r=new Raster(frame.w,frame.h);r.p.set(frame.pixels);sprites.push(r);entries.push({id:`feature:ledge-${dir}`,kind:'ledge',offsetY:frame.offsetY,dy:frame.dy,w:frame.w,h:frame.h,contact:frame.contact});}
let x=0,y=0,rh=0;for(let i=0;i<entries.length;i++){const a=entries[i];if(x+a.w>1024){x=0;y+=rh;rh=0;}a.rect=[x,y,a.w,a.h];x+=a.w;rh=Math.max(rh,a.h);}const atlas=new Raster(1024,y+rh);sprites.forEach((r,i)=>atlas.blit(r,...entries[i].rect.slice(0,2)));await atlas.save(out+'/atlas.png');
const tiles=[],assemblies={};for(const a of entries){const [x,y,w,h]=a.rect,rows=[];for(let yy=0;yy<h;yy+=32){const row=[];for(let xx=0;xx<w;xx+=32){const id=`B.${a.id}.${xx/32}.${yy/32}`;row.push(id);tiles.push({id,x:x+xx,y:y+yy,width:32,height:32,assembly:a.id,contact:CONTACT_RULE});}rows.push(row);}assemblies[a.id]=rows;}
await writeFile(out+'/atlas.json',JSON.stringify({image:'atlas.png',tileSize:32,rule:CONTACT_RULE,assets:entries,tiles,assemblies,frontiers},null,2)+'\n');
await writeFile(out+'/contact.tsj',JSON.stringify({type:'tileset',version:'1.10',name:'Critz approved B contact',tilewidth:32,tileheight:32,columns:32,tilecount:atlas.w*atlas.h/1024,image:'atlas.png',imagewidth:atlas.w,imageheight:atlas.h,tiles:tiles.map(t=>({id:t.y/32*32+t.x/32,properties:[{name:'assetId',type:'string',value:t.id},{name:'contactRule',type:'string',value:'B 50% structure / 50% ground'}]}))},null,2)+'\n');console.log(`${entries.length} contact assemblies, ${tiles.length} native tiles`);
