// World time is additive v1 save data; habitat time remains the existing model.
export const DAY_START=360, DAY_END=1560, TEN_MINUTE_SECONDS=14;
export function validDayClock(c){return !!c&&Number.isInteger(c.day)&&c.day>=1&&c.day<=1e8&&Number.isInteger(c.minute)&&c.minute>=DAY_START&&c.minute<=DAY_END&&c.minute%10===0&&Number.isFinite(c.remainder)&&c.remainder>=0&&c.remainder<TEN_MINUTE_SECONDS;}
export function ensureDayClock(state){if(!validDayClock(state.dayClock))state.dayClock={day:1,minute:DAY_START,remainder:0};return state.dayClock;}
export function worldHour(state){return state.stage==='night'?22:(validDayClock(state.dayClock)?state.dayClock.minute/60:((state.time%24)+24)%24);}
export function clockLabel(c){const m=c.minute%1440,h=Math.floor(m/60);return `${h%12||12}:${String(m%60).padStart(2,'0')} ${h>=12?'pm':'am'}`;}
export function advanceDayClock(state,seconds){const c=ensureDayClock(state);if(state.stage!=='morning'||!Number.isFinite(seconds)||seconds<=0)return false;c.remainder+=seconds;while(c.remainder>=TEN_MINUTE_SECONDS&&c.minute<DAY_END){c.remainder-=TEN_MINUTE_SECONDS;c.minute+=10;}if(c.minute===DAY_END){c.remainder=0;return true;}return false;}
export function endDay(state){const c=ensureDayClock(state),hours=(1800-c.minute)/60;c.day++;c.minute=DAY_START;c.remainder=0;state.scene='bedroom';state.player={x:3,y:6,facing:'down'};return hours;}
export function paintClock(element,state,paused=false){const c=ensureDayClock(state);element.hidden=state.stage!=='morning';const label=clockLabel(c);element.dataset.paused=String(paused);element.dataset.late=String(c.minute>=1440);element.querySelector('[data-clock-day]').textContent=`Day ${c.day}`;element.querySelector('[data-clock-time]').textContent=label;element.querySelector('[data-clock-money]').textContent=`$${(state.money/100).toFixed(2)}`;element.querySelector('[data-clock-sky]').textContent=c.minute>=1200?'☾':'☀';element.style.setProperty('--hand',`${-90+180*Math.min(1,(c.minute-360)/1200)}deg`);element.setAttribute('aria-label',`Day ${c.day}, ${label}${paused?', paused':''}, $${(state.money/100).toFixed(2)}`);}
